### PR TITLE
fix listbox navigation index

### LINKED ISSUE #10077: Pressing Down Key Without Selection Highlights the Second Server
When no server is selected in the server list and you press the down arrow key, the second server gets highlighted. I find this behavior a bit odd — it would make more sense to start from the first server (even though you can technically select the first one by pressing the up key).

https://github.com/user-attachments/assets/2e926b78-ba19-445a-803c-32105470b7ad

### PR DESCRIPTION
**Pull request by ASKLL-STAR**
fix #10077

The original code incorrectly added the offset `1` to the base index `0` and did not handle EDGE CASE separately.
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/ui_listbox.cpp [hunk 1]
```diff
@@ -209,7 +209,10 @@ int CListBox::DoEnd()
 	m_ScrollbarShown = m_ScrollRegion.ScrollbarShown();
 	if(m_ListBoxNewSelOffset != 0 && m_ListBoxNumItems > 0 && m_ListBoxSelectedIndex == m_ListBoxNewSelected)
 	{
-		m_ListBoxNewSelected = clamp((m_ListBoxNewSelected == -1 ? 0 : m_ListBoxNewSelected) + m_ListBoxNewSelOffset, 0, m_ListBoxNumItems - 1);
+		if(m_ListBoxNewSelected == -1 && m_ListBoxNewSelOffset > 0)
```
Comment (Robyt3) [inline src/game/client/ui_listbox.cpp:212]: The `m_ListBoxNewSelOffset > 0` check should be redundant here. Whenever no item is selected then the next selection should be the first item.

File: src/game/client/ui_listbox.cpp [hunk 2]
```diff
@@ -209,7 +209,10 @@ int CListBox::DoEnd()
...
+			m_ListBoxNewSelected = 0;
+		else
+			m_ListBoxNewSelected = clamp((m_ListBoxNewSelected == -1 ? 0 : m_ListBoxNewSelected) + m_ListBoxNewSelOffset, 0, m_ListBoxNumItems - 1);
```
Comment (Robyt3) [inline src/game/client/ui_listbox.cpp:215]: The `m_ListBoxNewSelected == -1` check here is then also redundant with the above change because it's already covered by that branch.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

**Review by Robyt3 — APPROVED** [review]
