### PR TITLE
Fix specchar transparency and move spec-char to character snap (fixes #4123, #3816)

### LINKED ISSUE #4123: Spec char should be moved to CCharacter::Snap

### PR DESCRIPTION
**Pull request by fokkonaut**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/server/player.cpp [hunk 1]
```diff
@@ -424,24 +424,6 @@ void CPlayer::Snap(int SnappingClient)
 			return;
 		pRaceInfo->m_RaceStartTick = m_pCharacter->m_StartTime;
 	}
-
-	bool ShowSpec = m_pCharacter && m_pCharacter->IsPaused();
-
-	if(SnappingClient >= 0)
-	{
-		CPlayer *pSnapPlayer = GameServer()->m_apPlayers[SnappingClient];
-		ShowSpec = ShowSpec && (GameServer()->GetDDRaceTeam(id) == GameServer()->GetDDRaceTeam(SnappingClient) || pSnapPlayer->m_ShowOthers == 1 || (pSnapPlayer->GetTeam() == TEAM_SPECTATORS || pSnapPlayer->IsPaused()));
```
Comment (fokkonaut) [inline src/game/server/player.cpp:433]: Also fixes incorrect usage of `id` here.
