### PR TITLE
Kill unfinishable teams if they don't enter /practice within a minute

### LINKED ISSUE #4088: Improve start line skip patch
A non started tee leaving the team makes the team unfinishable. This made a couple teams fail some with multiple hours in their timers. Without #3091 system messages are unreadable to some of our players and some players flat out ignore system messages.

Ideas:
1. We could just kill such unfinishable teams
2. We could nag them with system messages every 10s until they switch to practice mode

I don't see a way to address this case properly without falling victim to the case in https://github.com/ddnet/ddnet/pull/3959#discussion_r673216749

### PR DESCRIPTION
**Pull request by heinrich5991**
This is to avoid players playing in unfinishable teams for a long time
if they don't understand the system messages.

Fixes #4088.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/server/teams.cpp [hunk 1]
```diff
@@ -127,6 +129,7 @@ void CGameTeams::OnCharacterStart(int ClientID)
 	{
 		ChangeTeamState(m_Core.Team(ClientID), TEAMSTATE_STARTED);
 		m_TeamSentStartWarning[m_Core.Team(ClientID)] = false;
+		m_TeamSentStartWarning[m_Core.Team(ClientID)] = false;
```
Comment (Learath2) [inline src/game/server/teams.cpp:132]: Duplicate line

**Review by Learath2 — CHANGES_REQUESTED** [review]

File: src/game/server/ddracechat.cpp [hunk 2]
```diff
@@ -916,10 +907,7 @@ void CGameContext::UnlockTeam(int ClientID, int Team)
 
 	char aBuf[512];
 	str_format(aBuf, sizeof(aBuf), "'%s' unlocked your team.", Server()->ClientName(ClientID));
-
-	for(int i = 0; i < MAX_CLIENTS; i++)
-		if(((CGameControllerDDRace *)m_pController)->m_Teams.m_Core.Team(i) == Team)
-			SendChatTarget(i, aBuf);
+	SendChatTarget(Team, aBuf);
```
[the remark this answers is not in the document]
Comment (heinrich5991) [reply src/game/server/ddracechat.cpp]: Done.

File: src/game/server/teams.cpp (hunk 1 above)
Comment (heinrich5991) [reply src/game/server/teams.cpp]: Oh, that's actually a bug, a different line needs to go there. Nice find.

**Comment by Learath2** [comment]
LGTM

bors r+

**Comment by murpii** [comment]
@heinrich5991 The warning message is abit to long:

image

**Comment by heinrich5991** [comment]
Ah, this is in the console. Should I try and put it into two lines?

**Comment by murpii** [comment]
> Ah, this is in the console. Should I try and put it into two lines?

That would be great. It's also cut off in the regular chat.
