### PR TITLE
Fix demo rename not working if names only differ in capitalization

### LINKED ISSUE #10878: Demo renaming isn't case sensitive
If you try to rename a demo, by changing a lowercase to uppercase letter, it doesn't want to save and says, that the demo exists already

Image

### PR DESCRIPTION
**Pull request by Robyt3**
Closes #10878.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/components/menus.cpp [hunk 1]
```diff
@@ -1570,11 +1570,16 @@ void CMenus::RenderPopupFullscreen(CUIRect Screen)
...
+			if(str_comp(aBufOld, aBufNew) == 0)
+			{
+				// Nothing to rename, also same capitalization
+			}
+			else if(!str_valid_filename(m_DemoRenameInput.GetString()))
 			{
 				PopupMessage(Localize("Error"), Localize("This name cannot be used for files and folders"), Localize("Ok"), POPUP_RENAME_DEMO);
 			}
-			else if(Storage()->FileExists(aBufNew, m_vpFilteredDemos[m_DemolistSelectedIndex]->m_StorageType))
+			else if(str_utf8_comp_nocase(aBufOld, aBufNew) != 0 && // Allow renaming if it only changes capitalization to support case-insensitive filesystems
```
Comment (AssassinTee) [inline src/game/client/components/menus.cpp:1581]: I find it quite interesting, that this needs to be fixed like this and that file exists doesn't have a case sensitive flag or something. But I guess it works in this case

Comment (Robyt3) [reply src/game/client/components/menus.cpp:1581]: Windows has no API for checking whether a file exists with specific capitalization. The filesystem is case-insentive by default, so renaming a file to a name that already exists with same or different capitalization would overwrite the file that has the new name, because renaming and moving a file are also the same operation. Conversely, you can open an existing file using any capitalization of its name, which is effectively how checking whether a file exists works.

**Comment by ChillerDragon** [comment]
Works on my linux, but linux is also the sanest os of them all. The troll os macOS also does some weird stuff with fs casing. Should ideally be checked there before merging it.

**Comment by ChillerDragon** [comment]
Works on my macOS too.
