### PR TITLE
Fix `console_enable_colors` not being used, save `console_output_level` and `console_enable_colors` variables

### LINKED ISSUE #6447: `console_enable_colors` is unused and not saved, `console_output_level` is not saved
Usage of `console_enable_colors` was removed by #5013 (@heinrich5991).

Both `console_enable_colors` and `console_output_level` are not and have never been saved to the config. I think they should be saved.

### PR DESCRIPTION
**Pull request by Robyt3**
Closes #6447.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/shared/config_variables.h [hunk 1]
```diff
@@ -12,8 +12,8 @@ MACRO_CONFIG_INT(PlayerCountry, player_country, -1, -1, 1000, CFGFLAG_SAVE | CFG
 MACRO_CONFIG_STR(Password, password, 32, "", CFGFLAG_CLIENT | CFGFLAG_SERVER | CFGFLAG_NONTEEHISTORIC, "Password to the server")
 MACRO_CONFIG_STR(Logfile, logfile, 128, "", CFGFLAG_SAVE | CFGFLAG_CLIENT | CFGFLAG_SERVER, "Filename to log all output to")
 MACRO_CONFIG_INT(Loglevel, loglevel, 2, 0, 4, CFGFLAG_SAVE | CFGFLAG_CLIENT | CFGFLAG_SERVER, "Log level (0 = Error, 1 = Warn, 2 = Info, 3 = Debug, 4 = Trace)")
-MACRO_CONFIG_INT(ConsoleOutputLevel, console_output_level, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SERVER, "Adjusts the amount of information in the console")
-MACRO_CONFIG_INT(ConsoleEnableColors, console_enable_colors, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SERVER, "Enable colors in console output")
+MACRO_CONFIG_INT(ConsoleOutputLevel, console_output_level, 0, 0, 2, CFGFLAG_SAVE | CFGFLAG_CLIENT | CFGFLAG_SERVER, "Adjusts the amount of information in the console")
```
Comment (def-) [inline src/engine/shared/config_variables.h:15]: Why save them? I forgot the motivation for not saving them.

Comment (heinrich5991) [reply src/engine/shared/config_variables.h:15]: Not save them because people will provide incomplete logs. Not sure why you'd want to save them.

Comment (Robyt3) [reply src/engine/shared/config_variables.h:15]: The default value for `console_output_level` is `0`, so user's logs per default will contain the least information possible anyway. Not saving the variable makes it harder to get the log messages that are printed when the client starts.

It was never saved since it was added by oy 13 years ago in cabecb7fa937b5e4efa859ea62722468f91a5089.

Also we are saving `loglevel`: https://github.com/ddnet/ddnet/blob/971b166488ed2e2f5fd418e1234b7d0b01725bb7/src/engine/shared/config_variables.h#L14

**Review by def- — APPROVED** [review]
bors r+
