### PR TITLE
Fix invalid team count in scoreboard for split teams

### LINKED ISSUE #8681: Team count wrong
From [Discord](https://discord.com/channels/252358080522747904/757720336274948198/1269636434403397673):
> [2:41 PM]xteriche: why 6?
> image
> [2:42 PM]xteriche: if you count there are 8 of us
> [3:13 PM]RedRay32: does he count on one side only?

### PR DESCRIPTION
**Pull request by archimede67**
Fixes #8681.

DDNet_rcQue7LR2c

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/components/scoreboard.cpp [hunk 1]
```diff
@@ -319,7 +319,7 @@ void CScoreboard::RenderScoreboard(CUIRect Scoreboard, int Team, int CountStart,
 	// render player entries
 	int CountRendered = 0;
 	int PrevDDTeam = -1;
-	int CurrentDDTeamSize = 0;
+	static int s_CurrentDDTeamSize = 0;
```
Comment (heinrich5991) [inline src/game/client/components/scoreboard.cpp:322]: `static` variables shouldn't be used. You could use a member variable, but even that sounds wrong here. Why does the render method need to keep state?

Comment (Robyt3) [reply src/game/client/components/scoreboard.cpp:322]: Same applies to the `s_TeamStartY` and `s_TeamStartX` variables below. We call the function once for every panel of the scoreboard, but teams can span over two panels (or even 3 panels with 128 players).

Comment (archimede67) [reply src/game/client/components/scoreboard.cpp:322]: `static` variables are used everywhere within the code base. The method needs to keep state because the scoreboard is not rendered in a single pass, the render method is called multiple times depending on which side to render.

Comment (Robyt3) [reply src/game/client/components/scoreboard.cpp:322]: > `static` variables are used everywhere within the code base.

In a perfect world there wouldn't be any `static`, non-`const` variables, so there would be no global state and we could instantiate any class multiple times and also not rely on static initialization (which for example only happens once on Android, so we currently need additional hacks there). UI elements are likely the worst offender in terms of `static` variables at the moment, because we don't have a better system for allocating UI element IDs yet (at compile-time if possible).

I generally try to remove `static`, non-`const` variables when refactoring, e.g. in #8682.

In this case, we could encapsulate the static variables as member variables of a class `CScoreboardRenderState` and then pass a reference to that to the `RenderScoreboard` function (no member variable necessary).

Comment (archimede67) [reply src/game/client/components/scoreboard.cpp:322]: > In this case, we could encapsulate the static variables as member variables of a class CScoreboardRenderState and then pass a reference to that to the RenderScoreboard function (no member variable necessary).

This would be a great solution indeed. So if you want, I can implement this and remove the static variable usage in this method.

Comment (archimede67) [reply src/game/client/components/scoreboard.cpp:322]: I must also agree that avoiding `static`s is better, but I've seen it used so many times that I'm not sure, maybe sometimes using `static` is not that bad depending on the context of course.

**Review by heinrich5991 — APPROVED** [review]
Thanks!
