### PR TITLE
Properly initialize all `CClient` member variables, improve integration test script

### LINKED ISSUE #7553: Valgrind finds many uninitialized member variables
Many valgrind errors "Conditional jump or move depends on uninitialised value" appear when running the integration test (also in the CI). For some reason this doesn't cause the CI to fail though it probably should.

The uninitialized variables are likely the result of #6256, which removed the `mem_zero` of `CClient`.

Full error log at 0213535dd8ce88e9eb2088c894a9536a05736758: [valgrind.log](https://github.com/ddnet/ddnet/files/13468322/valgrind.log)

### PR DESCRIPTION
**Pull request by Robyt3**
Closes #7553.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: scripts/integration_test.sh [hunk 1]
```diff
@@ -85,8 +89,8 @@ function fail()
 	echo "[-] $1 exited with code $2"
 }
 
-# TODO: check for open ports instead
-port=17822
+# Get unused port from the system by binding to port 0 and immediately closing the socket again
+port=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()');
```
Comment (Chairn) [inline scripts/integration_test.sh:93]: python3

**Review by def- — APPROVED** [review]

File: src/engine/client/client.h [hunk 2]
```diff
@@ -86,78 +86,76 @@ class CClient : public IClient, public CDemoPlayer::IListener
...
+	SHA256_DIGEST m_MapdownloadSha256 = SHA256_ZEROED;
+
+	bool m_MapDetailsPresent = false;
+	char m_aMapDetailsName[256] = "";
+	int m_MapDetailsCrc = 0;
+	SHA256_DIGEST m_MapDetailsSha256 = SHA256_ZEROED;
+	char m_aMapDetailsUrl[256] = "";
 
 	char m_aDDNetInfoTmp[64];
-	std::shared_ptr<CHttpRequest> m_pDDNetInfoTask;
```
Comment (Kaffeine) [inline src/engine/client/client.h:160]: [std::shared_ptr](https://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr) is a class with a default constructor. There is no need in assignment.
