### PR TITLE
Fix #662 (timer command displays the wrong state)

### LINKED ISSUE #662: /timer chat message wrong
https://github.com/necropotame/ddnet/blob/6a9406dc81fd3cdfaedd1a60bbf70ce6964dc81c/src/game/server/ddracechat.cpp#L1182

This chat message outputs the current /timer-mode.
Since commands which change the timer-mode (e.g. /timer cycle) get executed afterwards, the string contains the old mode, but not the new one. So the chat-message should be moved a bit down, I guess.

### PR DESCRIPTION
**Pull request by necropotame**

### CODE REVIEW

File: src/game/server/ddracechat.cpp [hunk 1]
```diff
@@ -1283,60 +1283,59 @@ void CGameContext::ConSetTimerType(IConsole::IResult *pResult, void *pUserData)
...
 		}
+	
+		if((OldType == CPlayer::TIMERTYPE_BROADCAST || OldType == CPlayer::TIMERTYPE_GAMETIMER_AND_BROADCAST) && (pPlayer->m_TimerType == CPlayer::TIMERTYPE_GAMETIMER || pPlayer->m_TimerType == CPlayer::TIMERTYPE_NONE))
+			pSelf->SendBroadcast("", pResult->m_ClientID);
 	}
 	
-	if((OldType == CPlayer::TIMERTYPE_BROADCAST || OldType == CPlayer::TIMERTYPE_GAMETIMER_AND_BROADCAST) && (pPlayer->m_TimerType == CPlayer::TIMERTYPE_GAMETIMER || pPlayer->m_TimerType == CPlayer::TIMERTYPE_NONE))
-		pSelf->SendBroadcast("", pResult->m_ClientID);
+	char aBuf[128];
+	const char msg[3][128] = {"game/round timer.", "broadcast.", "both game/round timer and broadcast."};
```
Comment (heinrich5991) [inline src/game/server/ddracechat.cpp]: Can be `static const s_aaMsg`.

File: src/game/server/ddracechat.cpp [hunk 2]
```diff
@@ -1283,60 +1283,59 @@ void CGameContext::ConSetTimerType(IConsole::IResult *pResult, void *pUserData)
...
+					pPlayer->m_TimerType = CPlayer::TIMERTYPE_GAMETIMER;
+			}
+			else
+			{
+				if(pPlayer->m_TimerType < CPlayer::TIMERTYPE_NONE)
+					pPlayer->m_TimerType = CPlayer::TIMERTYPE_NONE;
+				else if(pPlayer->m_TimerType == CPlayer::TIMERTYPE_NONE)
+					pPlayer->m_TimerType = CPlayer::TIMERTYPE_BROADCAST;
+			}
 		}
```
Comment (heinrich5991) [inline src/game/server/ddracechat.cpp]: Maybe add an error case if you pass an invalid second parameter.

**Comment by heinrich5991** [comment]
Thanks!
