### PR TITLE
Show command completions with leading spaces

### LINKED ISSUE #8619: help shown when chaining commands does not work when there are leading spaces:
`command1 args; command2 args`
`              ^             `

will cause help to not be shown for command2. Removing the space shows help

### PR DESCRIPTION
**Pull request by Pioooooo**
Closes #8619.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/components/console.cpp [hunk 1]
```diff
@@ -482,7 +482,7 @@ void CGameConsole::CInstance::GetCommand(const char *pInput, char (&aCmd)[IConso
 		aInput[m_CompletionCommandEnd] = '\0';
 	}
 
-	str_copy(aCmd, aInput + m_CompletionCommandStart, sizeof(aCmd));
+	str_copy(aCmd, str_skip_whitespaces_const(aInput + m_CompletionCommandStart), sizeof(aCmd));
```
Comment (heinrich5991) [inline src/game/client/components/console.cpp]: Is this correct or should `m_CompletionCommandStart` be adjusted instead? What depends on `m_CompletionCommandStart`?

Comment (Pioooooo) [reply src/game/client/components/console.cpp]: The replacement start for tab completion. Fixed now.

**Review by heinrich5991 — APPROVED** [review]
Thanks! :)
