### PR TITLE
fix calculation of m_Angle of CCharacterCore

### LINKED ISSUE #4138: 0.7 way of m_Angle setup causes aim to jump
If a server sends [the 0.7 way of angle](https://github.com/teeworlds/teeworlds/blob/master/src/game/gamecore.cpp#L104), while someone is aiming straight left (angle -803 to +804, the border), then the aim of this guy jumps up for a sec, looking like a bot, but then its fine again.
[The ddnet way](https://github.com/ddnet/ddnet/blob/master/src/game/gamecore.cpp#L139-L149) of handling m_Angle for some reason doesnt cause this visual glitch, neither on ddnet or 0.7.

### LINKED ISSUE #4969: Wrong calculation of m_Angle in CCharacterCore
I have a funny bug for you today, which is already for more than 11 years in the code and certainly already noticed by a few. Spoiler in 0.7 it is already fixed. I would suggest we also fix it
It is about this function
our angle: https://github.com/C0D3D3V/ddnet/blob/dbd9c40893a18dccb7f70f0e2bb77c4384877973/src/game/gamecore.cpp#L143-L152
0.7 angle: https://github.com/teeworlds/teeworlds/blob/81c95de3f14b9df1947bf67347784730aba7bed1/src/game/gamecore.cpp#L103

result of the calculation using our function and the new form 0.7: (first column are coordinates)
```
          our       new
0|1:      201       402
1|1:      201       201
1|0:      0         0
1|-1:     -201      -201
0|-1:     -201      -402
-1|-1:    1005      -603
-1|0:     804       804
-1|1:     603       603
```

Since the angle is only used for client side display and not for physics
This is a visual bug 😄 You can see it in the following video

 Left is the player, Right is the view of a other player
https://user-images.githubusercontent.com/14315968/162616126-3fe48abc-2c9e-453c-b6cf-a95da70c755a.mp4

### PR DESCRIPTION
**Pull request by C0D3D3V**
fixes #4969
fixes #4138
The problem of #4138 can be seen in the following picture:
image

we have a strange angle circle, it was fixed in 0.7. For 0.7 to interpolate correctly between two network packets we should send the correct angle circle. 

The poblem from #4969 I have already described and follows directly from the wrong calculation. 

The PR fixes both problems. Here is a video, first I show how it behaves now in our client, then in a 0.7 client.

https://user-images.githubusercontent.com/14315968/162630563-83847e3f-4d29-48d9-adc1-fb3ba20cc387.mp4

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/server/entities/character.cpp [hunk 1]
```diff
@@ -1132,6 +1132,10 @@ void CCharacter::SnapCharacter(int SnappingClient, int ID)
 			return;
 
 		pCore->Write(reinterpret_cast<CNetObj_CharacterCore *>(static_cast<protocol7::CNetObj_CharacterCore *>(pCharacter)));
+		if(pCharacter->m_Angle > (int)(pi * 256.0f))
+		{
+			pCharacter->m_Angle -= (int)(2.0f * pi * 256.0f);
+		}
```
Comment (fokkonaut) [inline src/game/server/entities/character.cpp:1138]: That shouldnt happen here. Either in the other place you worked in or in CGameCore::Write(), depending on why this is necessary.

Comment (C0D3D3V) [reply src/game/server/entities/character.cpp:1138]: because 0.7 uses a different angular circle, we store our circle and convert it to 0.7

**Comment by Chairn** [comment]
Well, the jump in the first trigonometric circle is correct as the difference is 2pi. So it's just a cosmetic change?

File: src/game/gamecore.cpp [hunk 2]
```diff
@@ -138,16 +138,15 @@ void CCharacterCore::Tick(bool UseInput)
 		m_Direction = m_Input.m_Direction;
 
 		// setup angle
-		float a = 0;
-		if(m_Input.m_TargetX == 0)
-			a = atanf((float)m_Input.m_TargetY);
+		float tmp_angle = atan2f(m_Input.m_TargetY, m_Input.m_TargetX);
+		if(tmp_angle < -(pi / 2.0))
```
Comment (Chairn) [inline src/game/gamecore.cpp:142]: 2.0f to prevent double promotion

**Comment by C0D3D3V** [comment]
> So it's just a cosmetic change?
I do it because of this https://user-images.githubusercontent.com/14315968/162616126-3fe48abc-2c9e-453c-b6cf-a95da70c755a.mp4
but @fokkonaut pointed out the 0.7 bug so I fixed that to

**Comment by Chairn** [comment]
I don't understand what's wrong in the video as i can't really watch 2 screens at the same time

File: src/game/server/entities/character.cpp (hunk 1 above)
Comment (fokkonaut) [reply src/game/server/entities/character.cpp:1138]: Shouldnt it only be sent to 0.7 like this then? Or should we completely adapt to the 0.7 way?
I dont see the reason for doing it in ccharacter::snap, when we could just store it like that directly

**Comment by C0D3D3V** [comment]
@Chairn 
pause at second 0.8 there you see the player on the left aim up. Other player will see him aim to the top right.

**Comment by fokkonaut** [comment]
> I don't understand what's wrong in the video as i can't really watch 2 screens at the same time

Its the bind where you can aim directly in 45° steps, its known that the angle is wrongly shown then.

File: src/game/gamecore.cpp (hunk 2 above)
Comment (C0D3D3V) [reply src/game/gamecore.cpp]: done

File: src/game/server/entities/character.cpp (hunk 1 above)
Comment (C0D3D3V) [reply src/game/server/entities/character.cpp:1138]: CGameCore::Write() is also used for CCharacterCore::Quantize() so there we can't switch between different circles. I find the SnapCharacter() function quite suitable, since we have all the tanslation layers for 0.7 there anyway. 

If we would switch to the 0.7 angle we have to send the old angle circle for old clients, because otherwise exactly the bug from #4138 would happen for them. It happens because the angles are different and we interpolate between the last two network packets see: 
https://github.com/C0D3D3V/ddnet/blob/5ba4ddd6dc0a8648504e09b3f483f0fd77f6170a/src/game/client/components/players.cpp#L114-L118

https://github.com/teeworlds/teeworlds/blob/26d24ec061d44e6084b2d77a9b8a0a48e354eba6/src/game/client/components/players.cpp#L111-L116

Comment (C0D3D3V) [reply src/game/server/entities/character.cpp:1138]: > Shouldnt it only be sent to 0.7 like this then? 

thats exactly the case. That is what `Server()->IsSixup(SnappingClient)` takes care of

Comment (C0D3D3V) [reply src/game/server/entities/character.cpp:1138]: > Or should we completely adapt to the 0.7 way?
since this is only a visual matter and not a physical property, it doesn't really matter how we store it. But since most clients are ddnet (0.6) clients and therefore use our circle, it doesn't make much sense to save the 0.7 angle circle and convert it every time.

Comment (fokkonaut) [reply src/game/server/entities/character.cpp:1138]: > > Shouldnt it only be sent to 0.7 like this then? 
> 
> thats exactly the case. That is what `Server()->IsSixup(SnappingClient)` takes care of
> 

didnt see that

**Comment by def-** [comment]
bors r+
Thanks
