### PR TITLE
Preserve super on hot reload, fix hot reload crashes

### LINKED ISSUE #9156: hot_reload loses super state
screenshot_2024-10-19_13-38-23

I was trying to iterate on designs in this part of the map. And found my self being sent back to spawn.

### PR DESCRIPTION
**Pull request by KebsCS**
Fixes #9156 for both super and /invincible

Fixed a crash when in super with an empty previous team and when players were on a different teams during hot reload

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I don't think it's a good idea to include invincibility and super in `CSaveTee`. Perhaps we can add an abstraction around that `CSaveTee` that encompasses the things we need for hot reload beyond what is actually saved in `/save`?

**Comment by KebsCS** [comment]
> I don't think it's a good idea to include invincibility and super in `CSaveTee`. Perhaps we can add an abstraction around that `CSaveTee` that encompasses the things we need for hot reload beyond what is actually saved in `/save`?

Done, also moved `m_apSavedTeleTees` that was used to save `/lasttp` to the new `CSaveHotReloadTee` class

File: src/game/server/save.cpp [hunk 1]
```diff
@@ -482,6 +482,26 @@ bool CSaveTee::IsHooking() const
 	return m_HookState == HOOK_GRABBED || m_HookState == HOOK_FLYING;
 }
 
+void CSaveHotReloadTee::Save(CCharacter *pChr, bool AddPenalty)
+{
+	m_SaveTee.Save(pChr, AddPenalty);
+	m_Super = pChr->m_Core.m_Super;
+	m_Invincible = pChr->m_Core.m_Invincible;
+
+	if(pChr->m_pPlayer)
```
Comment (Robyt3) [inline src/game/server/save.cpp:491]: This check looks unnecessary to me. A character's player should never be `nullptr`. Also, if it was `nullptr` here then `m_SavedTeleTee` wouldn't be initialized.

File: src/game/server/save.h [hunk 2]
```diff
@@ -148,6 +148,21 @@ class CSaveTee
 	char m_aGameUuid[UUID_MAXSTRSIZE];
 };
 
+class CSaveHotReloadTee
+{
+public:
+	CSaveHotReloadTee() = default;
+	~CSaveHotReloadTee() = default;
+	void Save(CCharacter *pchr, bool AddPenalty = true);
+	bool Load(CCharacter *pchr, int Team, bool IsSwap = false);
```
Comment (Robyt3) [inline src/game/server/save.h:157]: `pChr` or `pCharacter`

File: src/game/server/save.h [hunk 3]
```diff
@@ -148,6 +148,21 @@ class CSaveTee
...
+
+private:
+	CSaveTee m_SaveTee;
+	int m_Super;
+	int m_Invincible;
```
Comment (Robyt3) [inline src/game/server/save.h:162]: Use `bool`s instead of `int`s

**Review by Robyt3 — CHANGES_REQUESTED** [review]

**Comment by KebsCS** [comment]
@Robyt3 Done!

**Comment by Robyt3** [comment]
You accidentally changed the ddnet-libs submodule.

**Review by Robyt3 — APPROVED** [review]
