### PR TITLE
Keep veto right after joining dummy with lower ID (fixes #3404)

### LINKED ISSUE #3404: Veto doesn't work after joining dummy
Konsti writes:
> When u are on a server and already got veto u lose it when connecting ur dummy until u disconnect dummy, makes no sense for me

Learath2:
> for veto we should probably check both players and determine whether the ip has a veto

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Diff without whitespace is easier to understand: https://github.com/ddnet/ddnet/pull/3405/files?w=1

File: src/engine/shared/config_variables.h [hunk 1]
```diff
@@ -314,6 +314,7 @@ MACRO_CONFIG_INT(SvShowOthersDefault, sv_show_others_default, 0, 0, 2, CFGFLAG_S
 MACRO_CONFIG_INT(SvShowAllDefault, sv_show_all_default, 0, 0, 1, CFGFLAG_SERVER, "Whether players see all tees by default")
 MACRO_CONFIG_INT(SvMaxAfkTime, sv_max_afk_time, 0, 0, 9999, CFGFLAG_SERVER, "The time in seconds a player is allowed to be afk (0 = disabled)")
 MACRO_CONFIG_INT(SvMaxAfkVoteTime, sv_max_afk_vote_time, 300, 0, 9999, CFGFLAG_SERVER, "The time in seconds a player can be afk and his votes still count (0 = disabled)")
```
Comment (Banana090) [inline src/engine/shared/config_variables.h:316]: I think It will just stop count your vote after 5 minutes, isnt It?

Comment (Banana090) [reply src/engine/shared/config_variables.h:316]: I mean ignoring the next configuración option of Sv_MaxVetoAfkTime

Comment (def-) [reply src/engine/shared/config_variables.h:316]: Not sure I understand

Comment (Banana090) [reply src/engine/shared/config_variables.h:316]: SvMaxAfkVoteTime seems to conflict with SvMaxAfkVetoTime.
Your SvMaxAfkVetoTime is greater then MaxAfkVoteTime and I think after SvMaxAfkVoteTime passes you Will lose your veto anyway, because you'll lose your whole voring right

Comment (def-) [reply src/engine/shared/config_variables.h:316]: The code in this change is supposed to prevent exactly that. But to be honest I haven't tested it.

**Comment by heinrich5991** [comment]
The bugfix is definitely fine.

I don't really see the use case for the other thing though.

**Comment by def-** [comment]
> Add sv_max_afk_veto_time 
> and set it to 20 minutes by default. Following a discussion on #bugs
> where Дядя Женя got map changed during smoke break.

So if a player is playing a long map with dummy and leaves for 5 minutes the map can be changed and they have no wait. I removed the change, I expected not to get in a new config.

**Comment by heinrich5991** [comment]
bors r+

Merging pure bugfixes is a no-brainer. Thanks. :)
