### PR TITLE
Fix: Speedups not working at 0/0 and top left map border

### LINKED ISSUE #12054: Any speedup at 0/0 or the top left mapborder is not working
Speedups with Mapindex 0/0 are not considered valid, because

```C++
int CCollision::IsSpeedup(int Index) const
{
	if(Index < 0 || !m_pSpeedup)
		return 0;

	if(m_pSpeedup[Index].m_Force > 0)
		return Index;

	return 0;
}
```

returns Index 0 for them.

I debugged the server, it runs into https://github.com/ddnet/ddnet/blob/d0a1e423423f1aac6da3eb213bc384dfd8e5de4e/src/game/server/entities/character.cpp#L1479

### PR DESCRIPTION
**Pull request by AssassinTee**
Fix speedups not working at 0/0 and top left map border. `IsSpeedup` fortunately has only one usage* which is doubled due to prediction. This breaks prediction for older clients.

closes #12054
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or Valgrind's memcheck](https://github.com/ddnet/ddnet/blob/master/docs/DEBUGGING.md#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)
- [x] I didn't use generative AI to generate more than single-line completions

### CODE REVIEW

File: src/game/collision.cpp [hunk 1]
```diff
@@ -730,15 +730,9 @@ int CCollision::IsTeleportHook(int Index) const
...
+bool CCollision::IsSpeedup(int Index) const
 {
-	if(Index < 0 || !m_pSpeedup)
-		return 0;
-
-	if(m_pSpeedup[Index].m_Force > 0)
-		return Index;
-
-	return 0;
+	return Index >= 0 && m_pSpeedup && m_pSpeedup[Index].m_Force > 0;
```
Comment (heinrich5991) [inline src/game/collision.cpp]: Index can't be `< 0` in the only call site of this function. Could you remove this or make it a `dbg_assert` instead?

**Review by heinrich5991 — APPROVED** [review]
I think it's sensible to fix this bug. It doesn't seem to break maps, according to @AssassinTee's research. :)

**Comment by Pioooooo** [comment]
need to bump teehistorian version (this should be written to the label description and/or after the PR checklist for physics)

**Comment by AssassinTee** [comment]
> It doesn't seem to break maps

I don't know what classifies as "breaking maps". This bug is doable on 2 ddnet maps and might "invalidate" the one or other run, but this doesn't allow insane skips or give you an advantage on this two maps (as the nature of this bug is to be at the top left corner)

**Comment by AssassinTee** [comment]
I don't know how to fix these teehistorian issue/tests

**Comment by heinrich5991** [comment]
The setup is annoying. You have to change the teehistorian minor version in the tests, too:

https://github.com/ddnet/ddnet/blob/1df20ec533891a635e5aa5617d5e058659c06349/src/test/teehistorian_test.cpp#L113

**Review by Robyt3 — APPROVED** [review]
