### PR TITLE
Fix out of bounds access in RenderPlayer (fixes #2365)

### LINKED ISSUE #2365: Array out of bounds access in `CPlayers::RenderPlayer`
https://github.com/ddnet/ddnet/blob/df66d83a04789b628d1526e9414ec9f4c231a7e8/src/game/client/components/ghost.cpp#L343

ClientID: -2

https://github.com/ddnet/ddnet/blob/df66d83a04789b628d1526e9414ec9f4c231a7e8/src/game/client/components/players.cpp#L218

Access to array with index -2.

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

File: src/game/client/components/players.cpp [hunk 1]
```diff
@@ -230,7 +230,7 @@ void CPlayers::RenderPlayer(
 
 	vec2 Direction = GetDirection((int)(Angle*256.0f));
 	vec2 Position;
-	if(in_range(ClientID, MAX_CLIENTS-1))
+	if(ClientID >= 0)
```
Comment (Learath2) [inline src/game/client/components/players.cpp:233]: Hm, doesn't this also remove the upper bound?

Comment (def-) [reply src/game/client/components/players.cpp:233]: I don't think the upper-bound check made sense here because previously in this function we always access m_aClients[ClientID] without checking upper bound.

Comment (def-) [reply src/game/client/components/players.cpp:233]: Checked and there are only two ways this function is called, with `for(int i = 0; i < MAX_CLIENTS; i++)` and explicitly with `-2`, so it's fine.

**Comment by Learath2** [comment]
Okay then. LGTM

bors r+
