### PR TITLE
Fix/Feature: Hide ips in mutes if showips is disabled and show player names

### LINKED ISSUE #11242: The `mutes` and `unmute` commands leak ips
By default `show_ips` is set to 0 and no ips should be shown. This can leak ips to helpers who might not even have access to the `show_ips` command. Same applies to bans but I think for mutes it is even stronger because one can quickly mute without interrupting the gameplay to dump an ip. While banning is a stronger action anyways.

I solved a similar issue in [ddnet-insta](https://github.com/ddnet-insta/ddnet-insta/) by showing the player name instead of their ip when `show_ips` is off. That is often more useful information anyways when trying to get a list of muted or banned players. For bans that is of course a bit tricky because they might be saved to a bans.cfg and not include a name. Anyways showing names is the nicest but requires a bit of code and setup. Alternatively it could also just show XXX everywhere like it does with the `status` command and then there is no way to differentiate entries based on ip only based on reason and time. Or it could show a unique placeholder for every ip in all places.

For reference this is the current situation for someone who has no access to `show_ips`

```
> muteid 13 200 sorry test xd
2025-11-14 16:59:21 I server: ClientId=1 rcon='muteid 13 200 sorry test xd'
2025-11-14 16:59:21 I chat: *** 'yu' has been muted for 200 seconds (sorry test xd)
> mutes
2025-11-14 16:59:26 I server: ClientId=1 rcon='mutes'
2025-11-14 16:59:26 I mutes: #0 '127.0.0.1' muted for 195 seconds (sorry test xd)
2025-11-14 16:59:26 I mutes: 1 mute, showing entries 0 - 0 (page 1/1)
> unmute 0
2025-11-14 16:59:29 I server: ClientId=1 rcon='unmute 0'
2025-11-14 16:59:29 I mutes: Unmuted: 127.0.0.1
```

That entire flow would still work if it looked like this

```
> muteid 13 200 sorry test xd
2025-11-14 16:59:21 I server: ClientId=1 rcon='muteid 13 200 sorry test xd'
2025-11-14 16:59:21 I chat: *** 'yu' has been muted for 200 seconds (sorry test xd)
> mutes
2025-11-14 16:59:26 I server: ClientId=1 rcon='mutes'
2025-11-14 16:59:26 I mutes: #0 XXX muted for 195 seconds (sorry test xd)
2025-11-14 16:59:26 I mutes: 1 mute, showing entries 0 - 0 (page 1/1)
> unmute 0
2025-11-14 16:59:29 I server: ClientId=1 rcon='unmute 0'
2025-11-14 16:59:29 I mutes: Unmuted: XXX
```

### PR DESCRIPTION
**Pull request by AssassinTee**
This PR hides IPs in the mutes menu, if you have show-ips disabled. Additionally it adds player names to the mutes table in order to make unmuting or moderating this list easier

screenshot_2025-11-17_17-50-37
(please don't attack my IP)

closes #11242

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/server/mutes.cpp [hunk 1]
```diff
@@ -228,7 +240,9 @@ void CGameContext::ConMuteIp(IConsole::IResult *pResult, void *pUserData)
 	}
 
 	const char *pReason = pResult->NumArguments() > 2 ? pResult->GetString(2) : "";
-	pSelf->m_Mutes.Mute(&Addr, pResult->GetInteger(1), pReason, false);
+
+	// We don't have a muted client name here, this is a mute by ip ban
+	pSelf->m_Mutes.Mute(&Addr, pResult->GetInteger(1), pReason, "[MUTED-BY-IP]", false);
```
Comment (AssassinTee) [inline src/game/server/mutes.cpp]: @ChillerDragon Is it fine to add this as player name if I muted by IP and don't have a player name?

File: src/engine/server/server.cpp [hunk 2]
```diff
@@ -680,6 +680,14 @@ bool CServer::GetClientInfo(int ClientId, CClientInfo *pInfo) const
 	return false;
 }
 
+bool CServer::CanShowIps(int ClientId) const
```
Comment (ChillerDragon) [inline src/engine/server/server.cpp]: I implemented the same method when doing the same fix for `deep_jails` and I thought a while about the name. I ended up using `HasShowIpsOn` because it is a thing that can be turned on and off. Its not about the ability to turn it on or off. But idk no hard feelings.

https://github.com/ddnet-insta/ddnet-insta/blob/620af6aa1f4de8d897551209859b897ffe29fb31/src/engine/server/instagib/server.cpp#L142-L147

File: src/engine/server/server.cpp [hunk 3]
```diff
@@ -680,6 +680,14 @@ bool CServer::GetClientInfo(int ClientId, CClientInfo *pInfo) const
...
+{
+	dbg_assert(ClientId >= 0 && ClientId < MAX_CLIENTS, "Invalid ClientId: %d", ClientId);
+	if(m_aClients[ClientId].m_State != CClient::STATE_INGAME)
+		return false;
```
Comment (ChillerDragon) [inline src/engine/server/server.cpp]: Should probably return true here, for econ, fifo and logger. Before the assert actually. Because -1 is a special admin id.

File: src/engine/server/server.cpp (hunk 2 above)
Comment (AssassinTee) [reply src/engine/server/server.cpp]: I can rename this for you, no hard feelings :heart:

File: src/game/server/mutes.cpp (hunk 1 above)
Comment (ChillerDragon) [reply src/game/server/mutes.cpp]: I would go with empty string instead of magic string.

File: src/game/server/mutes.cpp [hunk 4]
```diff
@@ -148,10 +149,21 @@ void CMutes::Print(int Page) const
...
+		{
+			char aAddrString[NETADDR_MAXSTRSIZE];
+			net_addr_str(&Addr, aAddrString, sizeof(aAddrString), false);
+
+			log_info(m_pSystemName, "#%d %s: '%s' muted for %d seconds (%s)",
+				Count, MuteEntry.m_aClientName, aAddrString, MuteEntry.SecondsLeft(), MuteEntry.m_aReason[0] == '\0' ? "No reason given" : MuteEntry.m_aReason);
+		}
+		else
+		{
+			log_info(m_pSystemName, "#%d %s: muted for %d seconds (%s)",
```
Comment (ChillerDragon) [inline src/game/server/mutes.cpp]: Missing single quotes around the player name

File: src/engine/server/server.cpp (hunk 2 above)
Comment (Robyt3) [reply src/engine/server/server.cpp]: I think that's the wrong approach for show-ips. Use the special syntax `<{%s}>` like for `status` so the console will censor the output automatically.

File: src/game/server/mutes.cpp [hunk 5]
```diff
@@ -305,7 +320,7 @@ void CGameContext::ConVoteMuteIp(IConsole::IResult *pResult, void *pUserData)
 	}
 
 	const char *pReason = pResult->NumArguments() > 2 ? pResult->GetString(2) : "";
-	pSelf->m_VoteMutes.Mute(&Addr, pResult->GetInteger(1), pReason, false);
+	pSelf->m_VoteMutes.Mute(&Addr, pResult->GetInteger(1), pReason, "[NOVOTE-BY-IP]", false);
```
Comment (ChillerDragon) [inline src/game/server/mutes.cpp]: Again I would go with `nullptr` or `""` here instead of a magic string on call site.

File: src/engine/server/server.cpp (hunk 3 above)
Comment (AssassinTee) [reply src/engine/server/server.cpp]: This function is removed, see Robyts comment above

File: src/engine/server/server.cpp (hunk 2 above)
Comment (AssassinTee) [reply src/engine/server/server.cpp]: This made this PR so much easier :star: I am amazed

File: src/game/server/mutes.cpp [hunk 6]
```diff
@@ -228,7 +232,9 @@ void CGameContext::ConMuteIp(IConsole::IResult *pResult, void *pUserData)
 	}
 
 	const char *pReason = pResult->NumArguments() > 2 ? pResult->GetString(2) : "";
-	pSelf->m_Mutes.Mute(&Addr, pResult->GetInteger(1), pReason, false);
+
+	// we don't have a muted client name here, this is a mute by ip ban
```
Comment (ChillerDragon) [inline src/game/server/mutes.cpp]: Not sure if we need the comment, but I don't really care tbh.

File: src/game/server/mutes.cpp [hunk 7]
```diff
@@ -148,10 +149,13 @@ void CMutes::Print(int Page) const
...
 			break;
 		}
+
 		char aAddrString[NETADDR_MAXSTRSIZE];
 		net_addr_str(&Addr, aAddrString, sizeof(aAddrString), false);
-		log_info(m_pSystemName, "#%d '%s' muted for %d seconds (%s)",
-			Count, aAddrString, MuteEntry.SecondsLeft(), MuteEntry.m_aReason[0] == '\0' ? "No reason given" : MuteEntry.m_aReason);
+
+		log_info(m_pSystemName, "#%d '%s': addr=<{%s}> muted for %d seconds (%s)",
+			Count, MuteEntry.m_aClientName, aAddrString, MuteEntry.SecondsLeft(), MuteEntry.m_aReason[0] == '\0' ? "No reason given" : MuteEntry.m_aReason);
```
Comment (ChillerDragon) [inline src/game/server/mutes.cpp]: Can we split every argument on a new line here? I don't like long lines.

**Comment by ChillerDragon** [comment]
Thanks for working on this @AssassinTee I didn't do a full test yet either, but so far looking at the code it looks good.

File: src/game/server/mutes.cpp (hunk 6 above)
Comment (AssassinTee) [reply src/game/server/mutes.cpp]: doesn't hurt I guess? :shrug: resolving

File: src/game/server/mutes.cpp (hunk 7 above)
Comment (AssassinTee) [reply src/game/server/mutes.cpp]: done :+1:

File: src/game/server/mutes.cpp [hunk 8]
```diff
@@ -148,10 +149,19 @@ void CMutes::Print(int Page) const
...
 		}
+
 		char aAddrString[NETADDR_MAXSTRSIZE];
 		net_addr_str(&Addr, aAddrString, sizeof(aAddrString), false);
-		log_info(m_pSystemName, "#%d '%s' muted for %d seconds (%s)",
-			Count, aAddrString, MuteEntry.SecondsLeft(), MuteEntry.m_aReason[0] == '\0' ? "No reason given" : MuteEntry.m_aReason);
+
+		log_info(
+			m_pSystemName,
+			"#%d '%s': addr=<{%s}> muted for %d seconds (%s)",
```
Comment (Robyt3) [inline src/game/server/mutes.cpp]:
```suggestion
			"#%d '%s' (<{%s}>) muted for %d seconds (%s)",
```

File: src/game/server/mutes.cpp [hunk 9]
```diff
@@ -228,7 +238,9 @@ void CGameContext::ConMuteIp(IConsole::IResult *pResult, void *pUserData)
 	}
 
 	const char *pReason = pResult->NumArguments() > 2 ? pResult->GetString(2) : "";
-	pSelf->m_Mutes.Mute(&Addr, pResult->GetInteger(1), pReason, false);
+
+	// we don't have a muted client name here, this is a mute by ip ban
+	pSelf->m_Mutes.Mute(&Addr, pResult->GetInteger(1), pReason, "", false);
```
Comment (Robyt3) [inline src/game/server/mutes.cpp]: I think a non-empty placeholder name like you had before would look better in the list of mutes, e.g. `(unknown)` or `(unknown name)`. I think that name would also make it clear enough without the comment. Also below.

File: src/game/server/mutes.cpp [hunk 10]
```diff
@@ -269,7 +281,6 @@ void CGameContext::ConUnmuteIp(IConsole::IResult *pResult, void *pUserData)
 void CGameContext::ConMutes(IConsole::IResult *pResult, void *pUserData)
 {
 	CGameContext *pSelf = (CGameContext *)pUserData;
-
```
Comment (Robyt3) [inline src/game/server/mutes.cpp:272]: I prefer the empty line consistently in all command callback functions here.

File: src/game/server/gamecontext.h [hunk 11]
```diff
@@ -90,7 +91,7 @@ class CMutes
 public:
 	CMutes(const char *pSystemName);
 
-	bool Mute(const NETADDR *pAddr, int Seconds, const char *pReason, bool InitialDelay);
+	bool Mute(const NETADDR *pAddr, int Seconds, const char *pReason, const char *pClientName, bool InitialDelay);
 	void UnmuteIndex(int Index);
```
Comment (Robyt3) [inline src/game/server/gamecontext.h:96]: What about the unmute functions? They currently also print the address without censoring.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

File: src/game/server/gamecontext.h (hunk 11 above)
Comment (AssassinTee) [reply src/game/server/gamecontext.h:96]: 🤦 ah he even showed that in the issue, ofc

File: src/game/server/mutes.cpp (hunk 9 above)
Comment (ChillerDragon) [reply src/game/server/mutes.cpp]: The all lowercase parenthesis style looks much more teeish I like it better than the previous placeholder.
But I still think this should not happen on call site but when the name is printed. It should be formatted differently on print. Maybe without the single quotes. Then it can be differentiated from a player called literally (unknown).

**Comment by AssassinTee** [comment]
@Robyt3 added unmutes and tested ign:

screenshot_2025-11-17_19-22-30

File: src/game/server/mutes.cpp (hunk 9 above)
Comment (Robyt3) [reply src/game/server/mutes.cpp]: The comment by @ChillerDragon wasn't addressed. I also think it would make sense to format it without the single quotes if the name is unknown. Should use a separate `bool` to determine whether the name is available.

**Comment by AssassinTee** [comment]
Here with IP ban and `unknown name`

screenshot_2025-11-17_22-40-05

File: src/game/server/mutes.cpp [hunk 12]
```diff
@@ -46,6 +46,17 @@ bool CMutes::Mute(const NETADDR *pAddr, int Seconds, const char *pReason, bool I
...
 		str_copy(Mute.m_aReason, pReason);
 		Mute.m_InitialDelay = InitialDelay;
+		if(pClientName)
+		{
+			str_copy(Mute.m_aClientName, pClientName);
+			Mute.m_NameKnown = true;
+		}
+		else
+		{
+			str_copy(Mute.m_aClientName, "unknown name");
```
Comment (Robyt3) [inline src/game/server/mutes.cpp]: I think this value shouldn't be used when the name is not known, so only set `Mute.m_aClientName[0] = '\0';` here. Then change the log messages for `Unmuted: ...` below such that `unknown name` is printed if `!m_NameKnown` and so the quotes are only printed when the name is known.

Comment (ChillerDragon) [reply src/game/server/mutes.cpp]: I would also go with `(unknown)` to match the style of `(connecting)`

Comment (AssassinTee) [reply src/game/server/mutes.cpp]: I am already doing this btw, I just set the name to unknown name anyway. We have the m_NameKnown flag which I already check against.
