### PR TITLE
fix laser bounce delay affecting other laser types beside rifle

### LINKED ISSUE #10551: Doors rendered incorrectly sometimes in editor and in-game
Image

Image

The horrizontal door is a local edit that is not present in the first image, just for comparison with vertical ones. It is correctly rendered sometimes but sometimes not. Map: bullseye

### PR DESCRIPTION
**Pull request by AssassinTee**
The tuning parameter `laser_bounce_delay` affects the rendering of other laser types e.g. doors, grabbers, etc. This is ofc. not intended.

closes #10551

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/gamecore.h [hunk 1]
```diff
@@ -64,6 +64,8 @@ class CTuningParams
 	bool Get(const char *pName, float *pValue) const;
 	static const char *Name(int Index) { return ms_apNames[Index]; }
 	float GetWeaponFireDelay(int Weapon) const;
+
+	static CTuningParams DEFAULT;
```
Comment (Robyt3) [inline src/game/gamecore.h]: This should be `const`. Maybe also added in a separate commit first to replace other default tuning params.

**Comment by AssassinTee** [comment]
@Robyt3 added a seperate commit which changes the use of default tunings. I tested this ingame and didn't find any issues, provided the asign operator of CTuningParams does what it's supposed to. I hope I didn't miss any, may be hard to tell sometimes.

File: src/game/client/gameclient.cpp [hunk 2]
```diff
@@ -4397,7 +4396,7 @@ void CGameClient::LoadMapSettings()
 	CTuningParams TuningParams;
```
Comment (Robyt3) [inline src/game/client/gameclient.cpp]: Remove

File: src/game/client/components/items.cpp [hunk 3]
```diff
@@ -366,7 +366,7 @@ void CItems::RenderLaser(vec2 From, vec2 Pos, ColorRGBA OuterColor, ColorRGBA In
 		vec2 Dir = normalize_pre_length(Pos - From, Len);
 
 		float Ms = TicksBody * 1000.0f / Client()->GameTickSpeed();
-		float a = Ms / GameClient()->GetTuning(TuneZone)->m_LaserBounceDelay;
+		float a = Ms / (Type == LASERTYPE_RIFLE ? GameClient()->GetTuning(TuneZone)->m_LaserBounceDelay : CTuningParams::DEFAULT.m_LaserBounceDelay);
```
Comment (l-ouis) [inline src/game/client/components/items.cpp]: `((Type == LASERTYPE_RIFLE || Type == LASERTYPE_SHOTGUN) ? ...`

**Review by l-ouis — CHANGES_REQUESTED** [review]

File: src/game/client/components/items.cpp (hunk 3 above)
Comment (AssassinTee) [reply src/game/client/components/items.cpp]: Oh I need to test this

Comment (AssassinTee) [reply src/game/client/components/items.cpp]: @l-ouis very smart, good catch 👍
