### PR TITLE
Move ddnet character display info in ddnet character

### LINKED ISSUE #5455: Maybe a bug in the snapshot system
If a snapshot is spitted into multiple parts, the client receive them as `NETMSG_SNAP` identified by there part number.
There can be up to 64 parts. And in this line is checked if all parts were received 
https://github.com/ddnet/ddnet/blob/cd8706a84ab928a37d11b2c9a18ca4e91c5007e5/src/engine/client/client.cpp#L1946

But I think the check is wrong, because `m_SnapshotParts[Conn]` is of type `unsigned` and as far as I know `unsigned` is only 32bit long. I think we should use `uint64_t` for the parts bit array. 

But maybe I'm wrong. But since very big snapshots are very rare (I could not even get it triggered myself, somewhere must be an other limit that prevents to many snaps in a snapshot), I think this bug is not often triggered.

### PR DESCRIPTION
**Pull request by C0D3D3V**
- I also added the default value mechanic for Net Objects that have set `validate_size=False`
- I removed the ramp value from the snap, because currently all maps use the default tuning parameters for it
- I renamed `m_FreezeTick` to `m_FreezeStart` 

- Added Extended Net Objects to the debug HUD (Also added a Headline):
grafik
(out of range) is in the screenshot the old DDNetCharacterDisplayInfo

fixes #5455

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Learath2** [comment]
If the ramp value is tunable, things shouldn't break if it's tuned. @trml could we predict this value w.r.t the current tunezone the character is in somehow?

**Comment by C0D3D3V** [comment]
It is already predict... (and I already use the predicted values but only of the own char) but prediction is off if you spectate other players...

**Comment by C0D3D3V** [comment]
I would say thats a problem for the future, and should be fixed by sending the tunings of other players efficient to the client.

**Comment by trml** [comment]
Yes, thinking about it, it would be possible to query the tuning directly just based on the position in the map, without going through the predicted gameworld, using just the player position (which is approximately what the prediction does in CCharacter::HandleTuneLayer). Perhaps using Collision()->IsTune() and CGameClient::GetTuning()

**Comment by C0D3D3V** [comment]
@heinrich5991 if I join with these changes included on a old server for example 15.9.1 and 16.0.3. The client crashes because of different `malloc(): invalid next size (unsorted)` exceptions. Seems to be because I extend the DDnetCharacter, (since we never really extended snapshots this bug was probably always in there? maybe it is because my default value mechanic does not work idk)

**Comment by heinrich5991** [comment]
Sounds like a buffer overflow. `malloc` detects that its internal structures were overwritten.

I don't know where this comes from, but probably because you write over some object's boundaries?

**Comment by Chairn** [comment]
ASAN is of great help in the case you're trying to debug ;)

**Comment by trml** [comment]
Since almost all player input is now sent after this extension of ddnetchar (it now includes mouse targets), it would be nice to also include fire presses at the same time for completeness (as a separate character flag).

**Comment by C0D3D3V** [comment]
Other player presses like left and right are also still missing, so this should maybe be discussed in an other issue.

**Comment by C0D3D3V** [comment]
This does no longer crash on old servers. As requested by Heinrich I added default values to Net Objects that have `validate_size=False`.
But I do get now prediction errors when someone hooks (or interacts with) you (to see the errors you have to activate the debug hug).

**Comment by C0D3D3V** [comment]
Mh, after the rebase to master, I have no more prediction errors xD but the fire input is broken. I will investigate tomorrow.

**Comment by C0D3D3V** [comment]
Since this changes critical parts... please review it good :) 
At least it passed all ingame and demo tests for me.

File: src/engine/server/server.cpp [hunk 1]
```diff
@@ -3745,10 +3745,6 @@ void CServer::SnapFreeID(int ID)
 
 void *CServer::SnapNewItem(int Type, int ID, int Size)
 {
-	if(Type > 0xffff)
-	{
-		g_UuidManager.GetUuid(Type);
```
Comment (heinrich5991) [inline src/engine/server/server.cpp:3750]: Why was this removed? It looks like an assert to me.

Comment (C0D3D3V) [reply src/engine/server/server.cpp:3750]: I thought this is unused code because the result of GetUuid is not used. But maybe I missed that this could trigger an assert that would otherwise be missed. I will look at it tonight.

Comment (C0D3D3V) [reply src/engine/server/server.cpp:3750]: grafik
grafik

there is no assert

Comment (C0D3D3V) [reply src/engine/server/server.cpp:3750]: it is just useless code

**Comment by C0D3D3V** [comment]
rebased to master.

Any more comments/review?
@heinrich5991  do you still want to have this in 16.2?

**Comment by def-** [comment]
bors r+
Let's get it in for 16.2-rc7 test

**Comment by def-** [comment]
bors retry
