### PR TITLE
Fix `sv_vanilla_antispoof` for vanilla 0.6.5 clients

### LINKED ISSUE #2074: Vanilla Client 0.6.5 can't connect to DDNet servers?
As reported by Skeith on Discord. Please verify, seems to happen on Windows and client just closes. Would be great if we can fix it server-side.

### PR DESCRIPTION
**Pull request by Robyt3**
This fixes issues that prevented vanilla 0.6.5 clients from joining DDNet servers with `sv_vanilla_antispoof 1` (closes #2074).

The dummy map was not valid. The size of the tiles and game layers was calculated incorrectly. The last member variable included in `CMapItemLayerTilemap` version 2 should be `m_Data`. Previously only the size of the member `m_aName` was subtracted from the total size, which was resulting in an incorrect item size, as the size of the following 5 members also needs to be subtracted.

The handshake messages were packed incorrectly. The message ID and the system flag were not added to the six packers that are passed to `SendMsgs`. The lines that are removed in this function seemed to assume that the message ID was already added but not packed, which was no longer the case. Presumable at some point `CMsgPacker` was changed without adapting the vanilla antispoof feature. Now, the message ID and system flag are properly packed when initially creating the message packers.

The `dummy_map` tool is improved to also print the generated map file's hashes and data as a C style array, so the data can immediately be copied to `network_server.cpp`.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [X] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Nice
bors r+

File: src/engine/message.h [hunk 1]
```diff
@@ -17,6 +17,11 @@ class CMsgPacker : public CPacker
 	{
 		Reset();
 	}
+
+	void PackMessageSystem()
+	{
+		AddInt((m_MsgID << 1) | (m_System ? 1 : 0));
+	}
```
Comment (heinrich5991) [inline src/engine/message.h:24]: This looks like it is at the wrong abstraction level. Should probably rather go into `CNetServer::SendMsgs`, `CMsgPacker` doesn't know about the encoding of the message IDs.
