### PR TITLE
Fix memory leak on team finish and read of uninitialized data

### LINKED ISSUE #2522: Game UUID is discarded on load
This means that the save is incomplete in the teehistorian. Should fix.

### LINKED ISSUE #3144: heap-buffer-overflow in CSaveTee
```
=================================================================
==18021==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61e001fb3a6c at pc 0x00000046e7fe bp 0x7fff0fb4c7e0 sp 0x7fff0fb4bf58
READ of size 42 at 0x61e001fb3a6c thread T0
    #0 0x46e7fd in printf_common(void*, char const*, __va_list_tag*) (/home/teeworlds/servers/DDNet-Server-asan+0x46e7fd)
    #1 0x46ed3c in __vsnprintf_chk (/home/teeworlds/servers/DDNet-Server-asan+0x46ed3c)
    #2 0x6e7296 in vsnprintf /usr/include/x86_64-linux-gnu/bits/stdio2.h:80:10
    #3 0x6e7296 in str_format /home/teeworlds/src/master/src/base/system.c:2396
    #4 0x6158aa in CSaveTee::GetString(CSaveTeam const*) /home/teeworlds/src/master/src/game/server/save.cpp:226:2
    #5 0x618a1c in CSaveTeam::GetString() /home/teeworlds/src/master/src/game/server/save.cpp:541:58
    #6 0x63c67b in CGameTeams::ProcessSaveTeam() /home/teeworlds/src/master/src/game/server/teams.cpp:722:43
    #7 0x5f5e8b in CGameControllerDDRace::Tick() /home/teeworlds/src/master/src/game/server/gamemodes/DDRace.cpp:28:10
    #8 0x5bfa36 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:754:17
    #9 0x556073 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #10 0x561a56 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #11 0x7fc869bba09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #12 0x448a99 in _start (/home/teeworlds/servers/DDNet-Server-asan+0x448a99)

0x61e001fb3a6c is located 0 bytes to the right of 2540-byte region [0x61e001fb3080,0x61e001fb3a6c)
allocated by thread T1 here:
    #0 0x51fcb2 in operator new[](unsigned long) (/home/teeworlds/servers/DDNet-Server-asan+0x51fcb2)
    #1 0x6190a3 in CSaveTeam::FromString(char const*) /home/teeworlds/src/master/src/game/server/save.cpp:618:18
    #2 0x62e31a in CScore::LoadTeamThread(IDbConnection*, ISqlData const*, bool) /home/teeworlds/src/master/src/game/server/score.cpp:1477:43
    #3 0x528aa3 in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, bool) /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:216:7
    #4 0x5283d5 in CDbConnectionPool::Worker() /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:174:8
    #5 0x527529 in CDbConnectionPool::Worker(void*) /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:132:9
    #6 0x6e9d5d in thread_run /home/teeworlds/src/master/src/base/system.c:694:2
    #7 0x7fc869d7ffa2 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7fa2)

Thread T1 created by T0 here:
    #0 0x4d91fd in pthread_create (/home/teeworlds/servers/DDNet-Server-asan+0x4d91fd)
    #1 0x6e9f80 in thread_init /home/teeworlds/src/master/src/base/system.c:706:16
    #2 0x6e9f80 in thread_init_and_detach /home/teeworlds/src/master/src/base/system.c:777
    #3 0x52710a in CDbConnectionPool::CDbConnectionPool() /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:65:2
    #4 0x5405a1 in CServer::CServer() /home/teeworlds/src/master/src/engine/server/server.cpp:325:26
    #5 0x561339 in CreateServer() /home/teeworlds/src/master/src/engine/server/server.cpp:3444:45
    #6 0x561339 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3468
    #7 0x7fc869bba09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/teeworlds/servers/DDNet-Server-asan+0x46e7fd) in printf_common(void*, char const*, __va_list_tag*)
Shadow bytes around the buggy address:
  0x0c3c803ee6f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c803ee700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c803ee710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c803ee720: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c803ee730: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3c803ee740: 00 00 00 00 00 00 00 00 00 00 00 00 00[04]fa fa
  0x0c3c803ee750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c803ee760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c803ee770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c803ee780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c803ee790: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==18021==ABORTING
```

### PR DESCRIPTION
**Pull request by Zwelf**
Fixes #2522, fixes #3144 and fixes second leak from #3134.

### CODE REVIEW

File: src/game/server/save.cpp [hunk 1]
```diff
@@ -320,7 +320,7 @@ int CSaveTee::FromString(const char *String)
 		"%f\t%f\t%f\t%f\t%f\t"
 		"%d\t"
 		"%d\t%d\t%d\t"
-		"%*s\t" // discard the game uuid
+		"%36s\t"
```
Comment (def-) [inline src/game/server/save.cpp:323]: does it always have this length? I mean might old saves not load anymore?

Comment (Zwelf) [reply src/game/server/save.cpp:323]: It just specifies the max length (excluding the null-terminator). Old saves should still load.
