### PR TITLE
Editor: better map settings input (autocomplete, validation)

### LINKED ISSUE #1406: Add checks for server settings in editor
Should check if a command can be used as a map setting and whether it's spelled correctly.
Could also check whether tune_zone/switch_open commands are used.

Wrongly used commands could be highlighted similar to how unused/wrongly embedded tilesets are marked.

Mapping for something that isn't DDNet and that added their own commands (e.g. KoG) would be problematic, but for DDNet this should be helpful.

### LINKED ISSUE #7124: Server setting improvement
This is something I suggested on DDNet's discord.
image

I also shared the idea to k2d222 here:
https://github.com/k2d222/twwe/issues/77

### PR DESCRIPTION
**Pull request by archimede67**
## Description

Closes #7124. Closes #1406.
This PR overhauls the map settings input in the editor. Previously, we could add invalid commands, we could have multiple times the same command with different argument values, etc. An improvement was suggested in #7124, as well as better checks requested in #1406. This PR aims to solve both of these issues while providing an easy-to-use solution that can improve the productivity of mappers.

~To make it work, all the map settings are compiled into a single file when compiling with a new python script `map_settings.py` (based on https://github.com/ddnet/ddnet-scripts/tree/master/client). This script is used to generate the files `map_settings.h` and `map_settings.cpp`, which contain the static data for the available map settings.~

There are two new files: `editor_server_settings.h` and `editor_server_settings.cpp` which contain the implementation and the rendering code for the server settings editor, this is a step forward of splitting editor code.

By default, only recognized map settings from ddnet are considered valid. However, there is a toggle next to the input line which allows or disallows unknown commands. I believe this can be useful when mapping for a modded server using ddnet client.

The input has colored arguments for valid ddnet command names:
- numeric values are in green (integer, float)
- string values are in cyan (string, rest of string)
- any error argument or invalid command is rendered in red

For validation purposes, I have added some parsing methods to `system.h` and `system.cpp` that have a success check.

~Finally, I fixed argument types being wrong for tune commands, as they used `i` but they are floats, so they now use `f`. I also removed the command `toggle_tune` from the map settings by removing `CFGFLAG_GAME` as it does not make sense to have it as a map setting.~ Edit: moved to a separate PR.

## Functionality

Here is a list of the main functionalities:
- Autocompletion of server settings names
- Autocompletion of some string arguments such as tunes and mapbugs
- Validation of each argument
- Colored input
- Error display
- Argument name display
- Works with undo/redo
- Automatically updates corresponding line in the list when trying to add a similar command
- Toggle unknown commands support
- `Ctrl+Space` can be used when the input is empty to show the list of available commands
- Navigate/autocomplete available options with `Tab`, `Shift+Tab`, up and down arrows
- `Ctrl+Click` on a setting in the list to change the selection only, not affecting the input

## Status

It works, but I opened this PR as draft for two things:
- I would like to get your opinions on it, maybe things to change or improve
- [x] ~I want to add validation of existing server settings when loading a map, and showing which settings are incorrect as well as an option to change or delete invalid settings from the map.~ Edit: Done, see https://github.com/ddnet/ddnet/pull/7687#issuecomment-1869636241.

## Some previews

Below are some screenshots of different settings and how it looks like.

- Valid setting, while the cursor is on the 2nd argument (`tuning`):
arg_list_and_colors

- Invalid value for an argument:
invalid_value

- Too many arguments for the setting:
too_many_args

- Unknown setting, with unknown settings disallowed:
disallow_unknown_setting

- Unknown setting, with unknown settings allowed:
allow_unknown_setting

- Available commands list:
suggestions

- Out of range error:
err_out_of_range

## Demo

https://github.com/ddnet/ddnet/assets/13364635/4aebdc0d-6d50-4a3e-a181-1d5299040811

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Woah, looks fancy!

File: src/game/server/gamecontext.cpp [hunk 1]
```diff
@@ -3486,11 +3486,11 @@ void CGameContext::OnConsoleInit()
...
 
-	Console()->Register("tune", "s[tuning] ?i[value]", CFGFLAG_SERVER | CFGFLAG_GAME, ConTuneParam, this, "Tune variable to value or show current value");
-	Console()->Register("toggle_tune", "s[tuning] i[value 1] i[value 2]", CFGFLAG_SERVER | CFGFLAG_GAME, ConToggleTuneParam, this, "Toggle tune variable");
+	Console()->Register("tune", "s[tuning] ?f[value]", CFGFLAG_SERVER | CFGFLAG_GAME, ConTuneParam, this, "Tune variable to value or show current value");
+	Console()->Register("toggle_tune", "s[tuning] f[value 1] f[value 2]", CFGFLAG_SERVER, ConToggleTuneParam, this, "Toggle tune variable");
 	Console()->Register("tune_reset", "?s[tuning]", CFGFLAG_SERVER, ConTuneReset, this, "Reset all or one tuning variable to default");
 	Console()->Register("tunes", "", CFGFLAG_SERVER, ConTunes, this, "List all tuning variables and their values");
-	Console()->Register("tune_zone", "i[zone] s[tuning] i[value]", CFGFLAG_SERVER | CFGFLAG_GAME, ConTuneZone, this, "Tune in zone a variable to value");
+	Console()->Register("tune_zone", "i[zone] s[tuning] f[value]", CFGFLAG_SERVER | CFGFLAG_GAME, ConTuneZone, this, "Tune in zone a variable to value");
```
Comment (Robyt3) [inline src/game/server/gamecontext.cpp:3493]: > Finally, I fixed argument types being wrong for tune commands, as they used `i` but they are floats, so they now use `f`. I also removed the command `toggle_tune` from the map settings by removing `CFGFLAG_GAME` as it does not make sense to have it as a map setting.

These changes and those in `gameclient.cpp` seem independent from the feature itself, so they would be a good candidate for a separate PR.

File: src/game/editor/editor_server_settings.cpp [hunk 2]
```diff
@@ -0,0 +1,1440 @@
...
+		Props.m_MaxWidth = Label.w;
+		Props.m_EllipsisAtEnd = true;
+		UI()->DoLabel(&Label, m_Map.m_vSettings[i].m_aCommand, 10.0f, TEXTALIGN_ML, Props);
+	}
+
+	const int NewSelected = s_ListBox.DoEnd();
+	if(s_CommandSelectedIndex != NewSelected || s_ListBox.WasItemSelected())
+	{
+		s_CommandSelectedIndex = NewSelected;
+		if(m_SettingsCommandInput.IsEmpty() || Input()->ModifierIsPressed()) // Allow ctrl+click to fill the input even if empty
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:246]: > `Ctrl+Click` on a setting in the list to load it into the input

What's the motivation for this? Feels very unintuitive if the editbox doesn't stay synchronized with the listbox selection.

File: src/game/editor/editor_server_settings.cpp [hunk 3]
```diff
@@ -0,0 +1,1440 @@
...
+		{
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:247]: The dropdown menu should be closed when you click on a listbox item or you can't see some items because the dropdown keeps opening.

File: src/game/editor/editor_server_settings.cpp [hunk 4]
```diff
@@ -0,0 +1,1440 @@
...
+		}
+		else if(pInfo->m_Type == IMapSetting::SETTING_COMMAND)
+		{
+			SMapSettingCommand *pCommand = (SMapSettingCommand *)pInfo;
+			str_format(aOutput, sizeof(aOutput), "%s %s", pCommand->m_pName, pCommand->m_pArgs);
+		}
+	}
+	else
+	{
+		str_format(aOutput, sizeof(aOutput), "%s", Match.m_pValue);
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:537]: No need for `str_format` here, also in some other places below

**Review by Robyt3 — CHANGES_REQUESTED** [review]

File: src/engine/client/text.cpp [hunk 5]
```diff
@@ -1755,9 +1755,9 @@ class CTextRender : public IEngineTextRender
 					if(ColorOption < (int)pCursor->m_vColorSplits.size())
 					{
 						STextColorSplit &Split = pCursor->m_vColorSplits.at(ColorOption);
-						if(PrevCharCount >= Split.m_CharIndex && PrevCharCount < Split.m_CharIndex + Split.m_Length)
+						if(PrevCharCount >= Split.m_CharIndex && (Split.m_Length == -1 || PrevCharCount < Split.m_CharIndex + Split.m_Length))
 							Color = Split.m_Color;
-						if(PrevCharCount >= (Split.m_CharIndex + Split.m_Length - 1))
+						if(Split.m_Length != -1 && PrevCharCount >= (Split.m_CharIndex + Split.m_Length - 1))
```
[the remark this answers is not in the document]
Comment (Robyt3) [reply src/engine/client/text.cpp:1760]: Hmm, seems like it could overflow then if we aren't careful about the order of operations.

File: src/game/editor/editor_server_settings.cpp (hunk 2 above)
Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp:246]: The motivation is that you can edit a command and then click on a command in the list that you might want to replace. Previously this would replace the current command, now to replace you ctrl+click to avoid having to retype everything in case you wanted to replace a command.
If it really feels unintuitive then I can just restore the old behavior

File: scripts/map_settings.py
[the remark this answers is not in the document]
Comment (archimede67) [reply scripts/map_settings.py:1]: I first tried to not use an extra python script but I realized like you said that we have map settings commands that are not available since they are not registered on the client. So I figured the best option would be to make a script to compile everything into one file, regardless of where they are registered.

I mainly made this script to future-proof the code in case more commands are added, to avoid having to hard-code them elsewhere.

Now I understand the issue with such a script, and if you think it is better to hard code them, then sure thing, I can do that.

File: src/engine/client/text.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (archimede67) [reply src/engine/client/text.cpp:1760]: I believe this can work yes, didn't think about it

File: src/game/client/lineinput.cpp [hunk 6]
```diff
@@ -389,7 +389,7 @@ bool CLineInput::ProcessInput(const IInput::CEvent &Event)
 	return m_WasChanged || m_WasCursorChanged || KeyHandled;
 }
 
-STextBoundingBox CLineInput::Render(const CUIRect *pRect, float FontSize, int Align, bool Changed, float LineWidth, float LineSpacing)
+STextBoundingBox CLineInput::Render(const CUIRect *pRect, float FontSize, int Align, bool Changed, float LineWidth, float LineSpacing, const std::vector<STextColorSplit> &vColorSplits)
```
[the remark this answers is not in the document]
Comment (archimede67) [reply src/game/client/lineinput.cpp:392]: How can I test this?

File: src/engine/client/text.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (archimede67) [reply src/engine/client/text.cpp:1760]: Oh, so do we keep `-1` ?

File: src/game/client/lineinput.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (archimede67) [reply src/game/client/lineinput.cpp:392]: Should be fixed now!

File: src/game/editor/editor_server_settings.cpp [hunk 7]
```diff
@@ -0,0 +1,1440 @@
...
+	// If we have a valid command, display the help in the tooltip
+	if(Context.CommandIsValid())
+		Context.GetCommandHelpText(m_aTooltip, sizeof(m_aTooltip));
+
+	CUIRect ToolBar = *pRect;
+	CUIRect Button;
+	ToolBar.VSplitRight(ToolBar.h, &ToolBar, &Button);
+
+	// Do the unknown command toggle button
+	if(DoButton_FontIcon(&Context.m_AllowUnknownCommands, FONT_ICON_BAN, !Context.m_AllowUnknownCommands, &Button, 0, "Disallow/allow unknown commands", IGraphics::CORNER_R))
```
[the remark this answers is not in the document]
Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp]: I used "question" icon, which looks good and fits better as you suggested

File: scripts/map_settings.py
[the remark this answers is not in the document]
Comment (archimede67) [reply scripts/map_settings.py:1]: I think if I need to use `IConfigManager`, then I would need to move the structs `SConfigVariable`, `SIntConfigVarialbe`, etc from `engine/shared/config.cpp` to `engine/shared/config.h` so that I can access them from the editor code.

File: src/engine/shared/config.h [hunk 8]
```diff
@@ -58,6 +59,361 @@ enum
 	CFGFLAG_INSENSITIVE = 1 << 12,
 };
 
+static void EscapeParam(char *pDst, const char *pSrc, int Size)
+{
+	str_escape(&pDst, pSrc, pDst + Size);
+}
+
+struct SConfigVariable
```
Comment (Robyt3) [inline src/engine/shared/config.h:67]: `config.h` shouldn't contain the implementation, so you don't need to include `system.h` here.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

File: src/game/editor/editor_server_settings.cpp (hunk 2 above)
Comment (Robyt3) [reply src/game/editor/editor_server_settings.cpp:271]: Maybe swap both actions so clicking is the same as before and Ctrl+clicking just changes the selection. Then this wouldn't change how mappers use the feature.

**Comment by archimede67** [comment]
I have added a new dialog that is shown after loading a map containing invalid settings.
The dialog displays a list in which you can fix the invalid settings, by either deleting or editing them.
It also displays duplicate settings in which case you can choose between one of them.
The dialog asks you to fix all the issues before you can continue editing the map. If you press "escape" or press the "cancel" button, the the map will "unload".

Here is a short demo:

https://github.com/ddnet/ddnet/assets/13364635/58b27a42-e8c3-4100-ae09-1acfb842bd94

And here is an example after loading the map "Paralyzed":
map_settings_error_example

File: src/game/editor/editor_actions.cpp [hunk 9]
```diff
@@ -1303,6 +1303,7 @@ void CEditorCommandAction::Undo()
 	}
 	case EType::EDIT:
 	{
+		printf("Restoring %s\n", m_PreviousCommand.c_str());
```
Comment (Robyt3) [inline src/game/editor/editor_actions.cpp:1306]: Remove debug message

File: src/game/editor/editor_ui.h [hunk 10]
```diff
@@ -0,0 +1,17 @@
...
+	bool m_Visible = false;
+	int m_Selected = -1;
+	CListBox m_ListBox;
+	bool m_ShortcutUsed = false;
+	bool m_DidBecomeVisible = false;
+	bool m_MousePressedInside = false;
+	bool m_ShouldHide = false;
+};
+
+#endif
```
Comment (Robyt3) [inline src/game/editor/editor_ui.h:17]: Newline

File: src/game/editor/editor_server_settings.cpp [hunk 11]
```diff
@@ -0,0 +1,2131 @@
...
+}
+
+void SValueLoader::LoadArgumentTuneValues(CArgumentValuesListBuilder &&ArgBuilder)
+{
+	// Iterate through available tunings add their name to the list
+	for(int i = 0; i < CTuningParams::Num(); i++)
+	{
+		ArgBuilder.Add(CTuningParams::Name(i));
+	}
+}
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:2131]: Newline

File: src/game/editor/editor_server_settings.cpp [hunk 12]
```diff
@@ -0,0 +1,2131 @@
...
+		// Check if all arguments are valid
+		const bool ArgumentsValid = std::all_of(m_vCurrentArgs.begin(), m_vCurrentArgs.end(), [](const SCurrentSettingArg &Arg) {
+			return !Arg.m_Error;
+		});
+
+		if(!ArgumentsValid)
+			return false;
+
+		// Check that we have the same number of arguments
+		const bool ArgCountValid = m_vCurrentArgs.size() == m_pBackend->m_ParsedCommandArgs.at(m_pCurrentSetting).size();
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:1954]: Unnecessary variable

File: src/game/editor/editor_server_settings.cpp [hunk 13]
```diff
@@ -0,0 +1,2131 @@
...
+		const char *pNameStart = pIterator;
+
+		while(*pIterator && *pIterator != ']')
+			pIterator++;
+
+		size_t Len = pIterator - pNameStart;
+		pIterator++; // Skip ']'
+
+		if(Len + 1 >= sizeof(SParsedMapSettingArg::m_aName))
+			dbg_msg("editor", "Warning: length of server setting name exceeds limit.");
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:1120]: Seems like a programming error if this happens so you should `dbg_assert` instead of continuing and likely performing out of bounds writes with the `str_copy` below.

File: src/game/editor/editor_server_settings.cpp [hunk 14]
```diff
@@ -0,0 +1,2131 @@
...
+		m_Dialog = DIALOG_NONE;
+	}
+
+	// Cancel - we load a new empty map
+	if(DoButton_Editor(&s_CancelButton, "Cancel", 0, &CancelButton, 0, nullptr) || (UI()->ConsumeHotkey(CUI::HOTKEY_ESCAPE)))
+	{
+		Reset();
+		m_aFileName[0] = 0;
+		m_Dialog = DIALOG_NONE;
+	}
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:995]: Position the buttons more like in the other popups, i.e. cancel on the left and confirm on the right, with spacing between them.

File: src/game/editor/editor_server_settings.cpp [hunk 15]
```diff
@@ -0,0 +1,2131 @@
...
+					SubSlot.HMargin(1.0f, &SubSlot);
+
+					if(!IsFixing)
+					{
+						// If not fixing, then display "Choose" and maybe "Fix" buttons.
+
+						CUIRect ChooseBtn;
+						SubSlot.VSplitRight(50.0f, &SubSlot, &ChooseBtn);
+						SubSlot.VSplitRight(5.0f, &SubSlot, nullptr);
+						if(DoButton_Editor(&Duplicate.m_Context.m_Chosen, "Choose", IsInvalid && !Duplicate.m_Context.m_Fixed ? -1 : Duplicate.m_Context.m_Chosen, &ChooseBtn, 0, "Override with this command"))
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:803]: Add a small `HMargin` to the choose buttons, same as the fix button.

File: src/game/editor/editor_server_settings.cpp [hunk 16]
```diff
@@ -0,0 +1,2131 @@
...
+{
+	auto &LoadedMapSettings = m_MapSettingsBackend.m_LoadedMapSettings;
+	auto &vSettingsInvalid = LoadedMapSettings.m_vSettingsInvalid;
+	auto &vSettingsValid = LoadedMapSettings.m_vSettingsValid;
+	auto &SettingsDuplicate = LoadedMapSettings.m_SettingsDuplicate;
+
+	UI()->MapScreen();
+	CUIRect Overlay = *UI()->Screen();
+
+	Overlay.Draw(ColorRGBA(0, 0, 0, 0.33f), 0, 0);
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:554]: `IGraphics::CORNER_NONE` and `0.0f`

File: src/game/editor/editor_server_settings.cpp [hunk 17]
```diff
@@ -0,0 +1,2131 @@
...
+		const float RowHeight = 18.0f;
+		static CScrollRegion s_ScrollRegion;
+		vec2 ScrollOffset(0.0f, 0.0f);
+		CScrollRegionParams ScrollParams;
+		ScrollParams.m_ScrollUnit = 120.0f;
+		s_ScrollRegion.Begin(&List, &ScrollOffset, &ScrollParams);
+		const float EndY = List.y + List.h;
+		List.y += ScrollOffset.y;
+
+		List.HSplitTop(20.0f, nullptr, &List);
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:599]: Is this space and the space at the bottom of the list necessary?

File: src/engine/textrender.h [hunk 18]
```diff
@@ -142,6 +142,9 @@ MAYBE_UNUSED static const char *FONT_ICON_DICE_SIX = "\xEF\x94\xA6";
 MAYBE_UNUSED static const char *FONT_ICON_LAYER_GROUP = "\xEF\x97\xBD";
 MAYBE_UNUSED static const char *FONT_ICON_UNDO = "\xEF\x8B\xAA";
 MAYBE_UNUSED static const char *FONT_ICON_REDO = "\xEF\x8B\xB9";
+
+MAYBE_UNUSED static const char *FONT_ICON_ARROWS_ROTATE = "\xEF\x80\xA1";
+MAYBE_UNUSED static const char *FONT_ICON_QUESTION = "\x3F";
```
Comment (Robyt3) [inline src/engine/textrender.h:147]: No need for encoding here, this is simply `"?"` (the constant is still a good idea, to be clear)

**Review by Robyt3 — CHANGES_REQUESTED** [review]

File: src/game/editor/editor_server_settings.cpp (hunk 17 above)
Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp:599]: Yeah, it is needed to display either the error for the very first line in the list (the error is displayed above the line, so if there is no space then it gets clipped and is basically invisible), or the possible values dropdown for the very last line in the list (if there is no space then the dropdown would be clipped and would be almost invisible as well).

File: src/game/editor/editor_server_settings.cpp (hunk 14 above)
Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp:995]: Like in the file browser dialog? Or can I just change the order with cancel being on the left instead, but keep the size of the buttons?
image

Comment (Robyt3) [reply src/game/editor/editor_server_settings.cpp:999]: Like in this popup I'd say:

button order layout

Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp:999]: This is how it looks like:
image

I'm not sure about it, do you think it looks better?

Comment (Robyt3) [reply src/game/editor/editor_server_settings.cpp:999]: Looks good to me.

**Comment by furo321** [comment]
Commands and settings can contain the `#` character to create comments. Here's an example of it being used on the map `Volleyball`

image

Or here on `Kobra 4 Solo` with it being its own line.

image

I also don't think you should force the user to fix the map settings, as the map may use non-ddnet specific commands like `Q-move` on KoG

image

**Comment by archimede67** [comment]
> Commands and settings can contain the `#` character to create comments. Here's an example of it being used on the map `Volleyball`
Ohh I did not even know this was a thing! Thanks for pointing it out, should be an easy fix.

> I also don't think you should force the user to fix the map settings, as the map may use non-ddnet specific commands like Q-move on KoG
These settings can be fixed using the "Fix" button and checking the "allow unknown commands" button next to the command input. I chose to not allow unknown settings when loading a map to show potential misspelled commands, for example `sv_taems` instead of `sv_teams`. I could allow unknown settings which would mark those settings as completely valid, but then we would not know if there is a misspelled setting somewhere.

**Comment by archimede67** [comment]
Also I'm not sure if we should allow empty map settings or not? I see it used on map `Kobra 4` to separate groups of settings

**Comment by archimede67** [comment]
@Robyt3 Do you have any more comments on this? ^^

File: src/game/editor/editor_server_settings.cpp [hunk 19]
```diff
@@ -0,0 +1,2209 @@
...
+		Background.x = x - PartMargin;
+		Background.y = pInputRect->y - pInputRect->h - 6.0f;
+		Background.w = TextRender()->TextWidth(FontSize, pStr) + 2 * PartMargin;
+		Background.h = pInputRect->h;
+		Background.Draw(ColorRGBA(0, 0, 0, 0.9f), IGraphics::CORNER_ALL, 3.0f);
+
+		CUIRect Label;
+		Background.VSplitLeft(PartMargin, nullptr, &Label);
+		TextRender()->TextColor(0.8f, 0.8f, 0.8f, 1.0f);
+		UI()->DoLabel(&Label, pStr, FontSize, TEXTALIGN_MIDDLE);
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:311]: `TEXTALIGN_MIDDLE` --> `TEXTALIGN_ML`

File: src/game/editor/editor_server_settings.cpp [hunk 20]
```diff
@@ -0,0 +1,2209 @@
...
+	// Render a dropdown tied to an edit box/line input
+	auto *pListBox = &pDropdown->m_ListBox;
+
+	pListBox->SetActive(m_Dialog == DIALOG_NONE && !UI()->IsPopupOpen() && pLineInput->IsActive());
+	pListBox->SetScrollbarWidth(15.0f);
+
+	const int NumEntries = vData.size();
+
+	// Setup the rect
+	static float s_Width = View.w;
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:470]: This should be part of `SEditBoxDropdownContext`. Otherwise each call to the `RenderEditBoxDropdown` function uses the same `static` variable, so you couldn't have multiple dropdowns at once like this.

File: src/game/editor/editor_server_settings.cpp [hunk 21]
```diff
@@ -0,0 +1,2209 @@
...
+		if(NewIndex != Selected)
+		{
+			UI()->SetActiveItem(pLineInput);
+			return NewIndex;
+		}
+	}
+	return -1;
+}
+
+void CEditor::RenderMapSettingsErrorDialog()
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:544]: There has to be a way to accept all unknown map settings in this dialog. Otherwise the user has to click on "Fix" and press enter for ever map setting every time they load a map that contains non-vanilla settings.

File: src/game/editor/editor_server_settings.cpp [hunk 22]
```diff
@@ -0,0 +1,2209 @@
...
+{
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:545]: Client crashes with seemingly random backtrace sometimes when loading any map after attempting to load another map that unknown map settings and cancelling the dialog.

**Review by Robyt3 — CHANGES_REQUESTED** [review]
Should also be tested more with ASAN/UBSAN.

**Comment by archimede67** [comment]
> Should also be tested more with ASAN/UBSAN.

Is there a guide on how to run ASAN/UBSAN on Windows?

**Comment by Robyt3** [comment]
> Is there a guide on how to run ASAN/UBSAN on Windows?

[Visual Studio seems to supports ASAN](https://learn.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-170). Otherwise you are likely out of luck. I use an Ubuntu VM for that.

File: src/game/editor/editor_server_settings.cpp (hunk 22 above)
Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp:544]: Are you able to reproduce this somehow? I've been trying what you said but couldn't get it to crash. What are the maps you tried ?

Comment (Robyt3) [reply src/game/editor/editor_server_settings.cpp:544]: I used this map [testing_server_settings.zip](https://github.com/ddnet/ddnet/files/13928681/testing_server_settings.zip) and other vanilla maps like dm1 and ctf5. The crash doesn't happen every time though. Eventually it happens when you keep loading maps without settings and maps where the server settings dialog is opened. For example I got the crash after loading two vanilla maps in a row after loading a map with unknown map settings.

Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp:544]: I see, and do you have any trace/logs of these crashes when they happened? I will try to reproduce, thanks!

Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp:544]: I tried your map and i got the crash instantly when loading it. I think the issue was something to do with trying to copy data to an argument while data length exceeded the max argument length which was 160. I changed the length to be 256 and inserted a dbg_assert just in case.

Could you try again if you are able to get a crash again?

Comment (Robyt3) [reply src/game/editor/editor_server_settings.cpp:544]: Seems to work with this map now, but it shouldn't crash with `dbg_assert` when you load maps with too long settings either. Maps can contain settings of arbitrary length. It seems fine to me to simply truncate the settings to 256 bytes, the same as it was already done previously.

Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp:544]: Alright I changed it so there is no more `dbg_assert` and only copies a maximum if 256 bytes for each argument to be safe.

**Comment by archimede67** [comment]
I ran it with ASAN/UBSAN and didn't find anything related to my changes after the latest fixes. I tried loading maps with unknown settings, loading valid maps, loading empty map, fixing settings in the dialog, adding new settings on a fresh map, etc. Nothing was reported, so I think it should all be fine now.

**Comment by Robyt3** [comment]
Thanks, I'll review this again in a few days. We should wait for 18.0 to be released before merging this to avoid conflicts.

File: src/game/editor/editor_server_settings.cpp [hunk 23]
```diff
@@ -0,0 +1,2235 @@
...
+		int m_Index;
+		std::vector<SArgument> m_vArgs;
+	};
+
+	// For now we split each map setting corresponding to the setting we want to add by spaces
+	auto &&SplitSetting = [](const char *pStr) {
+		std::vector<SArgument> vaArgs;
+		const char *pIt = pStr;
+		char aBuffer[128];
+		while((pIt = str_next_token(pIt, " ", aBuffer, 128)))
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:1892]: `128` -> `sizeof(aBuffer)`

File: src/game/editor/editor_server_settings.cpp [hunk 24]
```diff
@@ -0,0 +1,2235 @@
...
+
+	if(m_CommentOffset == 0)
+		return;
+
+	// First case: argument index under cursor is -1 => we're on the command/setting name
+	if(m_CursorArgIndex == -1)
+	{
+		// Use a substring from the start of the input to the cursor offset
+		char aSubString[128];
+		str_copy(aSubString, m_aCommand, minimum((int)m_LastCursorOffset + 1, 128));
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:1681]: `128` -> `sizeof(aSubString)`

File: src/game/editor/editor_server_settings.cpp [hunk 25]
```diff
@@ -0,0 +1,2235 @@
...
+
+	auto &&FixAllUnknown = [&] {
+		// Mark unknown settings as fixed
+		for(auto &InvalidSetting : vSettingsInvalid)
+			if(!InvalidSetting.m_Context.m_Fixed && !InvalidSetting.m_Context.m_Deleted && !(InvalidSetting.m_Type & SInvalidSetting::TYPE_DUPLICATE) && InvalidSetting.m_Unknown)
+				InvalidSetting.m_Context.m_Fixed = true;
+	};
+
+	// Fix all unknown settings
+	if(DoButton_Editor(&s_FixAllButton, "Fix all unknown settings", CanFixAllUnknown ? 0 : -1, &FixAllUnknownButton, 0, nullptr))
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:998]: `Allow` instead of `Fix` fit better here. otherwise it make it seem like this attempts to fix/change the commands.

File: src/game/editor/editor_server_settings.cpp [hunk 26]
```diff
@@ -0,0 +1,2235 @@
...
+						//      sv_deepfly 5  <- This is invalid and duplicate. We can only fix it by writing "sv_deepfly 0" or "sv_deepfly 1".
+						//                       If we write any other setting, like "sv_hit 1", it won't work as it does not match "sv_deepfly".
+						// To do that, we use the context and we check for collision with the current map setting
+						ECollisionCheckResult Res = ECollisionCheckResult::ERROR;
+						s_Context.CheckCollision({m_Map.m_vSettings[i]}, Res);
+						bool Valid = s_Context.Valid() && Res == ECollisionCheckResult::REPLACE;
+
+						if(DoButton_Editor(&s_Ok, "Done", Valid ? 0 : -1, &OkBtn, 0, "Confirm edition of this command") || (s_Input.IsActive() && Valid && UI()->ConsumeHotkey(CUI::HOTKEY_ENTER)))
+						{
+							if(Valid) // Just to make sure
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:866]: This check is redundant

File: src/game/editor/editor_server_settings.cpp [hunk 27]
```diff
@@ -0,0 +1,2235 @@
...
+						}
+
+						// "Done" button only enabled if the fixed setting is valid
+						// For that we use a local CContext s_Context and use it to check
+						// that the setting is valid and that it is not a duplicate
+						ECollisionCheckResult Res = ECollisionCheckResult::ERROR;
+						s_Context.CheckCollision(vSettingsValid, Res);
+						bool Valid = s_Context.Valid() && Res == ECollisionCheckResult::ADD;
+
+						if(DoButton_Editor(&s_Ok, "Done", Valid ? 0 : -1, &OkBtn, 0, "Confirm edition of this command") || (s_Input.IsActive() && Valid && UI()->ConsumeHotkey(CUI::HOTKEY_ENTER)))
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:681]: `edition` -> `editing`

File: src/game/editor/editor_server_settings.cpp [hunk 28]
```diff
@@ -0,0 +1,2235 @@
...
+						// For example:
+						//   sv_deepfly 0
+						//      sv_deepfly 5  <- This is invalid and duplicate. We can only fix it by writing "sv_deepfly 0" or "sv_deepfly 1".
+						//                       If we write any other setting, like "sv_hit 1", it won't work as it does not match "sv_deepfly".
+						// To do that, we use the context and we check for collision with the current map setting
+						ECollisionCheckResult Res = ECollisionCheckResult::ERROR;
+						s_Context.CheckCollision({m_Map.m_vSettings[i]}, Res);
+						bool Valid = s_Context.Valid() && Res == ECollisionCheckResult::REPLACE;
+
+						if(DoButton_Editor(&s_Ok, "Done", Valid ? 0 : -1, &OkBtn, 0, "Confirm edition of this command") || (s_Input.IsActive() && Valid && UI()->ConsumeHotkey(CUI::HOTKEY_ENTER)))
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:864]: `edition` -> `editing`

File: src/game/editor/editor_server_settings.cpp [hunk 29]
```diff
@@ -0,0 +1,2235 @@
...
+		}
+	}
+	else
+	{
+		Context.m_DropdownContext.m_ListBox.SetActive(false);
+	}
+}
+
+template<typename T>
+int CEditor::DoEditBoxDropdown(SEditBoxDropdownContext *pDropdown, CLineInput *pLineInput, const CUIRect *pEditBoxRect, int x, float MaxHeight, bool AutoWidth, const std::vector<T> &vData, const FDropdownRenderCallback<T> &fnMatchCallback)
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:398]: The `pLineInput` argument seems redundant, it should always be the lineinput of the dropdown context.

File: src/game/editor/editor_server_settings.cpp [hunk 30]
```diff
@@ -0,0 +1,2235 @@
...
+		pDropdown->m_Visible = false;
+		pDropdown->m_ListBox.SetActive(false);
+		pDropdown->m_Selected = -1;
+	}
+
+	return -1;
+}
+
+template<typename T>
+int CEditor::RenderEditBoxDropdown(SEditBoxDropdownContext *pDropdown, CUIRect View, CLineInput *pLineInput, int x, float MaxHeight, bool AutoWidth, const std::vector<T> &vData, const FDropdownRenderCallback<T> &fnMatchCallback)
```
Comment (Robyt3) [inline src/game/editor/editor_server_settings.cpp:459]: `pLineInput` argument redundant

**Review by Robyt3 — CHANGES_REQUESTED** [review]

File: src/game/editor/editor_server_settings.cpp (hunk 29 above)
Comment (archimede67) [reply src/game/editor/editor_server_settings.cpp:398]: There is no lineinput in the dropdown context, the lineinput is in the backend context `CContext`.

**Review by Robyt3 — APPROVED** [review]
LGTM, please squash the commits.

**Comment by archimede67** [comment]
@Robyt3 Is this good for you? I'd like to keep the input and the dialog in separate commits

**Review by Robyt3 — APPROVED** [review]
Thanks!
