### PR TITLE
Fix #1031

### LINKED ISSUE #1031: Pressing "home" or "end" in settings -> player -> text edit fields
I think it's just an unintended UI/UX behaviour--to reproduce:
1) go to settings -> player
2) click on text field for either name or clan
3) press home/end
And you'll see that the flag selection changes instead of the text cursor moving to the beginning/end of the text edit field.

### PR DESCRIPTION
**Pull request by Learath2**
Not sure if this is the best way to do this though :D

### CODE REVIEW

File: src/game/client/components/menus_demo.cpp [hunk 1]
```diff
@@ -591,8 +593,10 @@ CMenus::CListboxItem CMenus::UiDoListboxNextItem(const void *pId, bool Selected,
 
 	CListboxItem Item = UiDoListboxNextRow();
 
-	if(Item.m_Visible && UI()->DoButtonLogic(pId, "", gs_ListBoxSelectedIndex == gs_ListBoxItemIndex, &Item.m_HitRect))
+	if(Item.m_Visible && UI()->DoButtonLogic(pId, "", gs_ListBoxSelectedIndex == gs_ListBoxItemIndex, &Item.m_HitRect)){
```
Comment (heinrich5991) [inline src/game/client/components/menus_demo.cpp]: Style.

Comment (Learath2) [reply src/game/client/components/menus_demo.cpp]: Habit sry
