### PR TITLE
Fix utf8 handling in str_truncate (fixes #2533)

### LINKED ISSUE #2533: Map name cut off inside of a utf8 character
2020-08-02-125842_1920x1080_scrot
I looks like an utf8 character was cut off. Note that it is the last letter of the map name.
Map name: [Uzmutulunculunbé](https://ddnet.tw/maps/Uzmutulunculunb-233-)

Happens in the score menu that opens when you press tab.

### PR DESCRIPTION
**Pull request by def-**
and rename to str_utf8_truncate since it's only used for utf8 strings

### CODE REVIEW

File: src/test/str.cpp [hunk 1]
```diff
@@ -188,14 +188,16 @@ TEST(Str, StrFormat)
...
+	str_utf8_truncate(aBuf, 3, foo, 1);
 	EXPECT_STREQ(aBuf, "F");
-	str_truncate(aBuf, 3, foo, 2);
+	str_utf8_truncate(aBuf, 3, foo, 2);
 	EXPECT_STREQ(aBuf, "Fo");
-	str_truncate(aBuf, 3, foo, 3);
+	str_utf8_truncate(aBuf, 3, foo, 3);
 	EXPECT_STREQ(aBuf, "Fo");
-	str_truncate(aBuf, sizeof(aBuf), foo, 6);
+	str_utf8_truncate(aBuf, sizeof(aBuf), foo, 6);
```
Comment (Zwelf) [inline src/test/str.cpp:199]: Maybe test the error case instead e.g.:
`str_utf8_truncate(aBuf, sizeof(aBuf), foo, 7);`

Comment (def-) [reply src/test/str.cpp:199]: Oops, fixed. I remembered I wanted to count the codepoints, not bytes anyway.

File: src/base/system.c [hunk 2]
```diff
@@ -2319,10 +2319,12 @@ void str_copy(char *dst, const char *src, int dst_size)
 	dst[dst_size-1] = 0; /* assure null termination */
 }
 
-void str_truncate(char *dst, int dst_size, const char *src, int truncation_len)
+void str_utf8_truncate(char *dst, int dst_size, const char *src, int truncation_len)
 {
-	int size = truncation_len >= dst_size ? dst_size : truncation_len + 1;
-	str_copy(dst, src, size);
+	int size = -1;
+	for(int cursor = 0, pos = 0; pos <= truncation_len && cursor < dst_size && size != cursor; cursor = str_utf8_forward(src, cursor), pos++)
```
Comment (Zwelf) [inline src/base/system.c:2325]: Shouldn't it be `cursor + 1 < dst_size` instead of `cursor < dst_size` since the destination includes the null-character, which could be written out of bounds in `str_copy`?

Comment (def-) [reply src/base/system.c:2325]: I added a test to make sure it works fine.

Comment (Zwelf) [reply src/base/system.c:2325]: Ah true, it works. Thanks for you fast responses.
