### PR TITLE
Fix hook coll on vanilla 0.7 servers

### LINKED ISSUE #8742: 0.7 using +showhookcoll on vanilla servers prevents the tee from moving
holding +showhookcoll bind key makes the player unable to move/shoot/hook/change weapons and hook line itself doesnt even show up

### PR DESCRIPTION
**Pull request by ChillerDragon**
Thanks to @fokkonaut for this F-Client commit

https://github.com/fokkonaut/F-Client/commit/8ecd8c7f0ab4b41f16d165bc5ec9b9e87578012c

Closed #8742

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/components/controls.cpp [hunk 1]
```diff
@@ -191,7 +191,7 @@ int CControls::SnapInput(int *pData)
 	if(m_pClient->m_Scoreboard.Active())
 		m_aInputData[g_Config.m_ClDummy].m_PlayerFlags |= PLAYERFLAG_SCOREBOARD;
 
-	if(m_pClient->m_Controls.m_aShowHookColl[g_Config.m_ClDummy])
+	if(m_pClient->m_Controls.m_aShowHookColl[g_Config.m_ClDummy] && (!Client()->IsSixup() || Client()->ServerCapAnyPlayerFlag()))
```
Comment (heinrich5991) [inline src/game/client/components/controls.cpp:194]:
```suggestion
	if(m_pClient->m_Controls.m_aShowHookColl[g_Config.m_ClDummy] && Client()->ServerCapAnyPlayerFlag())
```
Could you instead change the default value of `m_AnyPlayerFlag` to `!Sixup` (as a new parameter)?

https://github.com/ddnet/ddnet/blob/aaf69542b62b82605e4f691c95cbfe46eb6298a6/src/engine/client/client.cpp#L1404

**Review by heinrich5991 — COMMENTED** [review]
Does this still correctly deny showing hook collision lines on vanilla servers?

**Comment by heinrich5991** [comment]
> > Does this still correctly deny showing hook collision lines on vanilla servers?
> 
> "still"? When was that forbidden? As far as I know did the ddnet client always show hook coll on vanilla 0.6 servers.

Interesting. Seems like I was wrong about this.

**Review by heinrich5991 — APPROVED** [review]
Thanks.
