### PR TITLE
penalty tiles can be used to get a time of 00:00:01, this is fixed by letting the tees die, before that happens

### LINKED ISSUE #5170: m_StartTime can underflow into positive
https://github.com/C0D3D3V/ddnet/blob/8b31dbb108b8f2fb8f127bfb52f0b3fcc1f13a30/src/game/server/entities/character.cpp#L1842

reported by Hav on discord

### PR DESCRIPTION
**Pull request by C0D3D3V**
Also map gets reloaded if the server tick overflows. We could add a warning, that the server reloads soon, or save all players and load them after map reload. But I think that is such a rare event, we can just reload the map without these nice things.

fixes #5170

we should check the following maps for cheated times:
- just every fly
- puzzle partners
- time shop

## Checklist

- [x] Tested the change ingame See https://youtu.be/lQPU60XN8Nk
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/server/server.cpp [hunk 1]
```diff
@@ -2793,6 +2793,11 @@ int CServer::Run()
 
 				m_CurrentGameTick++;
```
Comment (Robyt3) [inline src/engine/server/server.cpp:2794]: The overflow that occurs here is already undefined behavior, so the check below may not work as intended. The loop also continues with the undefined tick value which should be avoided.

My suggestion: change the `if(m_MapReload)` on line 2682 to `if(m_MapReload || m_CurrentGameTick == std::numeric_limits<int>::max()` and remove the `if(m_CurrentGameTick < 0) { ... }` below.

Comment (C0D3D3V) [reply src/engine/server/server.cpp:2794]: the problem is, that it could be already overflown...
`m_CurrentGameTick++;` is in a loop, that can be triggered more then once

Comment (C0D3D3V) [reply src/engine/server/server.cpp:2794]: we could also check for some pseudo limit, a little below, int max, or I make this check for int max in this loop

Comment (C0D3D3V) [reply src/engine/server/server.cpp:2794]: @Robyt3 please review my new version

Comment (Robyt3) [reply src/engine/server/server.cpp:2794]: > please review my new version

I think it can still cause an overflow later at `m_CurrentGameTick + 1`. Vanilla just uses a value "a little below", i.e. `if(m_MapReload || m_CurrentGameTick >= 0x6FFFFFFF)`. 😅

> windows build does not like your function https://stackoverflow.com/a/27443191

The other answer suggests adding a define `NOMINMAX` to our build so windows doesn't add `min` and `max` macros. Might also be a good idea since we don't use those anyway, though it's fine with me for this PR.

**Comment by Chairn** [comment]
Other map i can think of

- Care for your time (solo)

File: src/engine/server/server.cpp [hunk 2]
```diff
@@ -2793,6 +2793,12 @@ int CServer::Run()
...
 				NewTicks++;
+				if(m_CurrentGameTick == (std::numeric_limits<int>::max)())
```
Comment (Chairn) [inline src/engine/server/server.cpp:2796]: Can you change `int` to `m_CurrentGameTick`? This will prevent problem if we ever change the type tick variables.

File: src/engine/server/server.cpp (hunk 1 above)
Comment (C0D3D3V) [reply src/engine/server/server.cpp:2794]: > I think it can still cause an overflow later at m_CurrentGameTick + 1

should I subtract one from (std::numeric_limits<int>::max)()?

**Comment by C0D3D3V** [comment]
> Care for your time (solo)
It only has time add of 6 seconds ... it is not really possible with that small amount to get the underflow

here a full list of all maps... but I already mentioned the imported maps
[maps_with_time.txt](https://github.com/ddnet/ddnet/files/8799526/maps_with_time.txt)

**Comment by Chairn** [comment]
brutal/maps/Puzzle Partners.map
fun/maps/Avoid.map
fun/maps/Bullseye.map
fun/maps/TeeInvader.map
fun/maps/Time Calculator.map
moderate/maps/Just Every Fly.map
moderate/maps/Time Shop.map
novice/maps/Tutorial.map
solo/maps/Care for your Time.map
solo/maps/Flappy Bird.map
solo/maps/Weird Cave.map

File: src/engine/server/server.cpp (hunk 2 above)
Comment (Chairn) [reply src/engine/server/server.cpp:2796]: `std::decltype(m_CurrentGameTick)` i think

File: src/engine/server/server.cpp (hunk 1 above)
Comment (Robyt3) [reply src/engine/server/server.cpp:2794]: > should I subtract one from (std::numeric_limits::max)()?

That would be enough to make the engine code overflow-proof, as it only contains expressions like `tick +1`.

But the game code contains a lot of `tick + speed * seconds` expressions that could still overflow, so the safety margin probably has to be increased for some of those.

Some overflows can be avoided by reordering the operations or using a larger datatype:

https://github.com/ddnet/ddnet/blob/cfdb97a42287493bbbfdbb9a1fe8afe42ea3fe72/src/game/server/ddracecommands.cpp#L369

But others can only be avoided by increasing the safety margin, as the overflow would otherwise occur for a different variable:

https://github.com/ddnet/ddnet/blob/cfdb97a42287493bbbfdbb9a1fe8afe42ea3fe72/src/game/server/ddracecommands.cpp#L408

Comment (C0D3D3V) [reply src/engine/server/server.cpp:2794]: the vanilla limit is about 1879048191/50/60/60/24 = ~434.96 days 
instead of int max 2147483647/50/60/60/24 = ~497.10 days 
I would be fine with the vanilla limit

Comment (C0D3D3V) [reply src/engine/server/server.cpp:2794]: @Robyt3 do you agree that i use the pseudo limit of teeworlds or do you want a "nicer" solution?

Comment (Robyt3) [reply src/engine/server/server.cpp:2794]: I'd agree with the more simple vanilla solution. What about you, @def- ?

**Comment by def-** [comment]
> Also map gets reloaded if the server tick overflows.

When is this?
