### PR TITLE
fix 4781 and refactor of the client id for server demos

### LINKED ISSUE #4781: Server crashes (with ASAN) when recording a server demo
Use `record` in the rcon and try playing a map, in particular with a dummy. The following errors occur with ASAN/UBSAN:

```
/src/engine/server/server.h:465:63: runtime error: index -1 out of bounds for type 'CClient [64]'
    #0 0x55e948e5b3d4 in CServer::IsSixup(int) const (/build-asan/DDNet-Server+0xbfb3d4)
    #1 0x55e9491373be in IGameController::Snap(int) /src/game/server/gamecontroller.cpp:603
    #2 0x55e9490e5352 in CGameContext::OnSnap(int) /src/game/server/gamecontext.cpp:3639
    #3 0x55e948ddaf37 in CServer::DoSnapshot() /src/engine/server/server.cpp:856
    #4 0x55e948e21e59 in CServer::Run() /src/engine/server/server.cpp:2664
    #5 0x55e948e50b19 in main /src/engine/server/server.cpp:3732
    #6 0x7f831168e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #7 0x55e948d99e5d in _start (/build-asan/DDNet-Server+0xb39e5d)
```

```
/src/game/server/gamecontext.h:471:52: runtime error: shift exponent -1 is negative
    #0 0x55e948fdfced in CmaskOne(int) /src/game/server/gamecontext.h:471
    #1 0x55e948fdfd3e in CmaskIsSet(long, int) /src/game/server/gamecontext.h:474
    #2 0x55e94901a1d3 in CProjectile::Snap(int) /src/game/server/entities/projectile.cpp:338
    #3 0x55e949154d1a in CGameWorld::Snap(int) /src/game/server/gameworld.cpp:124
    #4 0x55e9490e5805 in CGameContext::OnSnap(int) /src/game/server/gamecontext.cpp:3650
    #5 0x55e948ddaf37 in CServer::DoSnapshot() /src/engine/server/server.cpp:856
    #6 0x55e948e21e59 in CServer::Run() /src/engine/server/server.cpp:2664
    #7 0x55e948e50b19 in main /src/engine/server/server.cpp:3732
    #8 0x7f831168e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #9 0x55e948d99e5d in _start (/build-asan/DDNet-Server+0xb39e5d)
```

When I hooked a dummy, the server crashed with `Illegal instruction (core dumped)` and no further log.

When the server doesn't crash, watching the resulting demo is very glitchy. Should be further investigated with ASAN whether that will be fixed on the server side or if client fixes are needed.

For the server, a server demo means that the `SnappingClient` will be `-1` when creating the snapshot. For the client, a server demo will have no local client, i.e. `LocalClientID` being -1.

### PR DESCRIPTION
**Pull request by C0D3D3V**
#Fixes #4781

I took the opportunity and directly refactored the code a bit, to be exact I replaced the -1 with the enum `SERVER_DEMO_CLIENT`, I can also change the identifier if we want to call it something else. Further I normalized the corresponding `>= 0` conditions to `!= SERVER_DEMO_CLIENT`.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
> [~] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

Done

File: src/engine/server/server.h [hunk 1]
```diff
@@ -462,7 +462,7 @@ class CServer : public IServer
 	bool ErrorShutdown() const { return m_aErrorShutdownReason[0] != 0; }
 	void SetErrorShutdown(const char *pReason);
 
-	bool IsSixup(int ClientID) const { return m_aClients[ClientID].m_Sixup; }
+	bool IsSixup(int ClientID) const { return ClientID > -1 && m_aClients[ClientID].m_Sixup; }
```
Comment (def-) [inline src/engine/server/server.h:465]: SERVER_DEMO_CLIENT

File: src/engine/server.h [hunk 2]
```diff
@@ -150,13 +157,19 @@ class IServer : public IInterface
...
+	}
+
 	bool Translate(int &Target, int Client)
 	{
 		if(IsSixup(Client))
 			return true;
-		CClientInfo Info;
-		GetClientInfo(Client, &Info);
-		if(Info.m_DDNetVersion >= VERSION_DDNET_OLD)
+		int ClientVersion = Client > SERVER_DEMO_CLIENT ? GetClientVersion(Client) : CLIENT_VERSIONNR;
```
Comment (def-) [inline src/engine/server.h:171]: Maybe Client != SERVER_DEMO_CLIENT in case we want to change the value for some reason.

File: src/game/server/entities/character.cpp [hunk 3]
```diff
@@ -1153,7 +1153,7 @@ void CCharacter::SnapCharacter(int SnappingClient, int ID)
 
 bool CCharacter::CanSnapCharacter(int SnappingClient)
 {
-	if(SnappingClient < 0)
+	if(SnappingClient == SERVER_DEMO_CLIENT)
```
Comment (def-) [inline src/game/server/entities/character.cpp:1156]: This is a slight change in behavior. Are other SnappingClients < 0 possible? Then we'd crash here.

File: src/engine/server.h (hunk 2 above)
Comment (C0D3D3V) [reply src/engine/server.h]: I have adjusted all conditions accordingly to equality or inequality tests.

**Comment by def-** [comment]
bors r+
Thanks
