### PR TITLE
Fix game freezing up on duplicate snapshot

### LINKED ISSUE #5657: Game freezing up (utilising 100% cpu) if a duplicate snapshot is received
If a duplicate snapshot is received (for the same tick), end up with the same snapshot as both Cur and Prev. This results in GameInfraTick returning "inf" and results in "NaN" downstream in a few places, getting the CollLine logic stuck.

Some debug info (tcpdump, gdb, perf): https://gist.github.com/Fireball-Teeworlds/ad0016d2551a2e4d4cb5691023493856

Apparently this doesn't really happen in the wild, unless you have a buggy network stack. In which case it happens frequently enough to pinpoint the issue :D

### PR DESCRIPTION
**Pull request by Fireball-Teeworlds**
If a duplicate snapshot is received (for the same tick), we add both to the SnapshotStorage and end up with the same snapshot as both Cur and Prev. This results in GameInfraTick returning "inf" and results in "NaN" downstream in a few places, getting the CollLine logic stuck.

Some debug info (tcpdump, gdb, perf): https://gist.github.com/Fireball-Teeworlds/ad0016d2551a2e4d4cb5691023493856

Apparently this doesn't really happen in the wild, unless you have a buggy network stack. In which case it happens frequently enough to pinpoint the issue :D

 (fixes #5657)

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [X] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/client/client.cpp [hunk 1]
```diff
@@ -2125,8 +2127,6 @@ void CClient::ProcessServerPacket(CNetChunk *pPacket, int Conn, bool Dummy)
 					// apply snapshot, cycle pointers
 					m_aReceivedSnapshots[Conn]++;
 
-					m_aCurrentRecvTick[Conn] = GameTick;
-
```
Comment (Fireball-Teeworlds) [inline src/engine/client/client.cpp:2129]: We already check this above (see `if (GameTick != m_aCurrentRecvTick[Conn]`) and set them to be equal if they aren't already.

**Comment by Fireball-Teeworlds** [comment]
It's probably not worth it to add HW workarounds to DDNet in general, but this one might be simple enough and can also protect against malicious servers sending bad data.

**Comment by def-** [comment]
I see two ways to solve this. We could dbg_assert and crash if some tick is received again or at least print a dbg message to indicate a warning. I‘d prefer the latter.

**Comment by Fireball-Teeworlds** [comment]
The problem is that the game freezes up on the duplicate tick.

re: dbg message - do you mean printing a warning without skipping the tick? It will make it much easier to debug this issue if someone encounters it again. Although if we write a code to detect a duplicate snapshot, why not also skip it?

(The code is a bit complicated here because it is in fact designed to receive multiple snapshot packets for the same tick, as long as they are multiple parts of the same too-big-for-a-single-packet snapshot. But it's not supposed to call m_aSnapshotStorage.Add() on more than one reassembled snapshot)

**Comment by def-** [comment]
hardware

**Comment by def-** [comment]
in that case can merge as is
bors r+
