### PR TITLE
Fix a couple of problems with the demoviewer.

### LINKED ISSUE #607: Speed change problem in demo viewer with mousewheeldown
(Is 1.5x implemented? I think the text needs to be fixed in the demo viewer, because it still shows 2x. So right now, I think it shows the text "2x" for both 1.5x speed and 2x speed.)

When speeding down with mousewheeldown, it speeds down twice.

### PR DESCRIPTION
**Pull request by Learath2**
The error of `0.01f` is arbitrarily chosen, should be fine for this case.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Can you describe the problem and what this does to fix it?

File: src/game/client/components/menus_demo.cpp [hunk 1]
```diff
@@ -373,8 +374,10 @@ void CMenus::RenderDemoPlayer(CUIRect MainView)
 	// speed meter
 	ButtonBar.VSplitLeft(Margins*3, 0, &ButtonBar);
 	char aBuffer[64];
-	if(pInfo->m_Speed >= 1.0f)
+	if(fabs(pInfo->m_Speed - 1.0f) <= 0.01f)
```
Comment (Henningstone) [inline src/game/client/components/menus_demo.cpp]: I would have just changed this if statement to `if(pInfo->m_Speed >= 1.0f && pInfo->m_Speed != 1.5f)`. I think hardcoding this one should be ok, since adding new demo speeds is nothing that happens every day. Like that, you could save on this messing around with float stuff. I don't like the magic `0.01f`, either...

File: src/game/client/components/menus_demo.cpp [hunk 2]
```diff
@@ -373,8 +374,10 @@ void CMenus::RenderDemoPlayer(CUIRect MainView)
...
 		str_format(aBuffer, sizeof(aBuffer), "×%.0f", pInfo->m_Speed);
+	else if(pInfo->m_Speed >= 1.01f)
```
Comment (Henningstone) [inline src/game/client/components/menus_demo.cpp]: this would become `else if(pInfo->m_Speed == 1.5f)`. Seems more reasonable to me than `1.01f `

**Comment by Henningstone** [comment]
@heinrich5991 it fixes the problems described [here](https://github.com/ddnet/ddnet/issues/607#issuecomment-288455559).

File: src/game/client/components/menus_demo.cpp (hunk 2 above)
Comment (Learath2) [inline src/game/client/components/menus_demo.cpp]: == 1.5f doesn't do what you think it does. You cant really compare floats for equality.

File: src/game/client/components/menus_demo.cpp (hunk 1 above)
Comment (Learath2) [inline src/game/client/components/menus_demo.cpp]: != wouldn't work either.

**Comment by Learath2** [comment]
Looks better like this IMHO. Feel free to merge just the first commit in case you want the old behavior.

File: src/game/client/components/menus_demo.cpp (hunk 1 above)
Comment (Henningstone) [inline src/game/client/components/menus_demo.cpp]: Well I tried it and it worked, but your solution now is better :)

**Comment by heinrich5991** [comment]
I like this better. Thanks.
