### PR TITLE
Fixed memory leak after gametype change

### LINKED ISSUE #636: memory leak with entities
Every time you switch between gamemodes while using entities, memory is being leaked as the image for the entities is reloaded every time you go on a different gametype, but never unloaded. Look at the code, you'll immediately see what I mean:

https://github.com/ddnet/ddnet/blob/master/src/game/client/components/mapimages.cpp#L112

### PR DESCRIPTION
**Pull request by necropotame**

### CODE REVIEW

File: src/game/client/components/mapimages.cpp [hunk 1]
```diff
@@ -109,6 +109,9 @@ int CMapImages::GetEntities()
 
 		char path[64];
 		str_format(path, sizeof(path), "editor/entities_clear/%s.png", file);
+		
+		if(m_EntitiesTextures >= 0)
```
Comment (def-) [inline src/game/client/components/mapimages.cpp]: I would assume 0 is a null pointer?

Comment (necropotame) [inline src/game/client/components/mapimages.cpp]: Maybe I'm wrong, but m_EntitiesTextures is an integer that represents a texture ID. TextureIDs are valid in the range [0, MAX_TEXTURES[, so I test if the texture exists by this comparison.
