### PR TITLE
Fix rescue resets switches

### LINKED ISSUE #4314: Rescue reset doors and draggers
When using /practice, if you use /r it will reset doors and draggers (and i guess, also shooters but didnt test)
https://discord.com/channels/252358080522747904/757720336274948198/906551570492166154

https://user-images.githubusercontent.com/10178629/140613355-af57d4f2-a26a-4602-b3c7-e815d70515ab.mp4

### PR DESCRIPTION
**Pull request by Pioooooo**
Fixes #4314. Reference #4103

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/server/entities/character.cpp [hunk 1]
```diff
@@ -2481,7 +2481,7 @@ void CCharacter::Rescue()
 
 		m_LastRescue = Server()->Tick();
 		int StartTime = m_StartTime;
-		m_RescueTee[GetPlayer()->m_RescueMode].Load(this, Team());
+		m_RescueTee[GetPlayer()->m_RescueMode].Load(this, Team(), true);
```
Comment (Robyt3) [inline src/game/server/entities/character.cpp]: The argument is named `IsSwap` but this doesn't look like a swap. If this works, then the argument should be renamed to be more descriptive.

File: src/game/server/save.h [hunk 2]
```diff
@@ -38,7 +39,7 @@ class CSaveTee
 	CSaveTee();
 	~CSaveTee() = default;
 	void Save(CCharacter *pchr, bool AddPenalty = true);
-	bool Load(CCharacter *pchr, int Team, bool IsSwap = false);
+	bool Load(CCharacter *pchr, bool LoadTeam = false, int Team = INVALID_TEAM);
```
Comment (Robyt3) [inline src/game/server/save.h]: Use an `std::optional<int> Team` instead of separate `bool` and `int` and remove the constant `INVALID_TEAM` again.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

**Review by Robyt3 — APPROVED** [review]

**Comment by ChillerDragon** [comment]
Seems gameplay relevant. @Zwelf teehistorian minor version bump?

**Comment by Zwelf** [comment]
If this only affects practice mode (or /r command) then no teehistorian minor bump necessary. If it potentially affects load/save (which uses the same code path) then yes, I'd apprechiate a minor_version bump.

**Comment by Zwelf** [comment]
And reading the code, it seems to only make practice behave differently, so no minor bump from my side expected.

**Comment by ChillerDragon** [comment]
Tested this in game. Works well. Thanks @Pioooooo c:
