### PR TITLE
fix tooltips rendering when they shouldn't, fixes #5035

### LINKED ISSUE #5035: Closing ingame menu while tooltip is shown -> fat tooltip ingame
image

### PR DESCRIPTION
**Pull request by edg-l**
fixes #5035

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/components/tooltips.cpp [hunk 1]
```diff
@@ -33,13 +33,17 @@ void CTooltips::DoToolTip(const void *pID, const CUIRect *pNearRect, const char
...
+							   WidthHint,
+							   false});
 	CTooltip &Tooltip = result.first->second;
 
 	if(!result.second)
 	{
 		Tooltip.m_Rect = *pNearRect; // update in case of window resize
 	}
+
+	Tooltip.m_OnScreen = true;
```
Comment (def-) [inline src/game/client/components/tooltips.cpp:45]: Why set it to false first then true here?

Comment (Jupeyy) [reply src/game/client/components/tooltips.cpp:45]: does it matter tho, this call has to stay anyway. But technically you are right ^^
