### PR TITLE
Only print log messages for failed unit tests by default

### LINKED ISSUE #8361: The tests have too much output. It is hard to find the failing tests.
In my opinion a good test output should show errors. The current test run hides the interesting errors in a wall of OK messages and debug/log prints.

### PR DESCRIPTION
**Pull request by Robyt3**
Set a custom global logger that switches between forwarding log messages to a regular global logger and storing the log messages in a memory logger. Use a gtest `::testing::TestEventListener` to listen for the start and end of tests. On test start, set the memory logger to capture the log messages. On test end, if the test failed, forward the stored log messages to the global logger, i.e., log them to stdout.

Add the optional parameter `--no-capture` to the testrunner to always log the output also for passed tests as before.

Use a custom global logger instead of a scope logger, as scope loggers are thread local, so they cannot be used to capture the output of other threads in the gameworld tests.

Closes #8361.

## Checklist

- [X] Tested the change
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or Valgrind's memcheck](https://github.com/ddnet/ddnet/blob/master/docs/DEBUGGING.md#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)
- [X] I didn't use generative AI to generate more than single-line completions

### CODE REVIEW

**Comment by Robyt3** [comment]
By running with `testrunner --gtest_brief=1`, the output is very brief and only includes the output of `dbg_assert`s, failing tests, and summary.

The log messages for asserts triggered during death tests cannot be filtered with this approach, because the test runner is executed as a separate process for each death test.

File: src/test/test.cpp [hunk 1]
```diff
@@ -141,13 +143,116 @@ CTestInfo::~CTestInfo()
...
+
 int main(int argc, const char **argv)
 {
+	std::unique_ptr<ILogger> pDefaultLogger = log_logger_default();
+	CTestLogger *pTestLogger = nullptr;
+	if(pDefaultLogger != nullptr)
+	{
+		pTestLogger = std::make_unique<CTestLogger>(std::move(pDefaultLogger)).release();
+		log_set_global_logger(pTestLogger);
+	}
```
Comment (heinrich5991) [inline src/test/test.cpp]:
```suggestion
	CTestLogger *pTestLogger = std::make_unique<CTestLogger>(pDefaultLogger).release();
	log_set_global_logger(pTestLogger);
```
I think the returned pointer should never be nullptr. If we think that it should have that possibility, the docs should mention it.

File: src/test/test.cpp [hunk 2]
```diff
@@ -141,13 +143,116 @@ CTestInfo::~CTestInfo()
...
 	GTEST_FLAG_SET(death_test_style, "threadsafe");
+
+	if(pTestLogger != nullptr)
+	{
+		bool Verbose = false;
+		if(argc >= 2)
+		{
+			for(int Argument = 1; Argument < argc; ++Argument)
+			{
+				if(str_comp(argv[Argument], "--verbose") == 0)
```
Comment (heinrich5991) [inline src/test/test.cpp]: Rust calls this `--no-capture`, maybe we could copy this.

```
        --no-capture    don't capture stdout/stderr of each task, allow
                        printing directly
```

**Review by heinrich5991 — COMMENTED** [review]
What happens if multiple tests run at the same time? Apparently GTest doesn't support this? So it's fine.

The code looks good to me. :)

File: src/test/test.cpp (hunk 1 above)
Comment (Robyt3) [reply src/test/test.cpp]: `log_logger_stdout` can return `nullptr` on Windows. I could change `log_logger_default` to return `log_logger_noop` instead of `nullptr` to avoid this particular check (and update the documentation), but we also check for `log_logger_stdout` logger being `nullptr` when using that function.

File: src/test/test.cpp (hunk 2 above)
Comment (Robyt3) [reply src/test/test.cpp]: Seems good. It currently always captures the output but only prints it conditionally, but it could also be changed to capture conditionally too.

**Comment by Robyt3** [comment]
> What happens if multiple tests run at the same time? Apparently GTest doesn't support this? So it's fine.

Doesn't seem to be supported by gtest. There's a separate wrapper script https://github.com/google/gtest-parallel that can be used to parallelize tests, but it launches separate processes so it should be compatible with this approach.

File: src/test/test.cpp (hunk 1 above)
Comment (heinrich5991) [reply src/test/test.cpp]: We should document that `log_logger_stdout` can return `nullptr`. Then I'm fine with either:
1) Documenting that `log_logger_default` can return `nullptr`.
2) Make `log_logger_default` return `log_logger_noop` instead of `nullptr`.

Perhaps slightly leaning towards 2).

Comment (Robyt3) [reply src/test/test.cpp]: Done, `log_logger_default` always returns a non-`nullptr` logger now.

File: src/test/test.cpp (hunk 2 above)
Comment (Robyt3) [reply src/test/test.cpp]: Done.

**Review by heinrich5991 — APPROVED** [review]
Thanks. :)

**Comment by ChillerDragon** [comment]
Thanks for working on this @Robyt3 :)
