### PR TITLE
Fix editor image delete

### LINKED ISSUE #5675: Editor: Crashes after removing specific mapres.
This one is weird.

To reproduce:
1. Set renderer to vulkan in graphics tab (client restart necessary)
2. Open [DM_Gores_test.zip](https://github.com/ddnet/ddnet/files/9223464/DM_Gores_test.zip)
3. Go to images, remove grass_main or grass_doodads.
4. Now click on Images to go to Sounds.
5. Crashes if you click on Sounds to go back to Layers.

According to another user this only happens, if the layers in which the images are used get displayed.

E.g. if the layers are empty or if you hide the layers it does not crash (but it will crash if you display the layers again).

Client version: 16.2.2 released, non steam and DDNet-16.2.2-20220729-win64
OS win 10 64bit

### PR DESCRIPTION
**Pull request by Jupeyy**
fixes #5675

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/editor/layer_tiles.cpp [hunk 1]
```diff
@@ -1044,7 +1044,10 @@ void CLayerTiles::FlagModified(int x, int y, int w, int h)
 
 void CLayerTiles::ModifyImageIndex(INDEX_MODIFY_FUNC Func)
 {
+	const auto ImgBefore = m_Image;
```
Comment (Chairn) [inline src/game/editor/layer_tiles.cpp:1047]: PreviousImg?

**Review by Chairn — APPROVED** [review]
