### PR TITLE
Fix zoom (fixes #3619)

### LINKED ISSUE #3619: Dummy broken?
Halp reports broken dummy on Discord @trml ?

https://user-images.githubusercontent.com/2335377/107862935-9c151b00-6e50-11eb-856b-49049ce75d6e.mp4

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/gameclient.cpp [hunk 1]
```diff
@@ -1630,12 +1630,12 @@ void CGameClient::OnNewSnapshot()
...
-															   :
-															   m_pCamera->m_ZoomSmoothingTarget < m_pCamera->m_Zoom ? m_LastZoom // Zooming in
-																						  :
-																						  m_pCamera->m_Zoom; // Not zooming
+			   :
+			   m_pCamera->m_ZoomSmoothingTarget > m_pCamera->m_Zoom ? m_pCamera->m_ZoomSmoothingTarget // Zooming out
+			   :
+			   (m_pCamera->m_ZoomSmoothingTarget < m_pCamera->m_Zoom && m_LastZoom > 0) ? m_LastZoom // Zooming in
+												      :
+                                                                                                      m_pCamera->m_Zoom; // Not zooming
```
Comment (heinrich5991) [inline src/game/client/gameclient.cpp:1638]: That's quite an abomination. :D

Comment (def-) [reply src/game/client/gameclient.cpp]: Indeed, changed.

**Comment by heinrich5991** [comment]
bors r+

Thanks.
