### PR TITLE
Fix cutting 0.6 demos

### LINKED ISSUE #8748: Demo cutting broken
Fussel reported that on newest nightly, demo cutting appears to be broken.

https://github.com/user-attachments/assets/690c9db1-e9cd-4d15-9ffe-19dc89cccc4c

Other demos:
[demos.zip](https://github.com/user-attachments/files/16638031/demos.zip)
geht.demo is before cutting, futsch.demo afterwards. Note that the demo's size decreases even though nothing was cut out.

### PR DESCRIPTION
**Pull request by ChillerDragon**
Closed #8748

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/shared/demo.cpp [hunk 1]
```diff
@@ -1234,6 +1234,7 @@ bool CDemoEditor::Slice(const char *pDemo, const char *pDst, int StartTick, int
 
 	const CMapInfo *pMapInfo = DemoPlayer.GetMapInfo();
 	const CDemoPlayer::CPlaybackInfo *pInfo = DemoPlayer.Info();
+	DemoPlayer.SetSixup(str_startswith(pInfo->m_Header.m_aNetversion, "0.7"));
```
Comment (Robyt3) [inline src/engine/shared/demo.cpp:1237]: It seems prone to errors to have to do this manually. `CDemoPlayer::m_Sixup` is generally uninitialized, so forgetting to use `SetSixup` on a demo player causes undefined behavior during playback. The same would be missing in the `demo_extract_chat` tool for example.

This should rather happen automatically in `CDemoPlayer::Load`, when the header has been loaded. The client should update its own `m_Sixup` with `m_Sixup = m_DemoPlayer.IsSixup()` and `CDemoPlayer::GetSixup` should be removed.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

**Comment by ChillerDragon** [comment]
After adding rossbits feedback I tested cutting and playing back two slices of 0.6 and 0.7 demos. Everything was smooth.

**Review by def- — APPROVED** [review]
