### PR TITLE
Fix stack overflow in destructor when dnsbl object is kept too long alive

### LINKED ISSUE #6954: Crash in DNSBL on RUS
```
Core was generated by `./DDRace64-Server_sql -f servers/8348.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005630ffcf5115 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x563107e4b4c0) at /usr/include/c++/12/bits/shared_ptr_base.h:346
346		      _M_dispose();
[Current thread is 1 (Thread 0x7f91be1d1a00 (LWP 2256099))]
(gdb) bt
#0  0x00005630ffcf5115 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x563107e4b4c0) at /usr/include/c++/12/bits/shared_ptr_base.h:346
#1  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x563107e4b4c0)
    at /usr/include/c++/12/bits/shared_ptr_base.h:317
#2  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1071
#3  std::__shared_ptr<IJob, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1524
#4  std::shared_ptr<IJob>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/12/bits/shared_ptr.h:175
#5  IJob::~IJob (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:23
#6  0x00005630ffcf5117 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x563107e4b3e0) at /usr/include/c++/12/bits/shared_ptr_base.h:346
#7  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x563107e4b3e0)
    at /usr/include/c++/12/bits/shared_ptr_base.h:317
#8  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1071
#9  std::__shared_ptr<IJob, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1524
#10 std::shared_ptr<IJob>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/12/bits/shared_ptr.h:175
#11 IJob::~IJob (this=<optimized out>, __in_chrg=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:23
#12 0x00005630ffcf5117 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x563107e4b300) at /usr/include/c++/12/bits/shared_ptr_base.h:346
#13 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x563107e4b300)
    at /usr/include/c++/12/bits/shared_ptr_base.h:317
#14 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1071
#15 std::__shared_ptr<IJob, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1524
#16 std::shared_ptr<IJob>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/12/bits/shared_ptr.h:175
#17 IJob::~IJob (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:23
#18 0x00005630ffcf5117 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x563107e4b220) at /usr/include/c++/12/bits/shared_ptr_base.h:346
#19 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x563107e4b220)
    at /usr/include/c++/12/bits/shared_ptr_base.h:317
#20 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1071
#21 std::__shared_ptr<IJob, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1524
#22 std::shared_ptr<IJob>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/12/bits/shared_ptr.h:175
--Type <RET> for more, q to quit, c to continue without paging--
#23 IJob::~IJob (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:23
#24 0x00005630ffcf5117 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x563107e4b140) at /usr/include/c++/12/bits/shared_ptr_base.h:346
#25 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x563107e4b140)
    at /usr/include/c++/12/bits/shared_ptr_base.h:317
#26 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1071
#27 std::__shared_ptr<IJob, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1524
#28 std::shared_ptr<IJob>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/12/bits/shared_ptr.h:175
#29 IJob::~IJob (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:23
#30 0x00005630ffcf5117 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x563107e4b060) at /usr/include/c++/12/bits/shared_ptr_base.h:346
#31 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x563107e4b060)
    at /usr/include/c++/12/bits/shared_ptr_base.h:317
#32 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1071
#33 std::__shared_ptr<IJob, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1524
#34 std::shared_ptr<IJob>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/c++/12/bits/shared_ptr.h:175
#35 IJob::~IJob (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:23
#36 0x00005630ffcf5117 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x563107e4af80) at /usr/include/c++/12/bits/shared_ptr_base.h:346
#37 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x563107e4af80)
    at /usr/include/c++/12/bits/shared_ptr_base.h:317
#38 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1071
#39 std::__shared_ptr<IJob, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1524
#40 std::shared_ptr<IJob>::~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/12/bits/shared_ptr.h:175
#41 IJob::~IJob (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:23
#42 0x00005630ffcf5117 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (
    this=0x563107e4aea0) at /usr/include/c++/12/bits/shared_ptr_base.h:346
#43 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x563107e4aea0)
    at /usr/include/c++/12/bits/shared_ptr_base.h:317
#44 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1071
#45 std::__shared_ptr<IJob, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    __in_chrg=<optimized out>) at /usr/include/c++/12/bits/shared_ptr_base.h:1524
```
The backtrace then just repeats endlessly for at least 200k lines. (These weird unexplainable crashes always seem to happen on RUS, I think we might have broken hardware there.)

### PR DESCRIPTION
**Pull request by Zwelf**
`shared_ptr`s of `CServer::m_pDnsblLookup[ClientID]` are set, but not cleaned up when done. Therefore the Job is kept alive until the player disconnects and a new player joins on that slot. Currently this means that the full linked list of jobs is kept alive.

When the Job is overwritten with a new job, all the remaining objects in the list can be dropped. With enough jobs, that is causing a stack overflow in the destructor.

This patch fixes this overflow by making the lifetime independent of the previous Job. Jobs can get dropped after processing them, even when the previous job is still alive.

Fixes #6954

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/shared/jobs.cpp [hunk 1]
```diff
@@ -62,6 +62,11 @@ void CJobPool::WorkerThread(void *pUser)
 			{
 				pJob = pPool->m_pFirstJob;
 				pPool->m_pFirstJob = pPool->m_pFirstJob->m_pNext;
+				// allow remaining objects in list to destruct, even when current object stays alive
+				if(pJob)
```
Comment (heinrich5991) [inline src/engine/shared/jobs.cpp:66]: The `if` is superfluous, `pJob` is non-null.

**Comment by heinrich5991** [comment]
Looks good, thanks!
