### PR TITLE
Use temporary file when saving editor map

### LINKED ISSUE #4476: Editor map saves should go into a temporary file first
Map saving should go to a temporary file first so that crashes don't corrupt the existing map file. Move it over to the correct name after finishing.

### PR DESCRIPTION
**Pull request by Robyt3**
Write the map to a temporary file first. When the map was saved to the temporary file successfully, first delete the existing map file having the real filename, then rename the temporary file to the real filename.

If deleting or renaming fails, show an error message popup and log an error message to the console.

The implementation is consistent with the way temporary files are utilized by Microsoft Word, so this should work on Windows.

See: https://support.microsoft.com/en-us/topic/description-of-how-word-creates-temporary-files-66b112fb-d2c0-8f40-a0be-70a367cc4c85

Different from #4482, this first deletes the old map file before renaming the temporary file. Although it appears that renaming a file would also override the target file, it could be that this does not work on all systems. Additionally, this adds descriptive error messages in the cases of failure.

Closes #4476.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/editor/editor.cpp [hunk 1]
```diff
@@ -7448,10 +7448,27 @@ void CEditor::HandleWriterFinishJobs()
 	std::shared_ptr<CDataFileWriterFinishJob> pJob = m_WriterFinishJobs.front();
 	if(pJob->Status() != IJob::STATE_DONE)
 		return;
+	m_WriterFinishJobs.pop_front();
 
-	char aBuf[IO_MAX_PATH_LENGTH + 32];
-	str_format(aBuf, sizeof(aBuf), "saving '%s' done", pJob->GetFileName());
-	Console()->Print(IConsole::OUTPUT_LEVEL_ADDINFO, "editor", aBuf);
+	char aBuf[2 * IO_MAX_PATH_LENGTH + 128];
+	if(Storage()->FileExists(pJob->GetRealFileName(), IStorage::TYPE_SAVE) && !Storage()->RemoveFile(pJob->GetRealFileName(), IStorage::TYPE_SAVE))
```
Comment (heinrich5991) [inline src/game/editor/editor.cpp:7454]: Generally, any kind of `FileExists` check shouldn't be necessary. Try the operation and see if it failed because there's no file. If so, no problem. Unfortunately, our code doesn't get the precise error (file not found vs others), so this isn't really possible.

**Comment by heinrich5991** [comment]
LGTM. Thanks!

File: src/game/editor/editor.cpp (hunk 1 above)
Comment (Robyt3) [reply src/game/editor/editor.cpp:7454]: This check is only to prevent the `dbg_msg` "failed to remove: filename.map" that's printed in `CStorage´ when the file doesn't exist.

**Review by def- — APPROVED** [review]
On non-Windows we could overwrite the original file with the new temp file, that is an atomic action so you always end up with a map file
