### PR TITLE
Fix client crash when community removed while on browser tab

### LINKED ISSUE #11153: Quickly refreshing server browser sometimes causes communities to not load, rarely also crashes with assertion
Reported by 6721 on Discord:

> holding ctrl+r in serverlist makes communities not load sometimes (both tabs and icons on servers) also it crashed the game once when I held it for a while 

Image

Image

Assertion error `Invalid community index`.

Also got another crash:

```
DDNet.exe caused an Access Violation at location 00007FF7A133DD8C in module DDNet.exe Reading from location 0000022899B67640.

AddrPC           Params
00007FF7A133DD8C 0000022899B67620 0000000000000000 00007FF73F800000  DDNet.exe!CCommunityCountry::FlagId+0xc  [ddnet/src/engine/serverbrowser.h @ 162]
   160: 
   161: const char *Name() const { return m_aName; }
>  162: int FlagId() const { return m_FlagId; }
   163: const std::vector<CCommunityCountryServer> &Servers() const { return m_vServers; }
   164: };
00007FF7A1419C67 0000005E772FE1A0 00007FF700000000 0000005E772FE1A0  DDNet.exe!CMenus::RenderServerbrowserCommunitiesFilter+0x617  [ddnet/src/game/client/components/menus_browser.cpp @ 1070]
  1068: Item.w = Item.h * 2.0f;
  1069: Item.x += (OldWidth - Item.w) / 2.0f;
> 1070: GameClient()->m_CountryFlags.Render(ServerBrowser()->CommunityCache().SelectableCountries()[ItemIndex]->FlagId(), ColorRGBA(1.0f, 1.0f, 1.0f, (Active ? 0.9f : 0.2f) + (Ui()->HotItem() == pItemId ? 0.1f : 0.0f)), Item.x, Item.y, Item.w, Item.h);
  1071: };
  1072: 
00007FF7A14232F0 0000005E772FE5E0 0000005E772FE348 0000005E772FE310  DDNet.exe!CMenus::UpdateCommunityCache+0x31a8  [D:/Standalone-Software/msys64/mingw64/include/c++/15.2.0/bits/invoke.h @ 63]
    61:     constexpr _Res
    62:     __invoke_impl(__invoke_other, _Fn&& __f, _Args&&... __args)
>   63:     { return std::forward<_Fn>(__f)(std::forward<_Args>(__args)...); }
    64: 
    65:   template<typename _Res, typename _MemFun, typename _Tp, typename... _Args>
00007FF7A1422932 0000005E772FE5E0 0000005E772FE348 0000005E772FE310  DDNet.exe!CMenus::UpdateCommunityCache+0x27ea  [D:/Standalone-Software/msys64/mingw64/include/c++/15.2.0/bits/invoke.h @ 113]
   111:       using __tag = typename __result::__invoke_type;
   112:       if constexpr (is_void_v<_Res>)
>  113: std::__invoke_impl<__type>(__tag{}, std::forward<_Callable>(__fn),
   114: std::forward<_Args>(__args)...);
   115:       else
00007FF7A142177C 0000005E772FE5E0 0000005E772FE348 0000005E772FE310  DDNet.exe!CMenus::UpdateCommunityCache+0x1634  [D:/Standalone-Software/msys64/mingw64/include/c++/15.2.0/bits/std_function.h @ 292]
   290:       _M_invoke(const _Any_data& __functor, _ArgTypes&&... __args)
   291:       {
>  292: return std::__invoke_r<_Res>(*_Base::_M_get_pointer(__functor),
   293:      std::forward<_ArgTypes>(__args)...);
   294:       }
00007FF7A142435A 0000005E772FE5E0 0000022800000000 0000005E00000000  DDNet.exe!std::function<void (int, CUIRect, void const*, bool)>::operator()+0x6a  [D:/Standalone-Software/msys64/mingw64/include/c++/15.2.0/bits/std_function.h @ 593]
   591: if (_M_empty())
   592:   __throw_bad_function_call();
>  593: return _M_invoker(_M_functor, std::forward<_ArgTypes>(__args)...);
   594:       }
   595: 
00007FF7A14190EA 0000022887C06998 0000005E772FE598 00000228887F3008  DDNet.exe!CMenus::RenderServerbrowserDDNetFilter+0x6a8  [ddnet/src/game/client/components/menus_browser.cpp @ 983]
   981: if(Ui()->HotItem() == pItemId && !ScrollRegion.Animating())
   982: Item.Draw(ColorRGBA(1.0f, 1.0f, 1.0f, 0.33f), IGraphics::CORNER_ALL, 2.0f);
>  983: RenderItem(ItemIndex, Item, pItemId, Active);
   984: }
   985: 
00007FF7A1419ED9 00007FF7A196152E 00007FF7A1961260 0000005E0000000C  DDNet.exe!CMenus::RenderServerbrowserCountriesFilter+0x1ff  [ddnet/src/game/client/components/menus_browser.cpp @ 1073]
  1071: };
  1072: 
> 1073: RenderServerbrowserDDNetFilter(View, ServerBrowser()->CountriesFilter(), ItemHeight + 2.0f * Spacing, MaxEntries, EntriesPerRow, s_ScrollRegion, s_vItemIds, false, GetItemName, RenderItem);
  1074: }
  1075: 
00007FF7A14186D5 0000005E772FE800 0000022800000000 000002280000000C  DDNet.exe!CMenus::RenderServerbrowserFilters+0x116f  [ddnet/src/game/client/components/menus_browser.cpp @ 821]
   819: if(s_ActiveTab == FILTERTAB_COUNTRIES)
   820: {
>  821: RenderServerbrowserCountriesFilter(TabContents);
   822: }
   823: else if(s_ActiveTab == FILTERTAB_TYPES)
00007FF7A141F921 0000005E772FE8C0 0000005E42820000 0000005E772FE800  DDNet.exe!CMenus::RenderServerbrowserToolBox+0xcd  [ddnet/src/game/client/components/menus_browser.cpp @ 1782]
  1780: {
  1781: case UI_TOOLBOX_PAGE_FILTERS:
> 1782: RenderServerbrowserFilters(ToolBox);
  1783: return;
  1784: case UI_TOOLBOX_PAGE_INFO:
00007FF7A141FD38 0000005E772FE980 00007FF741C00000 0000005E772FE990  DDNet.exe!CMenus::RenderServerbrowser+0x392  [ddnet/src/game/client/components/menus_browser.cpp @ 1855]
  1853: 
  1854: RenderServerbrowserTabBar(TabBar);
> 1855: RenderServerbrowserToolBox(ToolBox);
  1856: }
  1857: 
00007FF7A1403019 0000005E772FEA20 BF800000BF800000 0000005EBF800000  DDNet.exe!CMenus::Render+0x577  [ddnet/src/game/client/components/menus.cpp @ 1119]
  1117: else if(m_MenuPage >= PAGE_INTERNET && m_MenuPage <= PAGE_FAVORITE_COMMUNITY_5)
  1118: {
> 1119: RenderServerbrowser(MainView);
  1120: }
  1121: else if(m_MenuPage == PAGE_DEMOS)
00007FF7A140B41E 00000228887E8E70 0000005E772FEC90 000002283F008081  DDNet.exe!CMenus::OnRender+0x262  [ddnet/src/game/client/components/menus.cpp @ 2322]
  2320: Ui()->Update();
  2321: 
> 2322: Render();
  2323: 
  2324: if(IsActive())
00007FF7A152542B 0000022887B50040 0000000000000001 000000003B9ACA00  DDNet.exe!CGameClient::OnRender+0x32f  [ddnet/src/game/client/gameclient.cpp @ 829]
   827: // render all systems
   828: for(auto &pComponent : m_vpAll)
>  829: pComponent->OnRender();
   830: 
   831: // clear all events/input for this frame
00007FF7A12D0F09 0000022887B50040 0000005E444DE143 0000005E3F800000  DDNet.exe!CClient::Render+0x5d  [ddnet/src/engine/client/client.cpp @ 1132]
  1130: else
  1131: {
> 1132: GameClient()->OnRender();
  1133: }
  1134: 
00007FF7A12D9B54 0000005E772FF704 0000005E772FF750 0000000000000004  DDNet.exe!CClient::Run+0x1354  [ddnet/src/engine/client/client.cpp @ 3318]
  3316: m_LastRenderTime = Now;
  3317: 
> 3318: Render();
  3319: m_pGraphics->Swap();
  3320: }
00007FF7A12E263F 00007FF700000001 00007FF7A1AF2D78 0000000000000001  DDNet.exe!main+0x12a9  [ddnet/src/engine/client/client.cpp @ 4958]
  4956: // run the client
  4957: log_trace("client", "initialization finished after %.2fms, starting...", (time_get() - MainStart) * 1000.0f / (float)time_freq());
> 4958: pClient->Run();
  4959: 
  4960: const bool Restarting = pClient->State() == CClient::STATE_RESTARTING;
```

0790cc1e

### PR DESCRIPTION
**Pull request by Robyt3**
Immediately after refreshing the communities from the DDNet info, the serverlist type of the engine serverbrowser needs to be reset if a favorite community tab is selected but not enough communities are available anymore, as the engine serverbrowser will subsequently use the serverlist type to refresh the filtered serverlist.

Closes #11153.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/client/serverbrowser.cpp [hunk 1]
```diff
@@ -1668,6 +1669,21 @@ void CServerBrowser::UpdateServerRank(CServerInfo *pInfo) const
...
+{
+	if(m_ServerlistType >= IServerBrowser::TYPE_FAVORITE_COMMUNITY_1 &&
+		m_ServerlistType <= IServerBrowser::TYPE_FAVORITE_COMMUNITY_5)
+	{
+		const size_t CommunityIndex = m_ServerlistType - IServerBrowser::TYPE_FAVORITE_COMMUNITY_1;
+		if(CommunityIndex >= FavoriteCommunities().size())
+		{
+			// Reset to internet type if there is no favorite community for the current browser type,
+			// in case communities have been removed.
+			m_ServerlistType = IServerBrowser::TYPE_INTERNET;
```
Comment (AssassinTee) [inline src/engine/client/serverbrowser.cpp:1682]: Wouldn't it make more sense to update to `FavoriteCommunities().size()  - 1` and then fall back if that is not available?

Comment (Robyt3) [reply src/engine/client/serverbrowser.cpp:1682]: I think resetting to the internet type/page is simpler. This should also be consistent with the handling in the menus, which currently reset to the internet page:

https://github.com/ddnet/ddnet/blob/98f175ead292b058c18f0c98bb4b185d2fa42ccc/src/game/client/components/menus_browser.cpp#L1931-L1962
