### PR TITLE
Global lock for MySQL Connector's get_driver_instance (fixes #1131)

### LINKED ISSUE #1131: Segfault when connecting to CSqlServer (on RUS)
```
(gdb) bt
#0  0x00007fe2bc001140 in ?? ()
#1  0x000056106a94b91b in CSqlServer::Connect (this=this@entry=0x56106b4a7240)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:118
#2  0x000056106a94c656 in CSqlServer::CreateTables (this=0x56106b4a7240)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:165
#3  0x00007fe2cf3b3494 in start_thread (arg=0x7fe2c997c700) at pthread_create.c:333
#4  0x00007fe2cd95aacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

### PR DESCRIPTION
**Pull request by def-**
See note in https://dev.mysql.com/doc/connector-cpp/1.1/en/connector-cpp-examples-connecting.html

> get_mysql_driver_instance() calls get_driver_instance(), which is not
> thread-safe. Either avoid invoking these methods from within multiple
> threads at once, or surround the calls with a mutex to prevent
> simultaneous execution in multiple threads.

### CODE REVIEW

**Comment by Learath2** [comment]
Do we call it from multiple threads? I don't remember seeing more then one
call to it, in a thread that we spawn more then once.

**Comment by ChillerDragon** [comment]
Did the ddnet even ever crashed?

**Comment by def-** [comment]
Yes, see GER2 with the current core file, two servers were being connected at the same time. I presume that that's why it segfaulted.

**Comment by Learath2** [comment]
Yes Chiller check #1131. @def- my scopes are a bit rusty but I doubt that
variable can stretch across multiple processes.

**Comment by def-** [comment]
Variables? My guess is just that calling get_driver_instance in two threads around the same time leads to undefined behaviour and then when you end up connecting on the instance you segfault because the pointer to the object is invalid.

**Comment by Learath2** [comment]
And you used a mutex inside `CServer` to prevent that, however we have many
servers running each with their own instance of `CServer` and thus the
mutex. No?

**Comment by Learath2** [comment]
Hence I said we dont have multiple threads calling
`get_mysql_driver_instance()` one `CSqlScore` per `CServer` right? Anyways
I just skimmed over the code. No downsides to one extra lock. Feel free to
merge if you think it helps.

**Comment by def-** [comment]
We have one CSqlScore per registered mysql server. So on GER2 we do have 6 of them.

File: src/engine/server/sql_server.cpp [hunk 1]
```diff
@@ -114,7 +116,10 @@ bool CSqlServer::Connect()
 		connection_properties["OPT_CHARSET_NAME"] = sql::SQLString("utf8mb4");
 
 		// Create connection
-		m_pDriver = get_driver_instance();
+		{
+			LockScope globalLock(m_GlobalLock);
```
Comment (heinrich5991) [inline src/engine/server/sql_server.cpp]: Naming convention. `GlobalLock`.

File: src/engine/server/sql_server.h [hunk 2]
```diff
@@ -7,10 +7,28 @@
 #include <cppconn/exception.h>
 #include <cppconn/statement.h>
 
+class LockScope
```
Comment (heinrich5991) [inline src/engine/server/sql_server.h]: This is what `scope_lock` from src/base/tl/threading.h` does.

File: src/engine/server/sql_server.h [hunk 3]
```diff
@@ -52,6 +70,7 @@ class CSqlServer
 	bool m_SetUpDB;
 
 	LOCK m_SqlLock;
+	LOCK &m_GlobalLock;
```
Comment (heinrich5991) [inline src/engine/server/sql_server.h]: We usually don't use (non-const) references in Teeworlds code.
