### PR TITLE
Fix coloring of team chat. Fixes #648

### LINKED ISSUE #648: Teamchat: player's nickname has the same color value as the text
how it looks now:
ss 2017-02-27 at 11 48 26

how it should look:
ss 2017-02-27 at 11 49 33

### PR DESCRIPTION
**Pull request by Learath2**
Should maybe standardize CalculateNameColor to all messages at some point

### CODE REVIEW

File: src/game/client/gameclient.h [hunk 1]
```diff
@@ -439,6 +439,10 @@ inline vec3 RgbToHsl(vec3 RGB)
 
 }
 
+inline vec3 CalculateNameColor(vec3 TextColorHSL)
+{
+	return HslToRgb(vec3(TextColorHSL.h, TextColorHSL.s * 0.68f, TextColorHSL.l * 0.81f));
+}
```
Comment (heinrich5991) [inline src/game/client/gameclient.h]: Am I still allowed to complain? Maybe this should better go to some `.cpp` file.

Comment (Learath2) [inline src/game/client/gameclient.h]: Sure. Have no idea where to put it tho.
