### PR TITLE
Trivial name plate changes to fix #9808

### LINKED ISSUE #9808: client startup crash in CClient::OnWindowResize nullptr deref in CNamePlates::ResetNamePlates
DDNet sometimes crashes on startup for me:

```
Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
0x000055555590387e in __gnu_cxx::__normal_iterator<std::unique_ptr<CNamePlatePart, std::default_delete<CNamePlatePart> >*, std::vector<std::unique_ptr<CNamePlatePart, std::default_delete<CNamePlatePart> >, std::allocator<std::unique_ptr<CNamePlatePart, std::default_delete<CNamePlatePart> > > > >::__normal_iterator (
    this=0x7fffffffd430, 
    __i=<error reading variable: Cannot access memory at address 0x10>)
    at /usr/include/c++/14.2.1/bits/stl_iterator.h:1068
1068	      : _M_current(__i) { }
```

backtrace: [bt](https://zwelf.strct.cc/ddnet/issues/9808/bt.html), [bt-full](https://zwelf.strct.cc/ddnet/issues/9808/bt-full.html)

full log:

<details>

```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe41746c0 (LWP 4976)]
2025-03-05 10:38:36 I engine: running on unix-linux-amd64
2025-03-05 10:38:36 I engine: arch is little endian
2025-03-05 10:38:36 I engine: operating system version: Linux 6.12.9-arch1-1 (x86_64, #1 SMP PREEMPT_DYNAMIC Fri, 10 Jan 2025 00:39:41 +0000); "Arch Linux"
2025-03-05 10:38:36 E storage: couldn't open storage.cfg
2025-03-05 10:38:36 I storage: using standard paths
2025-03-05 10:38:36 I storage: added path '$USERDIR' ('/home/user/.local/share/ddnet')
2025-03-05 10:38:36 I storage: added path '$DATADIR' ('data')
2025-03-05 10:38:36 I storage: added path '$CURRENTDIR' ('/home/user/dev/ddnet/build')
2025-03-05 10:38:36 I console: executing 'settings_ddnet.cfg'
2025-03-05 10:38:36 I console: executing 'autoexec.cfg'
2025-03-05 10:38:36 I http: libcurl version 8.11.1 (compiled = 8.11.1)
2025-03-05 10:38:36 I sdl: SDL version 2.30.11 (compiled = 2.30.11)
2025-03-05 10:38:36 I gfx: Created Vulkan 1.1 context.
2025-03-05 10:38:36 I gfx: GPU vendor: AMD
2025-03-05 10:38:36 I gfx: GPU renderer: AMD Radeon Graphics (RADV RENOIR)
2025-03-05 10:38:36 I gfx: GPU version: Vulkan 1.3.296 (driver: 24.3.3)
2025-03-05 10:38:36 I sound: sound init successful using audio driver 'pulseaudio'
2025-03-05 10:38:36 I textrender: Freetype version 2.13.3 (compiled = 2.13.3)
2025-03-05 10:38:36 I joystick: 0 joystick(s) found
[New Thread 0x7fff515fc6c0 (LWP 5043)]
2025-03-05 10:38:36 E serverbrowser: invalid address (ServerIndex=0, TypeIndex=6, AddressIndex=6)
2025-03-05 10:38:36 E serverbrowser: invalid address (ServerIndex=0, TypeIndex=8, AddressIndex=8)
[Thread 0x7fff515fc6c0 (LWP 5043) exited]

Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
0x000055555590387e in __gnu_cxx::__normal_iterator<std::unique_ptr<CNamePlatePart, std::default_delete<CNamePlatePart> >*, std::vector<std::unique_ptr<CNamePlatePart, std::default_delete<CNamePlatePart> >, std::allocator<std::unique_ptr<CNamePlatePart, std::default_delete<CNamePlatePart> > > > >::__normal_iterator (
    this=0x7fffffffd430, 
    __i=<error reading variable: Cannot access memory at address 0x10>)
    at /usr/include/c++/14.2.1/bits/stl_iterator.h:1068
1068	      : _M_current(__i) { }
```
</details>

### PR DESCRIPTION
**Pull request by SollyBunny**
`m_pNamePlates` is now inited in constructer instead of OnInit so it can handle resize's before OnInit

Should close #9808 @Zwelf 

Also renamed `m_aNamePlates` to `m_pNamePlates`

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by Robyt3 — APPROVED** [review]

File: src/game/client/components/nameplates.h [hunk 1]
```diff
@@ -47,16 +47,16 @@ class CNamePlate;
 class CNamePlates : public CComponent
 {
 private:
-	CNamePlate *m_aNamePlates = nullptr;
+	CNamePlate *m_pNamePlates;
```
Comment (Robyt3) [inline src/game/client/components/nameplates.h:50]: `m_apNamePlates`

**Review by Robyt3 — CHANGES_REQUESTED** [review]

File: src/game/client/components/nameplates.h (hunk 1 above)
Comment (Robyt3) [reply src/game/client/components/nameplates.h:50]: Never mind, I also got confused.
