### PR TITLE
Fix chat messages being truncated in server log dump

### LINKED ISSUE #10781: some dump_log chat lines get cut off
```
2025-08-29 13:59:36 I chat/all: XXX: привет мои фанаты, кто хочет узнать побольше обо мне переходите на мой онлик <3 https://onlyfans.com/XXX
```

but `dump_log` only shows

```
2025-08-29 14:59:42 I log: Chat: привет мои фанаты, кто хочет узнать побольше обо мне переходите на, 6 seconds ago < XXX
```

### PR DESCRIPTION
**Pull request by Robyt3**
Closes #10781.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/server/gamecontext.cpp [hunk 1]
```diff
@@ -641,7 +641,7 @@ void CGameContext::SendChat(int ChatterClientId, int Team, const char *pText, in
 		if(ProcessSpamProtection(SpamProtectionClientId))
 			return;
 
-	char aBuf[256], aText[256];
+	char aBuf[256 + 8], aText[256];
 	str_copy(aText, pText, sizeof(aText));
 	if(ChatterClientId >= 0 && ChatterClientId < MAX_CLIENTS)
 		str_format(aBuf, sizeof(aBuf), "%d:%d:%s: %s", ChatterClientId, Team, Server()->ClientName(ChatterClientId), aText);
```
Comment (AssassinTee) [inline src/game/server/gamecontext.cpp]: @Robyt3 the `+ 8` might not be enough, if `aText` can have 256 chars. I believe client names can be longer and you have 2/3 extra digits for the ChatterClientId and 2 digits for the Team and extra digits from the other symbols

Comment (Robyt3) [reply src/game/server/gamecontext.cpp]: I'll rewrite the logs using `log_info` after #10788 removes the branch of `ChatterClientId == -2`, to avoid the truncation there.

**Comment by ChillerDragon** [comment]
Thanks
