### PR TITLE
Use member variables for demo player snapshot data, enable use of video recording for each demo player individually

### LINKED ISSUE #7068: Crash in demo slicing background job
Version 17.2.1 64 bit Steam, reported by cyberFighter on Discord.

```
0x00000001401ce8ef: CSnapshotItem::Key() const at src/engine/shared/snapshot.h:23
 (inlined by) GenerateHash at src/engine/shared/snapshot.cpp:178
0x00000001401cf136: CSnapshot::NumItems() const at src/engine/shared/snapshot.h:54
 (inlined by) CSnapshotDelta::CreateDelta(CSnapshot*, CSnapshot*, void*) at src/engine/shared/snapshot.cpp:283
0x00000001401be13b: CDemoRecorder::RecordSnapshot(int, void const*, int) at src/engine/shared/demo.cpp:322
0x00000001401bf4e3: CDemoPlayer::DoTick() at src/engine/shared/demo.cpp:649
0x00000001401bf97c: CDemoPlayer::Update(bool) at src/engine/shared/demo.cpp:1038
0x00000001401bfeb0: CDemoEditor::Slice(char const*, char const*, int, int, bool (*)(void const*, int, void*), void*) at src/engine/shared/demo.cpp:1210
0x000000014002acbf: CDemoEdit::Run() at src/engine/client/demoedit.cpp:25
0x00000001401c3a7e: std::__atomic_base<int>::store(int, std::memory_order) at /usr/x86_64-w64-mingw32/include/c++/12.2.0/bits/atomic_base.h:464
 (inlined by) std::__atomic_base<int>::operator=(int) at /usr/x86_64-w64-mingw32/include/c++/12.2.0/bits/atomic_base.h:356
 (inlined by) CJobPool::RunBlocking(IJob*) at src/engine/shared/jobs.cpp:110
 (inlined by) CJobPool::WorkerThread(void*) at src/engine/shared/jobs.cpp:64
0x00000001401dd5ca: CWindowsComLifecycle::~CWindowsComLifecycle() at src/base/system.cpp:4597
 (inlined by) thread_run at src/base/system.cpp:865
```

### PR DESCRIPTION
**Pull request by Robyt3**
Use member instead of static variables for demo player snapshot data. The static variables would otherwise cause issues when multiple demo players are playing at the same time, especially demo players used in background jobs for replay demo slicing. This hopefully closes #7068.

Previously all demo players checked `IVideo::Current` to render a video, which would cause issues when rendering a demo while a demo slicing background job is running. Now video rendering can be toggled for each demo player individually and is only enabled for the main demo player.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]

File: src/engine/shared/demo.cpp [hunk 1]
```diff
@@ -625,9 +623,8 @@ void CDemoPlayer::DoTick()
 		if(ChunkType == CHUNKTYPE_DELTA)
 		{
 			// process delta snapshot
-			static char s_aNewsnap[CSnapshot::MAX_SIZE];
-			CSnapshot *pNewsnap = (CSnapshot *)s_aNewsnap;
-			DataSize = m_pSnapshotDelta->UnpackDelta((CSnapshot *)m_aLastSnapshotData, pNewsnap, s_aData, DataSize);
+			CSnapshot *pNewsnap = (CSnapshot *)m_aDeltaSnapshotData;
+			DataSize = m_pSnapshotDelta->UnpackDelta((CSnapshot *)m_aLastSnapshotData, pNewsnap, m_aCurrentSnapshotData, DataSize);
```
Comment (ChillerDragon) [inline src/engine/shared/demo.cpp:627]: Here for me `m_aCurrentSnapshotData` reads like it contains a full snapshot. But it is only a delta. In the next if branch it is a full snapshot. So the same variable is used for two different data formats and is named only after one of them. Imo it would be easier to read the code if there were two variables (`m_aDeltaData`, `m_aSnapData`) or if it would have a more generic term such as `m_aChunkData`

**Review by ChillerDragon — COMMENTED** [review]
Imo this pullrequest did some renames that made it harder to reason about the code

Snap was renamed to delta. But it is still a snap not a delta.

`s_aNewsnap` -> `m_aDeltaSnapshotData`

Data was renamed to snapshot. But it is still a generic buffer that holds either a snapshot or a delta.

`s_aData` -> `m_aCurrentSnapshotData`

File: src/engine/shared/demo.cpp [hunk 2]
```diff
@@ -625,9 +623,8 @@ void CDemoPlayer::DoTick()
 		if(ChunkType == CHUNKTYPE_DELTA)
 		{
 			// process delta snapshot
-			static char s_aNewsnap[CSnapshot::MAX_SIZE];
-			CSnapshot *pNewsnap = (CSnapshot *)s_aNewsnap;
-			DataSize = m_pSnapshotDelta->UnpackDelta((CSnapshot *)m_aLastSnapshotData, pNewsnap, s_aData, DataSize);
+			CSnapshot *pNewsnap = (CSnapshot *)m_aDeltaSnapshotData;
```
[the remark this answers is not in the document]
Comment (Robyt3) [reply src/engine/shared/demo.cpp:626]: So maybe `m_aDeltaUnpackedSnapshotData` if you want to be explicit?

File: src/engine/shared/demo.cpp (hunk 1 above)
Comment (Robyt3) [reply src/engine/shared/demo.cpp:627]: Separate variables seem fine if it makes the code cleaner. Feel free to open a PR with your changes, comments on closed PRs tend to get forgotten.

File: src/engine/shared/demo.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (ChillerDragon) [reply src/engine/shared/demo.cpp:626]: Yea `m_aDeltaUnpackedSnapshotData` works so does `m_aSnapshotData` or `m_aSnapshot` or `m_aNewSnapshot`

Anything that does not read like it is a delta.

File: src/engine/shared/demo.cpp (hunk 1 above)
Comment (ChillerDragon) [reply src/engine/shared/demo.cpp:627]: I prefer `m_aChunkData` over two variables but yea both work.

I have too many prs open already where I am waiting for reviews I will open an issue instead.
