### PR TITLE
HTTP Serverbrowser: Quit faster (fixes #4563)

### LINKED ISSUE #4563: libcurl stop ddnet from quitting
[2022-01-03 21:46:34][client]: disconnecting. reason='unknown'
[2022-01-03 21:46:34][demo_recorder]: Stopped recording
[2022-01-03 21:46:44][http]: https://master4.ddnet.tw/ddnet/15/servers.json failed. libcurl error: Resolving timed out after 10000 milliseconds
[2022-01-03 21:46:50][serverbrowse_http]: found master, url='https://master1.ddnet.tw/ddnet/15/servers.json' time=3477ms
[2022-01-03 21:46:51][serverbrowse_http]: found master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=276ms
[2022-01-03 21:46:51][serverbrowse_http]: determined best master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=276ms

### PR DESCRIPTION
**Pull request by def-**
```
[2022-01-08 09:57:03][serverbrowse_http]: found master, url='https://master1.ddnet.tw/ddnet/15/servers.json' time=54ms
[2022-01-08 09:57:03][client]: disconnecting. reason='unknown'
[2022-01-08 09:57:03][http]: https://master2.ddnet.tw/ddnet/15/servers.json failed. libcurl error: Callback aborted
[2022-01-08 09:57:03][serverbrowse_http]: master chooser aborted
```

Not instantaneous but much faster, depends on how often curl calls the PROGRESSFUNCTION.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by edg-l** [comment]
I had curiosity so i looked up PROGRESSFUNCTION, and it's deprecated since curl 7.32.0, it recommends to use https://curl.se/libcurl/c/CURLOPT_XFERINFOFUNCTION.html instead

**Comment by def-** [comment]
Tried it, it gets called less often than the old PROGRESSFUNCTION, so then the fix here doesn't work anymore. I'd prefer to stay with PROGRESSFUNCTION until it's actually removed (or we find a better way to solve this).

File: src/engine/client/serverbrowser_http.cpp [hunk 1]
```diff
@@ -45,12 +45,15 @@ class CChooseMaster
 	class CJob : public IJob
 	{
 		std::shared_ptr<CData> m_pData;
+		std::unique_ptr<CHead> m_pHead;
```
Comment (Jupeyy) [inline src/engine/client/serverbrowser_http.cpp:48]: are unique_ptrs really safe to use for this purpose
From code it looks like they are created in the job thread, but aborted outside of that thread

Comment (def-) [reply src/engine/client/serverbrowser_http.cpp:48]: As long as they are only stored in a single memory location it's fine.

Comment (Jupeyy) [reply src/engine/client/serverbrowser_http.cpp:48]: I mean thread safe, or is everything in one thread?

**Comment by def-** [comment]
True, should probably lock that.

**Comment by def-** [comment]
Or we could argue that m_pHead is only being assigned to once, same for m_pGet. The only danger would be that Abort() is being called while the job is being destructed already. But we are calling Abort() from the destructor, and m_pJob is not deleted anywhere else, so this seems safe.

**Comment by def-** [comment]
I don't think I understand where the issue is. Can you explain @heinrich5991 ?

**Comment by heinrich5991** [comment]
`CServerBrowserHttp` owns `CChooseMaster` through `m_pChooseMaster`. I assume `CServerBrowserHttp` is destructed on the main thread, it then calls `CChooseMaster::Abort` which in turn looks at `m_pHead` (and `m_pGet`) in an unsynchronized manner.

`m_pHead` and `m_pGet` get assigned in the job background thread of `CChooseMaster::CJob`.

This is a read and a write in two different threads, unsynchronized, as far as I can tell. This would mean that it's a race condition.

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
Looks good to me. The submodules have accidentally been updated.

**Comment by def-** [comment]
Fixed (by rebasing)

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)
