### PR TITLE
Fix clangs recommendation to use '= default' to define a trivial destructor

### LINKED ISSUE #10590: use '= default' to define a trivial destructor
Needed for #10588

```
/home/runner/work/ddnet/ddnet/src/base/logger.h:73:10: error: use '= default' to define a trivial destructor [modernize-use-equals-default,-warnings-as-errors]
   73 |         virtual ~ILogger() {}
      |                 ^          ~~
      |                            = default;
```

Remove the lint or apply the fix?

### PR DESCRIPTION
**Pull request by ChillerDragon**
Closed #10590

### CODE REVIEW

**Comment by ChillerDragon** [comment]
I fixed this using clang. See my hacky shell script that calls clang manually on a per file basis and auto applies the fix.

 ```bash
 #!/bin/bash

ARG_JOBS=1
ARG_BUILDDIR=''
ARG_SKIP=0

read -rd '' CLANG_CONFIG_CONTENT << EOF
Checks: >
  -*,
  modernize-use-equals-default,
EOF

set -eu

log() {
	printf '%s\n' "$1"
}
err() {
	printf '%s\n' "$1" 1>&2
}

usage() {
	cat <<-EOF
	usage: fix_clang_tidy.sh [OPTION..] [build_dir]
	options:
	  -j[jobs]        number of threads (default: 1)
	EOF
}

parse_args() {
	while true
	do
		[ "$#" -eq 0 ] && break
		arg="$1"
		shift

		if [ "${arg::2}" = -j ]
		then
			ARG_JOBS="${arg:2}"
			if [[ ! "$ARG_JOBS" =~ ^[0-9]+$ ]]
			then
				err "error: jobs have to be numeric"
				exit 1
			fi
		elif [ "${arg::1}" = - ]
		then
			if [ "$arg" = "-h" ] && [ "$arg" == --help ]
			then
				usage
				exit 0
			elif [ "$arg" = --skip ]
			then
				ARG_SKIP="$1"
				shift
			else
				err "error: invalid argument '$arg'"
				exit 1
			fi
		elif [ "$ARG_BUILDDIR" = "" ]
		then
			ARG_BUILDDIR="$arg"
		else
			err "error: unexpected argument '$arg'"
			exit 1
		fi
	done
}

parse_args "$@"

build_dir="build-tidy-context"
if [ "$ARG_BUILDDIR" != "" ]
then
	build_dir="$ARG_BUILDDIR"
fi
if [ ! -d "$build_dir" ]
then
	mkdir "$build_dir"
	cd "$build_dir"
	cmake -DCMAKE_BUILD_TYPE=Debug -DDOWNLOAD_GTEST=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..
	make -j"$ARG_JOBS"
	cd ..
fi
# generated code hack
# https://github.com/ddnet/ddnet/issues/8152
mkdir -p src/game/generated
for generated_file in client_data.h client_data7.h
do
	cp "$build_dir/src/game/generated/$generated_file" src/game/generated/
done

if ! CLANG_CONFIG_FILE="$(mktemp /tmp/clang-tidy-XXXXX.yaml)"
then
	err "mktemp failed"
	exit 1
fi
printf '%s' "$CLANG_CONFIG_CONTENT" > "$CLANG_CONFIG_FILE"

restore() {
	log "cleaning up ..."
	rm "$CLANG_CONFIG_FILE"
}
trap restore EXIT

list_code_files() {
	find ./src/ \
		-type f \
		-not \( \
			-path './src/game/mapitems_ex_types.h' -o \
			-path './src/engine/shared/protocol_ex_msgs.h' -o \
			-path './src/engine/shared/teehistorian_ex_chunks.h' -o \
			-path './src/game/client/components/local_server.h' -o \
			-path './src/game/client/components/items.h' -o \
			-path './src/game/client/components/nameplates.h' -o \
			-path './src/game/mapbugs_list.h' -o \
			-path './src/game/tuning.h' -o \
			-path './src/engine/shared/config_variables.h' -o \
			-path './src/engine/shared/websockets.h' -o \
			-path './src/engine/client/keynames.h' -o \
			-path './src/rust-bridge/*' -o \
			-path './src/game/generated/*' -o \
			-path './src/test/*' -o \
			-path './src/android/*' -o \
			-path './src/base/*' -o \
			-path './src/engine/external/*' -o \
			-path './src/tools/*' \) \
		\( \
			-name '*.cpp' -o \
			-name '*.c' -o \
			-name '*.h' \
		\)
}

total="$(list_code_files | wc -l)"

check_file() {
	local source_file="$1"
	local build_dir="$2"
	if ! clang-tidy --fix --config-file="$CLANG_CONFIG_FILE" "$source_file" -p "$build_dir" 2>/dev/null
	then
		# show stderr on error
		clang-tidy --fix --config-file="$CLANG_CONFIG_FILE" "$source_file" -p "$build_dir" || true
	fi
}

export -f check_file

single_thread() {
	local current=0
	list_code_files | while read -r source_file
		do
			current="$((current+1))"
			[ "$current" -lt "$ARG_SKIP" ] && continue

			log "[$current/$total] $source_file"
			check_file "$source_file" "$build_dir"
		done
}

multi_thread_bash() {
	local current=0
	list_code_files | while read -r source_file
		do
			current="$((current+1))"
			[ "$current" -lt "$ARG_SKIP" ] && continue

			log "[$current/$total] $source_file"
			while [ "$(jobs | wc -l)" -ge "$ARG_JOBS" ]
			do
				sleep 0.5
			done
			check_file "$source_file" "$build_dir" &
		done
}

multi_thread_gnu_parallel() {
	if [ ! -x "$(command -v parallel)" ]
	then
		err "error: gnu parallel is not installed"
		exit 1
	fi
	list_code_files |
		parallel \
		--jobs "$ARG_JOBS" \
		--halt soon,fail=1 \
		--eta \
		"check_file {} $build_dir"
}

if [ "$ARG_JOBS" -gt 1 ]
then
	if parallel --version 2>/dev/null | grep -q 'GNU parallel'
	then
		multi_thread_gnu_parallel
	else
		multi_thread_bash
	fi
else
	single_thread
fi
```

When running in single file mode clang dies on unknown types. So not ALL files might have been caught. I sent fixes for 3 files and then rage quitted. #10596, #10597, #10598 I assume there is still a few more I just started to ignore the files with errors.

File: src/game/server/scoreworker.h [hunk 1]
```diff
@@ -227,7 +227,7 @@ class CPlayerData
 	{
 		Reset();
 	}
-	~CPlayerData() {}
+	~CPlayerData() = default;
```
Comment (heinrich5991) [inline src/game/server/scoreworker.h]: I missed this. Why do we explicitly declare a destructor here? Can it just be deleted entirely?

File: src/game/server/scoreworker.h [hunk 2]
```diff
@@ -209,7 +209,7 @@ struct CSqlTeamLoadRequest : ISqlData
 		ISqlData(std::move(pResult))
 	{
 	}
-	virtual ~CSqlTeamLoadRequest(){};
+	virtual ~CSqlTeamLoadRequest() = default;
```
Comment (heinrich5991) [inline src/game/server/scoreworker.h]: Do we need this? I'm not sure about the rules around child classes and destructors.

File: src/game/server/score.h [hunk 3]
```diff
@@ -40,7 +40,7 @@ class CScore
 
 public:
 	CScore(CGameContext *pGameServer, CDbConnectionPool *pPool);
-	~CScore() {}
+	~CScore() = default;
```
Comment (heinrich5991) [inline src/game/server/score.h]: Probably unneeded, too. Can you go over the changes and see which destructors we actually need?

File: src/game/server/scoreworker.h (hunk 2 above)
Comment (ChillerDragon) [reply src/game/server/scoreworker.h]: Clang does not complain when it is missing. So I remove it? @Zwelf do you need it?

File: src/game/server/score.h (hunk 3 above)
Comment (ChillerDragon) [reply src/game/server/score.h]: Removed a bunch of them. Some would cause compilation errors or clang warnings those I kept. Not sure what the exact implications of it is tho. I find it a bit scary. Also might cause some unexpected compilation errors downstream.

**Review by edg-l — APPROVED** [review]

File: src/engine/antibot.h [hunk 4]
```diff
@@ -23,8 +23,6 @@ class IAntibot : public IInterface
 
 	// Commands
 	virtual void ConsoleCommand(const char *pCommand) = 0;
-
-	virtual ~IAntibot(){};
```
Comment (heinrich5991) [inline src/engine/antibot.h:27]: Interface.

File: src/engine/antibot.h [hunk 5]
```diff
@@ -40,8 +38,6 @@ class IEngineAntibot : public IAntibot
 	virtual bool OnEngineClientMessage(int ClientId, const void *pData, int Size, int Flags) = 0;
 	virtual bool OnEngineServerMessage(int ClientId, const void *pData, int Size, int Flags) = 0;
 	virtual bool OnEngineSimulateClientMessage(int *pClientId, void *pBuffer, int BufferSize, int *pOutSize, int *pFlags) = 0;
-
-	virtual ~IEngineAntibot(){};
```
Comment (heinrich5991) [inline src/engine/antibot.h:44]: Interface.

File: src/engine/demo.h [hunk 6]
```diff
@@ -82,7 +82,6 @@ class IDemoPlayer : public IInterface
 		TICK_NEXT, // go to the next tick
 	};
 
-	virtual ~IDemoPlayer() {}
```
Comment (heinrich5991) [inline src/engine/demo.h:85]: Interface.

File: src/engine/demo.h [hunk 7]
```diff
@@ -109,7 +108,6 @@ class IDemoRecorder : public IInterface
 		REMOVE_FILE,
 	};
 
-	virtual ~IDemoRecorder() {}
```
Comment (heinrich5991) [inline src/engine/demo.h:112]: Interface.

File: src/engine/editor.h [hunk 8]
```diff
@@ -8,7 +8,6 @@ class IEditor : public IInterface
 {
 	MACRO_INTERFACE("editor")
 public:
-	virtual ~IEditor() {}
```
Comment (heinrich5991) [inline src/engine/editor.h:11]: Interface.

File: src/engine/favorites.h [hunk 9]
```diff
@@ -26,8 +26,6 @@ class IFavorites : public IInterface
 		bool m_AllowPing;
 	};
 
-	virtual ~IFavorites() {}
```
Comment (heinrich5991) [inline src/engine/favorites.h:29]: Interface.

File: src/engine/ghost.h [hunk 10]
```diff
@@ -19,8 +19,6 @@ class IGhostRecorder : public IInterface
 {
 	MACRO_INTERFACE("ghostrecorder")
 public:
-	virtual ~IGhostRecorder() {}
```
Comment (heinrich5991) [inline src/engine/ghost.h:22]: Interface.

File: src/engine/ghost.h [hunk 11]
```diff
@@ -32,8 +30,6 @@ class IGhostLoader : public IInterface
 {
 	MACRO_INTERFACE("ghostloader")
 public:
-	virtual ~IGhostLoader() {}
```
Comment (heinrich5991) [inline src/engine/ghost.h:35]: Interface.

**Review by heinrich5991 — COMMENTED** [review]
> Removed a bunch of them. Some would cause compilation errors or clang warnings those I kept. Not sure what the exact implications of it is tho. I find it a bit scary. Also might cause some unexpected compilation errors downstream.

Thanks.

Classes declaring virtual functions need a declared virtual default destructor. I marked them in the comments, can you re-add those?

File: src/game/server/scoreworker.h (hunk 2 above)
Comment (Zwelf) [reply src/game/server/scoreworker.h]: No need from my side.

**Comment by ChillerDragon** [comment]
> Classes declaring virtual functions need a declared virtual default destructor. I marked them in the comments, can you re-add those?

Added them back. Why are they needed?

**Comment by Robyt3** [comment]
> > Classes declaring virtual functions need a declared virtual default destructor. I marked them in the comments, can you re-add those?
> 
> Added them back. Why are they needed?

https://stackoverflow.com/a/461224

**Review by Robyt3 — APPROVED** [review]

**Comment by Robyt3** [comment]
Please rebase

**Comment by ChillerDragon2** [comment]
Please rebabe (testing https://github.com/ChillerDragon/rebase-bob)
