### PR TITLE
Fix: Editor can't find tele out (#11854)

### LINKED ISSUE #11854: Editor can't find tele out
```
2026-03-01 09:36:58 I chat: Cammodude: editor cant find a tele 254
2026-03-01 09:37:41 I chat: Cammodude: yeah editor is literally not showing me 254

2026-03-01 09:57:30 I chat: Cammodude: theyre called TO tele
2026-03-01 09:57:38 I chat: Cammodude: and i used the "view" thing in the editor
```

Happens on Map Auto_Maze (https://discord.com/channels/252358080522747904/1477444865410203678)

[Auto_Maze.txt](https://github.com/user-attachments/files/25658894/Auto_Maze.txt)
rename to .map

### PR DESCRIPTION
**Pull request by ProfSapphire**
Fix by removing the type filter and instead matching any tele tile whose m_Number equals the requested number (skipping only unset/zero numbers). Also changed the cycling behavior which should in theory improve it.
Fixes #11854

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)
- [x] I didn't use generative AI to generate more than single-line completions

### CODE REVIEW

**Comment by qxdFox** [comment]
> Fixes https://github.com/ddnet/ddnet/issues/11775

you mean #11854, right?

**Comment by Robyt3** [comment]
The commit message body still references the wrong issue.

**Comment by ProfSapphire** [comment]
> The commit message body still references the wrong issue.

Thanks for spotting that and telling me. It should be correct now.

File: src/game/editor/mapitems/layer_tele.cpp [hunk 1]
```diff
@@ -341,58 +341,86 @@ bool CLayerTele::ContainsElementWithId(int Id, bool Checkpoint) const
...
 void CLayerTele::GetPos(int Number, int Offset, int &TeleX, int &TeleY)
 {
-	int Match = -1;
-	ivec2 MatchPos = ivec2(-1, -1);
 	TeleX = -1;
 	TeleY = -1;
 
-	auto FindTile = [this, &Match, &MatchPos, &Number, &Offset]() {
-		for(int x = 0; x < m_Width; x++)
+	static const int aTypes[] = {
```
Comment (KebsCS) [inline src/game/editor/mapitems/layer_tele.cpp]: Maybe could be just `IsValidTeleTile`

Comment (ProfSapphire) [reply src/game/editor/mapitems/layer_tele.cpp]: Good idea, happy to use it if it covers all tile types including TILE_TELEOUT and TILE_TELECHECKOUT. Could you point me to the function?
Edit: NVM I found it, I'll build with it test and then push.

**Comment by KebsCS** [comment]
Also why didn't it work before? Afaik `IsTeleTileNumberUsedAny` checks for the teles that don't use numbers otherwise they'll show up when number 255 is being searched

**Comment by ProfSapphire** [comment]
> Also why didn't it work before? Afaik `IsTeleTileNumberUsedAny` checks for the teles that don't use numbers otherwise they'll show up when number 255 is being searched

Wait so 255 should also be excluded/skipped? If so I will change that. I'm not entirely sure why it didn't work before tbh I'm guessing it was a mix of the surrounding control flow and state handling so I just rewrote it how I thought it would make sense.

**Comment by ChillerDragon** [comment]
Cool thanks for working on this ❤️

**Comment by KebsCS** [comment]
> Wait so 255 should also be excluded/skipped? 

`IsValidTeleTile && IsTeleTileNumberUsedAny` should be enough

**Comment by ProfSapphire** [comment]
> > Wait so 255 should also be excluded/skipped?
> 
> `IsValidTeleTile && IsTeleTileNumberUsedAny` should be enough

thy will be done 😊

**Comment by ChillerDragon** [comment]
@ProfSapphire thanks! I confirmed this also now finds all tele 2 instances on [BlmapChill](https://github.com/DDNetPP/maps/blob/a839edeb96dc6a894fd954956ad88778031df5a7/BlmapChill.map) which was not the case before.
