### PR TITLE
Fix- Replaced usage of m_ProofBorders and m_MenuProofBorders with enum EProofBorder

### LINKED ISSUE #6609: Use `enum` instead of two `bool`s for editor settings
Combine these two into one enum with three values:

https://github.com/ddnet/ddnet/blob/ac820ce62d2830dfa4d6e148c6da8541bda138d2/src/game/editor/editor.h#L1037-L1038

And combine these two into one enum with three values:

https://github.com/ddnet/ddnet/blob/ac820ce62d2830dfa4d6e148c6da8541bda138d2/src/game/editor/editor.h#L922

https://github.com/ddnet/ddnet/blob/ac820ce62d2830dfa4d6e148c6da8541bda138d2/src/game/editor/editor.h#L1057

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
Changes requested.
closes #6609 

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [x] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
The checklist makes me suspicious, did you test this change?

**Comment by tarunsamanta2k20** [comment]
> The checklist makes me suspicious, did you test this change?



> The checklist makes me suspicious, did you test this change?

m_MenuProofBorders = false;if(m_MenuProofBorders && !m_ShowPicker);  I am not getting how to replace those with enums.

**Comment by Robyt3** [comment]
> `m_MenuProofBorders = false;`

You can remove the one in `editor.h`. In `popups.cpp` use `m_ProofBorders = PROOF_BORDER_INGAME;`.

> `if(m_MenuProofBorders && !m_ShowPicker)`

Keep the part of the condition that is unrelated to the proof borders unchanged (here `&& !m_ShowPicker`).

`m_MenuProofBorders` being `true` means you need to check for `PROOF_BORDER_MENU`.

**Comment by tarunsamanta2k20** [comment]
@Robyt3 thiose two:

!pEditor->m_MenuProofBorders
pEditor->m_MenuProofBorders

**Comment by Robyt3** [comment]
`if(m_ProofBorders == PROOF_BORDER_MENU && !m_ShowPicker)`

seem more correct

**Comment by tarunsamanta2k20** [comment]
@Robyt3 i am asking for the below line:
if(pEditor->DoButton_MenuItem(&s_ButtonIngame, "Ingame", !pEditor->m_MenuProofBorders, &Button,

**Comment by Robyt3** [comment]
There the bold part should be `pEditor->m_ProofBorders == PROOF_BORDER_INGAME`

File: src/game/editor/popups.cpp [hunk 1]
```diff
@@ -2327,18 +2327,18 @@ CUI::EPopupMenuFunctionResult CEditor::PopupProofMode(void *pContext, CUIRect Vi
...
 	}
 
 	View.HSplitTop(2.0f, nullptr, &View);
 	View.HSplitTop(12.0f, &Button, &View);
 	static int s_ButtonMenu;
-	if(pEditor->DoButton_MenuItem(&s_ButtonMenu, "Menu", pEditor->m_MenuProofBorders, &Button, 0, "These borders represent what will be shown in the menu."))
+	if(pEditor->DoButton_MenuItem(&s_ButtonMenu, "Menu", pEditor->m_ProofBorders == PROOF_BORDER_INGAME, &Button, 0, "These borders represent what will be shown in the menu."))
 	{
-		pEditor->m_MenuProofBorders = true;
+		pEditor->m_ProofBorders = PROOF_BORDER_INGAME;
```
Comment (Robyt3) [inline src/game/editor/popups.cpp:2341]: Use `PROOF_BORDER_MENU`

File: src/game/editor/popups.cpp [hunk 2]
```diff
@@ -2327,18 +2327,18 @@ CUI::EPopupMenuFunctionResult CEditor::PopupProofMode(void *pContext, CUIRect Vi
...
-		pEditor->m_MenuProofBorders = false;
+		pEditor->m_ProofBorders = PROOF_BORDER_INGAME;
 		return CUI::POPUP_CLOSE_CURRENT;
 	}
 
 	View.HSplitTop(2.0f, nullptr, &View);
 	View.HSplitTop(12.0f, &Button, &View);
 	static int s_ButtonMenu;
-	if(pEditor->DoButton_MenuItem(&s_ButtonMenu, "Menu", pEditor->m_MenuProofBorders, &Button, 0, "These borders represent what will be shown in the menu."))
+	if(pEditor->DoButton_MenuItem(&s_ButtonMenu, "Menu", pEditor->m_ProofBorders == PROOF_BORDER_INGAME, &Button, 0, "These borders represent what will be shown in the menu."))
```
Comment (Robyt3) [inline src/game/editor/popups.cpp:2339]: Use `PROOF_BORDER_MENU`

File: src/game/editor/popups.cpp [hunk 3]
```diff
@@ -2327,18 +2327,18 @@ CUI::EPopupMenuFunctionResult CEditor::PopupProofMode(void *pContext, CUIRect Vi
 	CUIRect Button;
 	View.HSplitTop(12.0f, &Button, &View);
 	static int s_ButtonIngame;
-	if(pEditor->DoButton_MenuItem(&s_ButtonIngame, "Ingame", !pEditor->m_MenuProofBorders, &Button, 0, "These borders represent what a player maximum can see."))
+	if(pEditor->DoButton_MenuItem(&s_ButtonIngame, "Ingame", !(pEditor->m_ProofBorders == PROOF_BORDER_INGAME), &Button, 0, "These borders represent what a player maximum can see."))
```
Comment (Robyt3) [inline src/game/editor/popups.cpp:2330]: Remove the negation `!` just use `pEditor->m_ProofBorders == PROOF_BORDER_INGAME`

File: src/game/editor/editor.h [hunk 4]
```diff
@@ -796,8 +796,7 @@ class CEditor : public IEditor
 		m_MouseDeltaWy = 0;
 
 		m_GuiActive = true;
-		m_ProofBorders = false;
-		m_MenuProofBorders = false;
+		m_ProofBorders =  PROOF_BORDER_OFF;
```
Comment (Robyt3) [inline src/game/editor/editor.h:799]: Only one space after `=`

File: src/game/editor/editor.cpp [hunk 5]
```diff
@@ -953,7 +953,7 @@ void CEditor::DoToolbar(CUIRect ToolBar)
 		if(DoButton_Ex(&s_ProofButton, "Proof", m_ProofBorders, &Button, 0, "[ctrl+p] Toggles proof borders. These borders represent what a player maximum can see.", IGraphics::CORNER_L) ||
 			(m_Dialog == DIALOG_NONE && m_EditBoxActive == 0 && Input()->KeyPress(KEY_P) && ModPressed))
 		{
-			m_ProofBorders = !m_ProofBorders;
+			m_ProofBorders =  PROOF_BORDER_OFF;
```
Comment (Robyt3) [inline src/game/editor/editor.cpp:956]: This should still toggle proof borders instead of just turning them off.

If the proof borders are currently off, then set to `PROOF_BORDER_INGAME`. Else set to `PROOF_BORDER_OFF`.

Only one space after `=`.

Comment (tarunsamanta2k20) [reply src/game/editor/editor.cpp:956]: m_ProofBorders = PROOF_BORDER_OFF ? PROOF_BORDER_INGAME : PROOF_BORDER_OFF;

or 

m_ProofBorders = !m_ProofBorders

> This should still toggle proof borders instead of just turning them off.
> 
> If the proof borders are currently off, then set to `PROOF_BORDER_INGAME`. Else set to `PROOF_BORDER_OFF`.
> 
> Only one space after `=`.
Which one should I use?
m_ProofBorders = PROOF_BORDER_OFF ? PROOF_BORDER_INGAME : PROOF_BORDER_OFF;

or 

m_ProofBorders = !m_ProofBorders

Comment (tarunsamanta2k20) [reply src/game/editor/editor.cpp:956]: > This should still toggle proof borders instead of just turning them off.
> 
> If the proof borders are currently off, then set to `PROOF_BORDER_INGAME`. Else set to `PROOF_BORDER_OFF`.
> 
> Only one space after `=`.

Which one should I use?

m_ProofBorders = PROOF_BORDER_OFF ? PROOF_BORDER_INGAME : PROOF_BORDER_OFF;

or 

m_ProofBorders = !m_ProofBorders

Comment (Robyt3) [reply src/game/editor/editor.cpp:956]: `m_ProofBorders = m_ProofBorders == PROOF_BORDER_OFF ? PROOF_BORDER_INGAME : PROOF_BORDER_OFF`

**Comment by Robyt3** [comment]
Also adjust the two usages of `m_ProofBorders` on lines 953 and 2909 in `editor.cpp` please. Use `m_ProofBorders != PROOF_BORDER_OFF` in both cases.

**Comment by Robyt3** [comment]
Thank you for your efforts so far. To fully close the issue there are also the other two bool variables (`m_ShowTileInfo` and `m_ShowTileInfoHex`) that should be replaced with one enum variable.

**Comment by tarunsamanta2k20** [comment]
> Thank you for your efforts so far. To fully close the issue there are also the other two bool variables (`m_ShowTileInfo` and `m_ShowTileInfoHex`) that should be replaced with one enum variable.

@Robyt3 should I remove m_ShowTileHexInfo as well?

File: src/game/editor/popups.cpp [hunk 6]
```diff
@@ -293,21 +293,19 @@ CUI::EPopupMenuFunctionResult CEditor::PopupMenuSettings(void *pContext, CUIRect
...
-			pEditor->m_ShowTileHexInfo = false;
+			pEditor->m_ShowTileInfo = SHOW_TILE_DECIMAL;
 			pEditor->m_ShowEnvelopePreview = SHOWENV_NONE;
 		}
-		if(pEditor->DoButton_ButtonInc(&s_ButtonHex, "Hex", pEditor->m_ShowTileInfo && pEditor->m_ShowTileHexInfo, &Hex, 0, "[ctrl+shift+i] Show tile information in hexadecimal"))
+		if(pEditor->DoButton_ButtonInc(&s_ButtonHex, "Hex", pEditor->m_ShowTileInfo == SHOW_TILE_DECIMAL, &Hex, 0, "[ctrl+shift+i] Show tile information in hexadecimal"))
 		{
-			pEditor->m_ShowTileInfo = true;
-			pEditor->m_ShowTileHexInfo = true;
+			pEditor->m_ShowTileInfo = SHOW_TILE_DECIMAL;
```
Comment (Robyt3) [inline src/game/editor/popups.cpp:308]: `SHOW_TILE_HEXADECIMAL`

File: src/game/editor/popups.cpp [hunk 7]
```diff
@@ -293,21 +293,19 @@ CUI::EPopupMenuFunctionResult CEditor::PopupMenuSettings(void *pContext, CUIRect
...
-		if(pEditor->DoButton_Ex(&s_ButtonDec, "Dec", pEditor->m_ShowTileInfo && !pEditor->m_ShowTileHexInfo, &Dec, 0, "[ctrl+i] Show tile information", IGraphics::CORNER_NONE))
+		if(pEditor->DoButton_Ex(&s_ButtonDec, "Dec", pEditor->m_ShowTileInfo == SHOW_TILE_DECIMAL , &Dec, 0, "[ctrl+i] Show tile information", IGraphics::CORNER_NONE))
 		{
-			pEditor->m_ShowTileInfo = true;
-			pEditor->m_ShowTileHexInfo = false;
+			pEditor->m_ShowTileInfo = SHOW_TILE_DECIMAL;
 			pEditor->m_ShowEnvelopePreview = SHOWENV_NONE;
 		}
-		if(pEditor->DoButton_ButtonInc(&s_ButtonHex, "Hex", pEditor->m_ShowTileInfo && pEditor->m_ShowTileHexInfo, &Hex, 0, "[ctrl+shift+i] Show tile information in hexadecimal"))
+		if(pEditor->DoButton_ButtonInc(&s_ButtonHex, "Hex", pEditor->m_ShowTileInfo == SHOW_TILE_DECIMAL, &Hex, 0, "[ctrl+shift+i] Show tile information in hexadecimal"))
```
Comment (Robyt3) [inline src/game/editor/popups.cpp:306]: `SHOW_TILE_HEXADECIMAL`

File: src/game/editor/popups.cpp [hunk 8]
```diff
@@ -293,21 +293,19 @@ CUI::EPopupMenuFunctionResult CEditor::PopupMenuSettings(void *pContext, CUIRect
 		static int s_ButtonOff = 0;
 		static int s_ButtonDec = 0;
 		static int s_ButtonHex = 0;
-		if(pEditor->DoButton_ButtonDec(&s_ButtonOff, "Off", !pEditor->m_ShowTileInfo, &Off, 0, "Do not show tile information"))
+		if(pEditor->DoButton_ButtonDec(&s_ButtonOff, "Off", pEditor->m_ShowTileInfo == SHOW_TILE_DECIMAL, &Off, 0, "Do not show tile information"))
 		{
-			pEditor->m_ShowTileInfo = false;
+			pEditor->m_ShowTileInfo = SHOW_TILE_DECIMAL;
```
Comment (Robyt3) [inline src/game/editor/popups.cpp:298]: `SHOW_TILE_OFF`

File: src/game/editor/popups.cpp [hunk 9]
```diff
@@ -293,21 +293,19 @@ CUI::EPopupMenuFunctionResult CEditor::PopupMenuSettings(void *pContext, CUIRect
 		static int s_ButtonOff = 0;
 		static int s_ButtonDec = 0;
 		static int s_ButtonHex = 0;
-		if(pEditor->DoButton_ButtonDec(&s_ButtonOff, "Off", !pEditor->m_ShowTileInfo, &Off, 0, "Do not show tile information"))
+		if(pEditor->DoButton_ButtonDec(&s_ButtonOff, "Off", pEditor->m_ShowTileInfo == SHOW_TILE_DECIMAL, &Off, 0, "Do not show tile information"))
```
Comment (Robyt3) [inline src/game/editor/popups.cpp:296]: `SHOW_TILE_OFF`

File: src/game/editor/editor.h [hunk 10]
```diff
@@ -838,7 +837,7 @@ class CEditor : public IEditor
 		m_PreventUnusedTilesWasWarned = false;
 		m_AllowPlaceUnusedTiles = 0;
 		m_BrushDrawDestructive = true;
-		m_ShowTileHexInfo = false;
+		m_ShowTileInfo = SHOW_TILE_OFF;
```
Comment (Robyt3) [inline src/game/editor/editor.h:840]: Remove this line. The same initialization is already above.

File: src/game/editor/editor.cpp [hunk 11]
```diff
@@ -889,26 +889,26 @@ void CEditor::DoToolbar(CUIRect ToolBar)
...
 	if(m_Dialog == DIALOG_NONE && m_EditBoxActive == 0 && Input()->KeyPress(KEY_I) && ModPressed && ShiftPressed)
 	{
-		if(m_ShowTileInfo && m_ShowTileHexInfo)
-			m_ShowTileInfo = false;
-		else if(m_ShowTileInfo)
-			m_ShowTileHexInfo = true;
+		if(m_ShowTileInfo == SHOW_TILE_HEXADECIMAL)
+			m_ShowTileInfo = SHOW_TILE_OFF;
+		else if(m_ShowTileInfo != SHOW_TILE_OFF)
+			m_ShowTileInfo = !SHOW_TILE_OFF;
```
Comment (Robyt3) [inline src/game/editor/editor.cpp:907]: `m_ShowTileInfo = SHOW_TILE_HEXADECIMAL;`

File: src/game/editor/editor.cpp [hunk 12]
```diff
@@ -889,26 +889,26 @@ void CEditor::DoToolbar(CUIRect ToolBar)
...
 		else
 		{
-			m_ShowTileInfo = true;
-			m_ShowTileHexInfo = true;
+			m_ShowTileInfo = !SHOW_TILE_OFF;
+			m_ShowTileInfo = SHOW_TILE_HEXADECIMAL;
 		}
```
Comment (Robyt3) [inline src/game/editor/editor.cpp:912]: The entire if-else-if-else can be replaced with this:

```cpp
m_ShowTileInfo = m_ShowTileInfo == SHOW_TILE_HEXADECIMAL ? SHOW_TILE_OFF : SHOW_TILE_HEXADECIMAL;
```

File: src/game/editor/editor.cpp [hunk 13]
```diff
@@ -889,26 +889,26 @@ void CEditor::DoToolbar(CUIRect ToolBar)
...
-			m_ShowTileHexInfo = false;
-		else if(m_ShowTileInfo)
-			m_ShowTileInfo = false;
+		if(m_ShowTileInfo == SHOW_TILE_HEXADECIMAL)
+			m_ShowTileInfo = SHOW_TILE_OFF;
+		else if(m_ShowTileInfo != SHOW_TILE_OFF)
+			m_ShowTileInfo = SHOW_TILE_OFF;
 		else
-			m_ShowTileInfo = true;
+			m_ShowTileInfo = !SHOW_TILE_OFF;
```
Comment (Robyt3) [inline src/game/editor/editor.cpp:897]: `m_ShowTileInfo = SHOW_TILE_DECIMAL;`

File: src/game/editor/editor.cpp [hunk 14]
```diff
@@ -889,26 +889,26 @@ void CEditor::DoToolbar(CUIRect ToolBar)
 	// handle shortcut for info button
 	if(m_Dialog == DIALOG_NONE && m_EditBoxActive == 0 && Input()->KeyPress(KEY_I) && ModPressed && !ShiftPressed)
 	{
-		if(m_ShowTileInfo && m_ShowTileHexInfo)
-			m_ShowTileHexInfo = false;
-		else if(m_ShowTileInfo)
-			m_ShowTileInfo = false;
+		if(m_ShowTileInfo == SHOW_TILE_HEXADECIMAL)
+			m_ShowTileInfo = SHOW_TILE_OFF;
```
Comment (Robyt3) [inline src/game/editor/editor.cpp:893]: `m_ShowTileInfo = SHOW_TILE_DECIMAL;`

File: src/game/editor/layer_tiles.cpp [hunk 15]
```diff
@@ -651,7 +651,7 @@ void CLayerTiles::ShowInfo()
 			if(m_pTiles[c].m_Index)
 			{
 				char aBuf[64];
-				str_format(aBuf, sizeof(aBuf), m_pEditor->m_ShowTileHexInfo ? "%02X" : "%i", m_pTiles[c].m_Index);
+				str_format(aBuf, sizeof(aBuf), m_pEditor->m_ShowTileInfo == SHOW_TILE_HEXADECIMAL ? "%02X" : "%i", m_pTiles[c].m_Index);
```
Comment (Robyt3) [inline src/game/editor/layer_tiles.cpp:654]: The build fails here because `SHOW_TILE_HEXADECIMAL` is not declared in this scope. Use `CEditor::SHOW_TILE_HEXADECIMAL` instead.

File: src/game/editor/editor.h [hunk 16]
```diff
@@ -1054,7 +1058,14 @@ class CEditor : public IEditor
 	float m_MouseDeltaWx;
 	float m_MouseDeltaWy;
```
[the remark this answers is not in the document]
Comment (tarunsamanta2k20) [reply src/game/editor/editor.h:1060]: @Robyt3 I've tried both options, but the style check is still not working.

[the remark this answers is not in the document]
Comment (tarunsamanta2k20) [reply src/game/editor/editor.h:1060]: src/game/editor/editor.h:1059:23: error: code should be clang-formatted [-Wclang-format-violations]
        float m_MouseDeltaWy;

**Review by Robyt3 — APPROVED** [review]
Thanks!

bors r+
