### PR TITLE
Set a recursion limit for config files

### LINKED ISSUE #7920: Recursively executing config files results in a segmentation fault
Could potentially be mitigated by limiting the recursion limit to like 10 or so.

Reported by @Teero888 on Discord.

### PR DESCRIPTION
**Pull request by MilkeeyCat**
Closes #7920

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/shared/console.cpp [hunk 1]
```diff
@@ -631,11 +631,15 @@ void CConsole::ExecuteLineFlag(const char *pStr, int FlagMask, int ClientId, boo
...
+	// make sure that this isn't being executed already and that recursion limit isn't met
 	for(CExecFile *pCur = m_pFirstExec; pCur; pCur = pCur->m_pPrev)
-		if(str_comp(pFilename, pCur->m_pFilename) == 0)
-			return false;
+	{
+		Count++;
 
+		if(str_comp(pFilename, pCur->m_pFilename) == 0 || Count > FILE_RECURSION_LIMIT)
+			return false;
+	}
```
Comment (heinrich5991) [inline src/engine/shared/console.cpp:642]: Hmmm. Was the detection already precise? Is the recursion limit actually still needed?

**Comment by MilkeeyCat** [comment]
It was checking if it doesn't execute the same file, but https://discord.com/channels/252358080522747904/293493549758939136/1203693355922489424 happens when you execute many files in order

File: src/engine/shared/console.cpp (hunk 1 above)
Comment (KebsCS) [reply src/engine/shared/console.cpp:642]: > Hmmm. Was the detection already precise? Is the recursion limit actually still needed?

Yes, it does crash. This issue was recently reported by [@romashkahh on Discord](https://discord.com/channels/252358080522747904/757720336274948198/1320478597601038427) with a config file that reproduces this

**Review by def- — APPROVED** [review]

**Review by Robyt3 — APPROVED** [review]
