### PR TITLE
A few fixes and improvements to server-side auto demos.

### LINKED ISSUE #7573: `sv_auto_demo_record 1` doesn't do anything.
Due to `DemoRecorder_HandleAutoStart()` being called from `StartRound()`, it won't actually start the demo recording as DDNet doesn't call `StartRound()` anywhere except if you manually do the command `restart`. 

So maybe the starting of a recording should be moved somewhere else?

### PR DESCRIPTION
**Pull request by furo321**
1. Fix `sv_auto_demo_record 1` not starting recording of auto demo. Closes #7573
2. Don't use the same demo recorder for manual and auto demos.
3. Change path of server auto demos from `demos/auto` to `demos/auto/server`. Also match the filenames to be the same as the client auto demos. `autorecord_(date)` -> `(current map)_(date)`

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/server/server.cpp [hunk 1]
```diff
@@ -316,6 +316,7 @@ CServer::CServer()
 	for(int i = 0; i < MAX_CLIENTS; i++)
 		m_aDemoRecorder[i] = CDemoRecorder(&m_SnapshotDelta, true);
 	m_aDemoRecorder[MAX_CLIENTS] = CDemoRecorder(&m_SnapshotDelta, false);
+	m_aDemoRecorder[MAX_CLIENTS + 1] = CDemoRecorder(&m_SnapshotDelta, false);
```
Comment (Robyt3) [inline src/engine/server/server.cpp:319]: Would be easier to understand if you define separate constants in `server.h` like `RECORDER_MANUAL = MAX_CLIENTS`, `RECORDER_AUTO` and `NUM_RECORDERS`.

File: src/engine/server/server.cpp [hunk 2]
```diff
@@ -963,18 +966,18 @@ void CServer::DoSnapshot()
 	GameServer()->OnPreSnap();
 
 	// create snapshot for demo recording
-	if(m_aDemoRecorder[MAX_CLIENTS].IsRecording())
```
Comment (Robyt3) [inline src/engine/server/server.cpp:966]: Check if either of the demo recorders is recording before creating the demo snapshot.

File: src/engine/server/server.cpp [hunk 3]
```diff
@@ -997,9 +1000,8 @@ void CServer::DoSnapshot()
 			GameServer()->OnSnap(i);
 
 			// finish snapshot
-			char aData[CSnapshot::MAX_SIZE];
 			CSnapshot *pData = (CSnapshot *)aData; // Fix compiler warning for strict-aliasing
-			int SnapshotSize = m_SnapshotBuilder.Finish(pData);
+			SnapshotSize = m_SnapshotBuilder.Finish(pData);
```
Comment (Robyt3) [inline src/engine/server/server.cpp:1004]: The previous variables shouldn't be reused, that seems bug prone.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

**Comment by furo321** [comment]
Thanks, fixed!

**Review by Robyt3 — APPROVED** [review]

**Review by def- — APPROVED** [review]
