### PR TITLE
Fix prediction when player has no current weapon

### LINKED ISSUE #11524: Having no weapon with antiping still displays the last equipped weapon
This also messes with prediction, not really important for DDNet but some modded servers allow no weapon

antiping on:

Image

antiping off:

Image

### PR DESCRIPTION
**Pull request by qxdFox**
Somewhere between 18.5 and now (19.7) there was an update to be able to have no weapon visually but prediction wasn't updated

closes #11524 

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)
- [x] I didn't use generative AI to generate more than single-line completions

### CODE REVIEW

File: src/game/client/prediction/entities/character.cpp [hunk 1]
```diff
@@ -1433,11 +1433,10 @@ void CCharacter::Read(CNetObj_Character *pChar, CNetObj_DDNetCharacter *pExtende
 
 	// set the current weapon
 	if(pChar->m_Weapon >= 0 && pChar->m_Weapon != WEAPON_NINJA)
-	{
 		m_Core.m_aWeapons[pChar->m_Weapon].m_Ammo = (GameWorld()->m_WorldConfig.m_InfiniteAmmo || pChar->m_Weapon == WEAPON_HAMMER) ? -1 : pChar->m_AmmoCount;
-		if(pChar->m_Weapon != m_Core.m_ActiveWeapon)
-			SetActiveWeapon(pChar->m_Weapon);
-	}
+
+	if(pChar->m_Weapon != m_Core.m_ActiveWeapon)
```
Comment (KebsCS) [inline src/game/client/prediction/entities/character.cpp]: This removes the guard against `pChar->m_Weapon != WEAPON_NINJA`

Just `pChar->m_Weapon >= -1` should be fine

**Comment by KebsCS** [comment]
Referenced PR https://github.com/ddnet/ddnet/pull/9230

File: src/game/client/prediction/entities/character.cpp (hunk 1 above)
Comment (qxdFox) [reply src/game/client/prediction/entities/character.cpp]: wouldn't that cause `m_Core.m_aWeapons[pChar->m_Weapon].m_Ammo` to go out of bounds?

Comment (KebsCS) [reply src/game/client/prediction/entities/character.cpp]: You're right, now looks good
