### PR TITLE
Fix legacy serverinfo with reserved slots and num_players > 15 (fixes #3678)

### LINKED ISSUE #3678: Legacy serverinfo does not work with reserved slots, if num_players > 15
Claims to have max_clients=15, but sends more than 15 clients:
```json
{
  "max_clients": 15,
  "max_players": 15,
  "passworded": false,
  "game_type": "DDraceNetwork",
  "name": "DDNet Turkey - Novice [19/64]",
  "map": {
    "name": "Multeasymap"
  },
  "version": "0.6.4, 15.3.1",
  "clients": [
    {
      "name": "BadGirl",
      "clan": "",
      "country": 792,
      "score": -9999,
      "is_player": true
    },
    {
      "name": "Faymir",
      "clan": "קųlsє",
      "country": 854,
      "score": -774,
      "is_player": true
    },
    {
      "name": "Fblexon半神",
      "clan": "bf",
      "country": -1,
      "score": -2128,
      "is_player": true
    },
    {
      "name": "Gokalpguneer",
      "clan": "",
      "country": 792,
      "score": -2795,
      "is_player": true
    },
    {
      "name": "Name01",
      "clan": "",
      "country": -1,
      "score": -2615,
      "is_player": true
    },
    {
      "name": "Puern",
      "clan": "",
      "country": -1,
      "score": -606,
      "is_player": true
    },
    {
      "name": "Revenant",
      "clan": "",
      "country": -1,
      "score": -9999,
      "is_player": true
    },
    {
      "name": "Sereq",
      "clan": "",
      "country": -1,
      "score": -9999,
      "is_player": true
    },
    {
      "name": "[D] Fblexon半",
      "clan": "",
      "country": -1,
      "score": -9999,
      "is_player": true
    },
    {
      "name": "[D] Name01",
      "clan": "",
      "country": -1,
      "score": -9999,
      "is_player": true
    },
    {
      "name": "[D] Revenant",
      "clan": "",
      "country": -1,
      "score": -9999,
      "is_player": true
    },
    {
      "name": "[D] xBalex",
      "clan": "",
      "country": -1,
      "score": -9999,
      "is_player": true
    },
    {
      "name": "ben10_e_bom",
      "clan": "",
      "country": -1,
      "score": -9999,
      "is_player": true
    },
    {
      "name": "word.exe GhOsT.",
      "clan": "",
      "country": -1,
      "score": -1701,
      "is_player": true
    },
    {
      "name": "xBalex",
      "clan": "B-F",
      "country": 792,
      "score": -9999,
      "is_player": true
    },
    {
      "name": "❥Heda!",
      "clan": "",
      "country": -1,
      "score": -9999,
      "is_player": true
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/server/server.cpp [hunk 1]
```diff
@@ -1864,16 +1867,15 @@ void CServer::CacheServerInfo(CCache *pCache, int Type, bool SendClients)
...
 		if(PlayerCount > ClientCount)
 			PlayerCount = ClientCount;
 	}
 
 	ADD_INT(p, PlayerCount); // num players
-	ADD_INT(p, maximum(MaxClients - maximum(g_Config.m_SvSpectatorSlots, g_Config.m_SvReservedSlots), PlayerCount)); // max players
+	ADD_INT(p, maximum(MaxClientsProtocol, maximum(MaxClients - maximum(g_Config.m_SvSpectatorSlots, g_Config.m_SvReservedSlots), PlayerCount))); // max players
 	ADD_INT(p, ClientCount); // num clients
-	ADD_INT(p, maximum(MaxClients - g_Config.m_SvReservedSlots, ClientCount)); // max clients
+	ADD_INT(p, maximum(MaxClientsProtocol, maximum(MaxClients - g_Config.m_SvReservedSlots, ClientCount))); // max clients
```
Comment (heinrich5991) [inline src/engine/server/server.cpp:1878]:
```suggestion
	ADD_INT(p, minimum(MaxClientsProtocol, maximum(MaxClients - g_Config.m_SvReservedSlots, ClientCount))); // max clients
```

I think the outer `maximum` should be `minimum`. It should use the smaller of MaxClientsProtocol (16) and the actual number of clients.

Comment (def-) [reply src/engine/server/server.cpp]: Done

**Comment by heinrich5991** [comment]
bors r+

Thanks.
