### PR TITLE
Fix ddnet ex snap item registration (closed #8271)

### LINKED ISSUE #8271: The first snapshot the server sends contains unregistered ddnet ex items
Commenting this line out or turning on debug mode shows errors on the first connection to a server.
After reconnect they are gone.

https://github.com/ddnet/ddnet/blob/c22ba00b59b8a4f9e4dd7e36d5a76fbad4a18899/src/engine/client/client.cpp#L2003

```
./DDNet-Server
./DDNet "debug 1;connect localhost"
```

Prints this one first connect if the client connects again the errors are gone

```
2024-04-27 15:44:57 D client: dropped weird object '(out of range)' (32767), failed on '(type out of range)'
2024-04-27 15:44:57 D client: dropped weird object '(out of range)' (32766), failed on '(type out of range)'
2024-04-27 15:44:57 D client: dropped weird object '(out of range)' (32765), failed on '(type out of range)'
2024-04-27 15:44:57 D client: dropped weird object '(out of range)' (32764), failed on '(type out of range)'
2024-04-27 15:44:57 D client: dropped weird object '(out of range)' (32764), failed on '(type out of range)'
2024-04-27 15:44:57 D client: dropped weird object '(out of range)' (32764), failed on '(type out of range)'
2024-04-27 15:44:57 D client: dropped weird object '(out of range)' (32764), failed on '(type out of range)'
2024-04-27 15:44:57 D client: dropped weird object '(out of range)' (32764), failed on '(type out of range)'
2024-04-27 15:44:57 D client: dropped weird object '(out of range)' (32764), failed on '(type out of range)'
```

The snapshot dump shows that the ddnet ex items are not registered yet. That seems to be some kind of race condition.

Here the first snapshot the server sends

```
2024-04-27 15:48:10 I snapshot: data_size=452 num_items=14                                                                                                                                                                                                                                                                                                                                                                                                                                  
2024-04-27 15:48:10 I snapshot:         type=6 id=0                                                                                                                                                                                                                                                                                                                                                                                                                                         
2024-04-27 15:48:10 I snapshot:                   0            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:                   1            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:                   2            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:                   3            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:                   4            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:                   5            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:                   6            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:                   7            1        00000001                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:         type=32767 id=0                                                                                                                                                                                                                                                                                                                                                                                                                                     
2024-04-27 15:48:10 I snapshot:                   0    247983155        0ec7ec33                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:                   1            9        00000009                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 15:48:10 I snapshot:                   2           64        00000040                                                                                                                                                                                                                                                                                                                                                                                                            
[..] 
```

It uses for example ``type=32767 id=0`` without ever registering `` type=0 id=32767``
Every snapshot after that is correct. Even for newly connected clients.

This is how the first snap looks like that the second client connecting to the server gets. It has the correct uuid register items in the beginning of the snapshot

```
2024-04-27 15:50:28 I snapshot: data_size=520 num_items=17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
2024-04-27 15:50:28 I snapshot:         type=0 id=32767                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
2024-04-27 15:50:28 I snapshot:                   0  -1824658838        933dea6a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   1   -629591830        da7930ea                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   2  -1450210576        a98f8af0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   3    914991429        3689a945                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:         type=0 id=32766                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
2024-04-27 15:50:28 I snapshot:                   0    583701389        22ca938d                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   1    327171627        13803e2b                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   2  -1636052395        9e7bd255                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   3  -1901674991        8ea6be11                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:         type=0 id=32765                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
2024-04-27 15:50:28 I snapshot:                   0   1993229659        76ce455b                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   1   -102024632        f9eb3a48                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   2  -1378361269        add7e04b                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   3  -1810037668        941d045c                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:         type=0 id=32764                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
2024-04-27 15:50:28 I snapshot:                   0   -362919343        ea5e4a51                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   1   1492858500        58fb3684                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   2  -1763385134        96e4e0d2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   3   1744095845        67f4ca65                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:         type=6 id=0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
2024-04-27 15:50:28 I snapshot:                   0            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   1            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   2            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   3            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   4            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   5            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   6            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   7            1        00000001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:         type=32767 id=0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
2024-04-27 15:50:28 I snapshot:                   0    247983155        0ec7ec33                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   1            9        00000009                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 15:50:28 I snapshot:                   2           64        00000040                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
[..]
```

### PR DESCRIPTION
**Pull request by ChillerDragon**
The problem was that the ddnet ex items would be registered when the snapshot builder was initialized. So it checked which ddnet ex items have been used already and then register those uuids. But then all new ddnet ex items that will be added to this snap are not registered. This way the registration is always lacking one snap behind. This could cause some nasty to debug off by one snap errors that are also rare because this only happens for ddnet ex items that were not used by the server before.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by ChillerDragon** [comment]
I don't like that the uuids are now registered at the end of the snap. That could probably fixed with some mem_copy or similar to insert snap items in the beginning instead of append to the end. But it seems to be working at the end too. Snap order does matter sometimes especially in this case.

**Review by Robyt3 — APPROVED** [review]

**Comment by ChillerDragon** [comment]
@Robyt3 are you sure that adding an ddnet ex item to the snap before its registration item is working correctly? Because I am not.

**Review by Robyt3 — CHANGES_REQUESTED** [review]
Hmm, seems like this causes issues when the snapshot is full, because then the ex-items are dropped first.

To test, use `sv_map dm2; tune grenade_fire_delay 0; tune grenade_speed 0; tune grenade_lifetime 1000` and shoot grenades. Without this changes, the first items to disappear are sounds and explosions. With this changes, the projectiles disappear entirely when the snapshot is full.

**Comment by ChillerDragon** [comment]
> Hmm, seems like this causes issues when the snapshot is full, because then the ex-items are dropped first.
> 
> To test, use `sv_map dm2; tune grenade_fire_delay 0; tune grenade_speed 0; tune grenade_lifetime 1000` and shoot grenades. Without this changes, the first items to disappear are sounds and explosions. With this changes, the projectiles disappear entirely when the snapshot is full.

Snapshot full is bad either way isn't it. But yes I would also like to have the registration in the beginning but for a different reason. I want to make sure that the uuid lookup does not fail because of some code that depends on snap item order.

I just don't see a clean way of inserting snap items in the beginning when the snapshot builder finished.

**Comment by ChillerDragon** [comment]
Okay new idea. I am happy with that one now. So instead of putting all ddnet uuids at the beginning or the end of the snap I put the uuid right before the first item of that type that uses it. The code still has bugs and I have to go. So there is no code pushed yet.

**Comment by ChillerDragon** [comment]
Okay nvm I made it work. But only had time for a quick test. In game looked good. The snap dump looked good too.

```
2024-04-27 17:31:54 I snapshot: data_size=520 num_items=17                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
2024-04-27 17:31:54 I snapshot:         type=6 id=0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
2024-04-27 17:31:54 I snapshot:                   0            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   1            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   2            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   3            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   5            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   6            0        00000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   7            1        00000001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:         type=0 id=32767                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
2024-04-27 17:31:54 I snapshot:                   0  -1824658838        933dea6a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   1   -629591830        da7930ea                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
2024-04-27 17:31:54 I snapshot:                   2  -1450210576        a98f8af0                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   3    914991429        3689a945                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:         type=32767 id=0                                                                                                                                                                                                                                                                                                                                                                                                                                     
2024-04-27 17:31:54 I snapshot:                   0    247983155        0ec7ec33                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1            9        00000009                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   2           64        00000040                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:         type=11 id=0                                                                                                                                                                                                                                                                                                                                                                                                                                        
2024-04-27 17:31:54 I snapshot:                   0  -1008145940        c3e8e9ec                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1   -320474428        ece5f2c4                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   2   -220076049        f2e1e7ef                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   3   -293568512        ee808000                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   4  -1008145940        c3e8e9ec                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   5   -320229718        ece9aeaa                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   6  -2139062272        80808000                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   7           64        00000040                                                                                                                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   8   -403511835        e7f2e5e5                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   9   -286001183        eef3f7e1                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  10   -219905920        f2e48080                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  11  -2139062144        80808080                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  12  -2139062144        80808080                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  13  -2139062272        80808000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  14            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  15      7199301        006dda45                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  16      2345678        0023cace                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:         type=10 id=0                                                                                                                                                                                                                                                                                                                                        
2024-04-27 17:31:54 I snapshot:                   0            1        00000001                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   2            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   3        -9999        ffffd8f1                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:         type=0 id=32766                                                                                                                                                                                                                                                                                                                                     
2024-04-27 17:31:54 I snapshot:                   0    583701389        22ca938d                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1    327171627        13803e2b                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   2  -1636052395        9e7bd255                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   3  -1901674991        8ea6be11                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:         type=32766 id=0                                                                                                                                                                                                                                                                                                                                     
2024-04-27 17:31:54 I snapshot:                   0            1        00000001                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:         type=9 id=0                                                                                                                                                                                                                                                                                                                                         
2024-04-27 17:31:54 I snapshot:                   0         2902        00000b56                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1          784        00000310                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   2          337        00000151                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   3            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   5            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   6            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   7            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   8           -1        ffffffff                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   9            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  10            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  11          784        00000310                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  12          337        00000151                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  13            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  14            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  15            1        00000001                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  16           10        0000000a                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  17           10        0000000a                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  18            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  19            1        00000001                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  20            5        00000005                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                  21            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:         type=0 id=32765                                                                                                                                                                                                                                                                                                                                     
2024-04-27 17:31:54 I snapshot:                   0   1993229659        76ce455b                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1   -102024632        f9eb3a48                                                                            
2024-04-27 17:31:54 I snapshot:                   2  -1378361269        add7e04b                                                                            
2024-04-27 17:31:54 I snapshot:                   3  -1810037668        941d045c                                                                            
2024-04-27 17:31:54 I snapshot:         type=32765 id=0                                                                                                     
2024-04-27 17:31:54 I snapshot:                   0        49152        0000c000                                                                            
2024-04-27 17:31:54 I snapshot:                   1            0        00000000                                                                            
2024-04-27 17:31:54 I snapshot:                   2            2        00000002                                                                            
2024-04-27 17:31:54 I snapshot:                   3            0        00000000                                                                            
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                            
2024-04-27 17:31:54 I snapshot:                   5            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:                   6            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:                   7            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:                   8            1        00000001                                                                              
2024-04-27 17:31:54 I snapshot:                   9            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:         type=0 id=32764                                                                                                       
2024-04-27 17:31:54 I snapshot:                   0   -362919343        ea5e4a51                                                                              
2024-04-27 17:31:54 I snapshot:                   1   1492858500        58fb3684                                                                              
2024-04-27 17:31:54 I snapshot:                   2  -1763385134        96e4e0d2                                                                              
2024-04-27 17:31:54 I snapshot:                   3   1744095845        67f4ca65                                                                              
2024-04-27 17:31:54 I snapshot:         type=32764 id=5                                                                                                       
2024-04-27 17:31:54 I snapshot:                   0         1616        00000650                                                                              
2024-04-27 17:31:54 I snapshot:                   1          272        00000110                                                                              
2024-04-27 17:31:54 I snapshot:                   2            2        00000002                                                                              
2024-04-27 17:31:54 I snapshot:                   3            4        00000004                                                                              
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:         type=32764 id=4                                                                                                       
2024-04-27 17:31:54 I snapshot:                   0         1552        00000610                                                                              
2024-04-27 17:31:54 I snapshot:                   1          272        00000110                                                                              
2024-04-27 17:31:54 I snapshot:                   2            2        00000002                                                                              
2024-04-27 17:31:54 I snapshot:                   3            2        00000002                                                                              
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:         type=32764 id=3                                                                                                       
2024-04-27 17:31:54 I snapshot:                   0         1488        000005d0                                                                              
2024-04-27 17:31:54 I snapshot:                   1          272        00000110                                                                              
2024-04-27 17:31:54 I snapshot:                   2            2        00000002                                                                              
2024-04-27 17:31:54 I snapshot:                   3            3        00000003                                                                              
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:         type=32764 id=2                                                                                                       
2024-04-27 17:31:54 I snapshot:                   0         1424        00000590                                                                              
2024-04-27 17:31:54 I snapshot:                   1          272        00000110                                                                              
2024-04-27 17:31:54 I snapshot:                   2            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:                   3            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:         type=32764 id=1                                                                                                       
2024-04-27 17:31:54 I snapshot:                   0         1392        00000570                                                                              
2024-04-27 17:31:54 I snapshot:                   1          272        00000110                                                                              
2024-04-27 17:31:54 I snapshot:                   2            1        00000001                                                                              
2024-04-27 17:31:54 I snapshot:                   3            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:                   4            0        00000000                                                                              
2024-04-27 17:31:54 I snapshot:         type=32764 id=0                                                                                                       
2024-04-27 17:31:54 I snapshot:                   0         1808        00000710                                                                              
2024-04-27 17:31:54 I snapshot:                   1          240        000000f0                                                                              
2024-04-27 17:31:54 I snapshot:                   2            3        00000003                                                                              
2024-04-27 17:31:54 I snapshot:                   3            5        00000005                                                                              
2024-04-27 17:31:54 I snapshot:                   4            0        00000000     
```

**Comment by heinrich5991** [comment]
It was intentional that extended item types never get dropped from the snap once they were added once. This is to make sure to not generate unnecessary diff traffic for extended item types as they're not expected to change. Can you restore that? It'd also get rid of the boolean array, since you could add all the extended item types in the beginning again.

**Comment by ChillerDragon** [comment]
> It was intentional that extended item types never get dropped from the snap once they were added once. This is to make sure to not generate unnecessary diff traffic for extended item types as they're not expected to change. Can you restore that? It'd also get rid of the boolean array, since you could add all the extended item types in the beginning again.

When you say "extended item types" what are you reffering to? The items with type=0 and uuid as payload? Or the others?
In general I lack some proper wording for the two types of things. Is there anything official? How are those two called?
```
2024-04-27 17:31:54 I snapshot:         type=0 id=32766                                                                                                                                                                                                                                                                                                                                     
2024-04-27 17:31:54 I snapshot:                   0    583701389        22ca938d                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1    327171627        13803e2b                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   2  -1636052395        9e7bd255                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   3  -1901674991        8ea6be11                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:         type=32766 id=0                                                                                                                                                                                                                                                                                                                                     
2024-04-27 17:31:54 I snapshot:                   0            1        00000001                                                                                                                                                                                                                                                                                                            
2024-04-27 17:31:54 I snapshot:                   1            0        00000000   
```
I would call the first one register and the second one ddnet ex. Because the first one registers the type 32766 to be the uuid 
22ca938d-1380-3e2b-9e7b-d2558ea6be11 which is known as [player@netobj.ddnet.tw](https://github.com/ddnet/ddnet/blob/03a0071d2885e13fbcfc5998fe73ebc71751973e/datasrc/network.py#L265-L268). And the second one is the actual ddnet ex object.

Isn't a higher diff the last problem when the snap is full? It dropped important gameplay information and then sends more bytes than it should. Nobody will be bothered by the latter if the former happend. Or do you mean that changing the order of the snap items creates a diff already in normal gameplay when new items get added and removed.

Yea I would be totally fine with adding the snap items in the beginning again. But I do not know how write the code for that.
I did not think the uuids in front of the items using it would be any problem. Now that I think about it I could do a mix. All old known ones are inserted at the top like they used to be. And the ones that are used for the first time in the snap get inserted before they are used.

**Comment by ChillerDragon** [comment]
Okay I did that now @heinrich5991 

> Now that I think about it I could do a mix. All old known ones are inserted at the top like they used to be. And the ones that are used for the first time in the snap get inserted before they are used.

It is mostly like it was before. All loaded ddnet ex items are registered in the beginning. But all that are newly added for the first time are right in front of their corresponding snap item.

So the snapshot for the first connecting client on a fresh server start shows no errors when running with `debug 1` and has no uuids in the beginning yet because the server never loaded them.

```
2024-04-30 16:03:33 I snapshot: data_size=356 num_items=10                                                                                                                                                                                                                                                                                                                                  
2024-04-30 16:03:33 I snapshot:         type=6 id=0                                                                                                                                                                                                                                                                                                                                         
2024-04-30 16:03:33 I snapshot:                   0            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   1            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   2            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   3            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   4            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   5            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   6            0        00000000                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   7            1        00000001                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:         type=0 id=32767                                                                                                                                                                                                                                                                                                                                     
2024-04-30 16:03:33 I snapshot:                   0  -1824658838        933dea6a                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   1   -629591830        da7930ea                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   2  -1450210576        a98f8af0                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   3    914991429        3689a945                                                                                                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:         type=32767 id=0                                                                                                                                                                                                                                                                                                                                     
2024-04-30 16:03:33 I snapshot:                   0    247983155        0ec7ec33                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   1            9        00000009                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   2           64        00000040                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:         type=11 id=0                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   0  -1008145940        c3e8e9ec                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   1   -320474428        ece5f2c4                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   2   -220076049        f2e1e7ef                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   3   -293568512        ee808000                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   4  -1008145940        c3e8e9ec                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   5   -320229718        ece9aeaa                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   6  -2139062272        80808000                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   7           64        00000040                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   8   -403511835        e7f2e5e5                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   9   -286001183        eef3f7e1                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                  10   -219905920        f2e48080                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                  11  -2139062144        80808080                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                  12  -2139062144        80808080                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                  13  -2139062272        80808000                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                  14            0        00000000                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                  15      7199301        006dda45                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                  16      2345678        0023cace                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:         type=10 id=0                                                                                                                                                                                                                            
2024-04-30 16:03:33 I snapshot:                   0            1        00000001                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   1            0        00000000                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   2            0        00000000                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   3        -9999        ffffd8f1                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   4            0        00000000                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:         type=0 id=32766                                                                                                                                                                                                                         
2024-04-30 16:03:33 I snapshot:                   0    583701389        22ca938d                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   1    327171627        13803e2b                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   2  -1636052395        9e7bd255                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:                   3  -1901674991        8ea6be11                                                                                                                                                                                                
2024-04-30 16:03:33 I snapshot:         type=32766 id=0                                                                                                                                                                                                                         
2024-04-30 16:03:33 I snapshot:                   0            1        00000001                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=9 id=0                                            
2024-04-30 16:03:33 I snapshot:                   0          523        0000020b                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1          784        00000310                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2          305        00000131                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   4          128        00000080                                                                                                              
2024-04-30 16:03:33 I snapshot:                   5         -402        fffffe6e                                                                                                              
2024-04-30 16:03:33 I snapshot:                   6            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   7            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   8           -1        ffffffff                                                                                                              
2024-04-30 16:03:33 I snapshot:                   9            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  10            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  11          784        00000310                                                                                                              
2024-04-30 16:03:33 I snapshot:                  12          304        00000130                                                                                                              
2024-04-30 16:03:33 I snapshot:                  13            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  14            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  15            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  16           10        0000000a                                                                                                              
2024-04-30 16:03:33 I snapshot:                  17           10        0000000a                                                                                                              
2024-04-30 16:03:33 I snapshot:                  18            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  19            1        00000001                                                                                                              
2024-04-30 16:03:33 I snapshot:                  20            5        00000005                                                                                                              
2024-04-30 16:03:33 I snapshot:                  21            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=0 id=32765                                                                                                                                       
2024-04-30 16:03:33 I snapshot:                   0   1993229659        76ce455b                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1   -102024632        f9eb3a48                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2  -1378361269        add7e04b                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3  -1810037668        941d045c                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=32765 id=0                                                                                                                                       
2024-04-30 16:03:33 I snapshot:                   0        49152        0000c000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2            2        00000002                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   4            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   5            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   6            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   7            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   8            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   9           -1        ffffffff 
```

The second snap the server sends to that client then has the old order.

```
2024-04-30 16:03:33 I snapshot: data_size=356 num_items=10                                                                                                                                    
2024-04-30 16:03:33 I snapshot:         type=0 id=32767                                                                                                                                       
2024-04-30 16:03:33 I snapshot:                   0  -1824658838        933dea6a                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1   -629591830        da7930ea                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2  -1450210576        a98f8af0                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3    914991429        3689a945                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=0 id=32766                                                                                                                                       
2024-04-30 16:03:33 I snapshot:                   0    583701389        22ca938d                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1    327171627        13803e2b                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2  -1636052395        9e7bd255                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3  -1901674991        8ea6be11                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=0 id=32765                                                                                                                                       
2024-04-30 16:03:33 I snapshot:                   0   1993229659        76ce455b                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1   -102024632        f9eb3a48                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2  -1378361269        add7e04b                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3  -1810037668        941d045c                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=6 id=0                                            
2024-04-30 16:03:33 I snapshot:                   0            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   4            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   5            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   6            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   7            1        00000001                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=32767 id=0                                                                                                                                       
2024-04-30 16:03:33 I snapshot:                   0    247983155        0ec7ec33                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1            9        00000009                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2           64        00000040                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=11 id=0                                           
2024-04-30 16:03:33 I snapshot:                   0  -1008145940        c3e8e9ec                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1   -320474428        ece5f2c4                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2   -220076049        f2e1e7ef                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3   -293568512        ee808000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   4  -1008145940        c3e8e9ec                                                                                                              
2024-04-30 16:03:33 I snapshot:                   5   -320229718        ece9aeaa                                                                                                              
2024-04-30 16:03:33 I snapshot:                   6  -2139062272        80808000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   7           64        00000040                                                                                                              
2024-04-30 16:03:33 I snapshot:                   8   -403511835        e7f2e5e5                                                                                                              
2024-04-30 16:03:33 I snapshot:                   9   -286001183        eef3f7e1                                                                                                              
2024-04-30 16:03:33 I snapshot:                  10   -219905920        f2e48080                                                                                                              
2024-04-30 16:03:33 I snapshot:                  11  -2139062144        80808080                                                                                                              
2024-04-30 16:03:33 I snapshot:                  12  -2139062144        80808080                                                                                                              
2024-04-30 16:03:33 I snapshot:                  13  -2139062272        80808000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  14            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  15      7199301        006dda45                                                                                                              
2024-04-30 16:03:33 I snapshot:                  16      2345678        0023cace                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=10 id=0                                           
2024-04-30 16:03:33 I snapshot:                   0            1        00000001                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3        -9999        ffffd8f1                                                                                                              
2024-04-30 16:03:33 I snapshot:                   4            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=32766 id=0                                                                                                                                       
2024-04-30 16:03:33 I snapshot:                   0            1        00000001                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=9 id=0                                            
2024-04-30 16:03:33 I snapshot:                   0          523        0000020b                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1          784        00000310                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2          305        00000131                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   4          128        00000080                                                                                                              
2024-04-30 16:03:33 I snapshot:                   5         -402        fffffe6e                                                                                                              
2024-04-30 16:03:33 I snapshot:                   6            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   7            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   8           -1        ffffffff                                                                                                              
2024-04-30 16:03:33 I snapshot:                   9            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  10            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  11          784        00000310                                                                                                              
2024-04-30 16:03:33 I snapshot:                  12          304        00000130                                                                                                              
2024-04-30 16:03:33 I snapshot:                  13            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  14            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  15            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  16           10        0000000a                                                                                                              
2024-04-30 16:03:33 I snapshot:                  17           10        0000000a                                                                                                              
2024-04-30 16:03:33 I snapshot:                  18            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                  19            1        00000001                                                                                                              
2024-04-30 16:03:33 I snapshot:                  20            5        00000005                                                                                                              
2024-04-30 16:03:33 I snapshot:                  21            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:         type=32765 id=0                                                                                                                                       
2024-04-30 16:03:33 I snapshot:                   0        49152        0000c000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   1            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   2            2        00000002                                                                                                              
2024-04-30 16:03:33 I snapshot:                   3            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   4            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   5            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   6            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   7            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   8            0        00000000                                                                                                              
2024-04-30 16:03:33 I snapshot:                   9           -1        ffffffff   
```

So it is basically exactly how it was before except it does not have the bug that the uuid register happens one snap delayed. But in that fixed case it is not in the very beginning of the snap. But it is guaranteed to be before the snap item that uses the uuid.

File: src/engine/shared/snapshot.h [hunk 1]
```diff
@@ -149,6 +149,7 @@ class CSnapshotBuilder
 	int m_NumItems;
 
 	int m_aExtendedItemTypes[MAX_EXTENDED_ITEM_TYPES];
+	bool m_aRegisteredExtendedItemTypes[MAX_EXTENDED_ITEM_TYPES];
```
Comment (heinrich5991) [inline src/engine/shared/snapshot.h:152]: This boolean array became unnecessary with the latest changes, no? You always know when you add an item type.

File: src/engine/shared/snapshot.cpp [hunk 2]
```diff
@@ -703,11 +703,10 @@ void CSnapshotBuilder::Init(bool Sixup)
 	m_DataSize = 0;
 	m_NumItems = 0;
 	m_Sixup = Sixup;
-
+	for(auto &RegisteredExtendedItemType : m_aRegisteredExtendedItemTypes)
+		RegisteredExtendedItemType = false;
 	for(int i = 0; i < m_NumExtendedItemTypes; i++)
-	{
 		AddExtendedItemType(i);
-	}
```
Comment (heinrich5991) [inline src/engine/shared/snapshot.cpp:710]: Unnecessary diff.

File: src/engine/shared/snapshot.h (hunk 1 above)
Comment (ChillerDragon) [reply src/engine/shared/snapshot.h:152]: It adds all known ones from previous snaps in the beginning. And all new ones on demand.

To not add them twice if they are already known we have to keep track of the ones that were already added.

File: src/engine/shared/snapshot.cpp [hunk 3]
```diff
@@ -760,12 +765,14 @@ int CSnapshotBuilder::GetExtendedItemTypeIndex(int TypeId)
...
 		if(m_aExtendedItemTypes[i] == TypeId)
 		{
+			AddExtendedItemType(i);
 			return i;
 		}
 	}
 	dbg_assert(m_NumExtendedItemTypes < MAX_EXTENDED_ITEM_TYPES, "too many extended item types");
 	int Index = m_NumExtendedItemTypes;
 	m_aExtendedItemTypes[Index] = TypeId;
+	AddExtendedItemType(m_NumExtendedItemTypes);
```
Comment (heinrich5991) [inline src/engine/shared/snapshot.cpp:775]: > It adds all known ones from previous snaps in the beginning. And all new ones on demand.
> 
> To not add them twice if they are already known we have to keep track of the ones that were already added.

There are exactly three call sites of `AddExtendedItemType`, one here, one where you mentioned and one above. In first two cases where it is called, it is statically known that item type hasn't been added to the snapshot yet. In the last case, it's statically known that the item type has been added already, making the call unnecessary. This means, as far as I understand it, that `m_aRegisteredExtendedItemTypes` is unnecessary.

File: src/engine/shared/snapshot.cpp [hunk 4]
```diff
@@ -743,7 +745,10 @@ int CSnapshotBuilder::GetTypeFromIndex(int Index) const
 
 void CSnapshotBuilder::AddExtendedItemType(int Index)
 {
-	dbg_assert(0 <= Index && Index < m_NumExtendedItemTypes, "index out of range");
+	dbg_assert(0 <= Index && Index <= m_NumExtendedItemTypes, "index out of range");
```
Comment (heinrich5991) [inline src/engine/shared/snapshot.cpp:748]:
```suggestion
	dbg_assert(0 <= Index && Index < m_NumExtendedItemTypes, "index out of range");
```

Please increment `m_NumExtendedItemTypes` first so that we can keep this out-of-bounds assert.

File: src/engine/shared/snapshot.cpp (hunk 3 above)
Comment (ChillerDragon) [reply src/engine/shared/snapshot.cpp]: Ah I finally got it. Thanks to your comment on irc. Fixed :white_check_mark:.

**Comment by ChillerDragon** [comment]
Okay after incorporating all feedback I did a full test again and it works as expected.
The layout of the snapshot still is exactly the same as described [here](https://github.com/ddnet/ddnet/pull/8272#issuecomment-2084661923).

Meaning all snaps that are bug free have the exact same format as on the master branch.
And the snaps with the edge case of new ddnet ex items being used for the first time by the server have the uuid items a bit later in the snap but only for exactly one snap. So no client running with debug on will show any errors anymore.

I tested with CSnapshot::DebugDump() on the client side.
I tested reconnecting.
I looked at the first and second snapshot carefully.
I tested with asan.
I tested recording and playing back demos.
I verified that new ddnet ex items that were added later than the first snap work correctly (spectator info)

image

**Review by heinrich5991 — APPROVED** [review]
Perfect! Thanks.
