### PR TITLE
Fix hidden input when searching in unauthed rcon

### LINKED ISSUE #10903: searching rcon whilst logged out = password stars
Image

### PR DESCRIPTION
**Pull request by SollyBunny**
Closes #10903 

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/components/console.cpp [hunk 1]
```diff
@@ -1196,8 +1196,10 @@ void CGameConsole::OnRender()
 			}
 		}
 
+		const bool Hidden = m_ConsoleType == CONSOLETYPE_REMOTE && Client()->State() == IClient::STATE_ONLINE && !m_RemoteConsole.m_Searching && !Client()->RconAuthed() && (pConsole->m_UserGot || !pConsole->m_UsernameReq);
+		pConsole->m_Input.SetHidden(Hidden);
+
 		// render console input (wrap line)
-		pConsole->m_Input.SetHidden(m_ConsoleType == CONSOLETYPE_REMOTE && Client()->State() == IClient::STATE_ONLINE && !Client()->RconAuthed() && (pConsole->m_UserGot || !pConsole->m_UsernameReq));
```
Comment (Robyt3) [inline src/game/client/components/console.cpp]: This could be made more readable by moving the condition to a member function `IsInputHidden`.

The `SetHidden` call should stay in the code block below the comment.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

File: src/game/client/components/console.cpp (hunk 1 above)
Comment (SollyBunny) [reply src/game/client/components/console.cpp]: sure

File: src/game/client/components/console.cpp [hunk 2]
```diff
@@ -1196,8 +1201,9 @@ void CGameConsole::OnRender()
 			}
 		}
 
+		pConsole->m_Input.SetHidden(pConsole->IsInputHidden());
+
 		// render console input (wrap line)
-		pConsole->m_Input.SetHidden(m_ConsoleType == CONSOLETYPE_REMOTE && Client()->State() == IClient::STATE_ONLINE && !Client()->RconAuthed() && (pConsole->m_UserGot || !pConsole->m_UsernameReq));
```
Comment (ChillerDragon) [inline src/game/client/components/console.cpp:1200]: > The SetHidden call should stay in the code block below the comment.

File: src/game/client/components/console.cpp [hunk 3]
```diff
@@ -892,6 +892,11 @@ void CGameConsole::CInstance::Dump()
 	}
 }
 
+bool CGameConsole::CInstance::IsInputHidden() const
+{
+	return m_Type == CONSOLETYPE_REMOTE && m_pGameConsole->Client()->State() == IClient::STATE_ONLINE && !m_Searching && !m_pGameConsole->Client()->RconAuthed() && (m_UserGot || !m_UsernameReq);
```
Comment (Robyt3) [inline src/game/client/components/console.cpp]: I forgot to mention, I also meant rewriting this condition to make it more readable, either by returning `false` early or by splitting it over multiple lines.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

File: src/game/client/components/console.cpp (hunk 2 above)
Comment (SollyBunny) [reply src/game/client/components/console.cpp:1200]: oops

**Comment by ChillerDragon** [comment]
I hate to be this annoying. But we are all online so it should be fast. @SollyBunny looks like the order of methods is different in the header and the source file. I find this a bit odd.

**Comment by ChillerDragon** [comment]
Amazing thanks

**Review by Robyt3 — APPROVED** [review]
