### PR TITLE
reintroduce shotgun bug

### LINKED ISSUE #5258: We somehow fixed the shotgun bug -> reintroduce it?
probably introduced by https://github.com/ddnet/ddnet/commit/6b497afba497c4e61d7d6d9940d63c97533917a3

we could check if it was hitting a player or a block...

### PR DESCRIPTION
**Pull request by C0D3D3V**
fixes #5258
bug got fixed by the math changes in https://github.com/ddnet/ddnet/commit/68bcd21eff9fbace8605eec8122f860499e03c21

This fix introduces a hard coded velocity that the player would get like before. (It could be that this has slightly other behaviour, because before the produced NaN values where converted to ints in CCharacterCore::Quantize (so some other logic may be confronted with the NaN values before), but it should most likely not be noticeable because it is fast enough)

We could now make this bug optional, by adding it to our mapbugs, or adding a server setting for it.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/prediction/entities/laser.cpp [hunk 1]
```diff
@@ -26,6 +26,7 @@ CLaser::CLaser(CGameWorld *pGameWorld, vec2 Pos, vec2 Direction, float StartEner
 
 bool CLaser::HitCharacter(vec2 From, vec2 To)
 {
+	static const vec2 StackedLaserShotgunBugSpeed = vec2(-2147483648.0f, -2147483648.0f);
```
Comment (def-) [inline src/game/client/prediction/entities/laser.cpp:29]: oh well... This is slightly crazy but I guess we need to keep physics the same

**Comment by def-** [comment]
> (It could be that this has slightly other behaviour, because before the produced NaN values where converted to ints in CCharacterCore::Quantize (so some other logic may be confronted with the NaN values before), but it should most likely not be noticeable because it is fast enough)

Could we print out the exact velocities that we got before with the undefined behavior and our gcc compiler and check that it's identical?

**Comment by C0D3D3V** [comment]
I did check it, thats where I got the values from.
grafik
grafik

But I did not check if any other logic uses the NaN values before CCharacterCore::Quantize gets called

**Comment by def-** [comment]
you could check with ubsan, it would tell you where the nan is used if you can reproduce the tricks.

bors r+

**Comment by C0D3D3V** [comment]
I have checked with ubsan, it indeed tells me the other uses. The only other use is in CCollision::MoveBox, but because the vel is nan, nothing is moved. Only after CCharacterCore::Quantize the player is moved. 
grafik

So the only change to the physics before is probably that the player gets 1 tick earlier moved, I think that is acceptable.
