### PR TITLE
Fix preinputs not being reset

### LINKED ISSUE #10477: players look like the client tries to predict non-existent movement
reported by me on discord: 
> did we alter prediction in any way?
> tees look weird on latest master
> they look like the client tries to predict movement on non-moving tees

https://github.com/user-attachments/assets/cd55e22c-e4c6-4c12-ae69-b813deb9866f

not sure how to reproduce, but `Souly` and `Pioooooo` reported that they had the same issue.

### PR DESCRIPTION
**Pull request by KebsCS**
Fixes #10477

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/gameclient.h [hunk 1]
```diff
@@ -481,7 +481,7 @@ class CGameClient : public IGameClient
 		CNetObj_Character m_Snapped;
 		CNetObj_Character m_Evolved;
 
-		CNetMsg_Sv_PreInput m_PreInput[200];
+		CNetMsg_Sv_PreInput m_PreInputs[200];
```
Comment (Robyt3) [inline src/game/client/gameclient.h]: `m_aPreInputs`

**Review by Robyt3 — CHANGES_REQUESTED** [review]
