### PR TITLE
Fix ninja old velocity not being clamped

### LINKED ISSUE #11072: Ninja + shotgun bug
[(Reported by ZChuanY on Discord)](https://discord.com/channels/252358080522747904/757720336274948198/1426582993690165320)

There's a gamebreaking bug right now that is very abusable.

https://github.com/user-attachments/assets/dee1794d-11bc-4a8d-90e5-56cfbea39735

As seen in the video, 2 tees are enough, so one player can replicate this very easily with dummy and deepfly bind:

1. One tee should have shotgun, the other one is ninja.
2. Shotgun tee must have strong over the ninja tee.
3. Both tees should be inside eachother.
4. Shotgun bug needs to be performed at the same time ninja presses fire button while aiming to the ground.

It doesn't only work with teleports arranged like in the video, but also on any "open map" (or that has open boundaries like "Sunny Side Up" spawn) and it causes connection problems to any player in the server for about 3-5 seconds.

### PR DESCRIPTION
**Pull request by sjrc6**
fixes #11072

When ninja runs out the tee's velocty is set to old velocity stored at the start of ninja, but this happens in HandleWeapon() which is after PreTick() so we don't clamp the velocity before MoveBox() happens, then MoveBox() runs a ~2 billion iteration loop.

The MoveBox() in HandleNinja isn't affected by this because it just sets your speed to fixed value.

The reason the normal shotgun bug doesn't have this lag is because the velocity gets clamped to 6000 before MoveBox() happens, so you never actually move faster than 6000.

This doesn't change any physics because there aren't any other situations where you get over 6000 speed so we can safely clamp velocity to 6000 anywhere at any time. 

You could put this in a different place, but putting it here also fixes the stored velocity being negative when it overflows the int. (that's why the reproduction requires the ninja tee to look down, so the negative stored velocity moves you up) 

See discord for long explanation 
https://discord.com/channels/252358080522747904/293493549758939136/1427568007290552382

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Please increase teehistorian minor version for physics changes.

**Comment by sjrc6** [comment]
> Please increase teehistorian minor version for physics changes.

Done

> @sjrc6 Could we also add a comment shortly explaining what this part of the code does, or why the magic number 6000, so someone doesn't have to dig up this pr?
E.g. prevent overflow that causes server lag with shotgun bug+ninja

Done

File: src/game/client/prediction/entities/character.cpp [hunk 1]
```diff
@@ -450,7 +450,10 @@ void CCharacter::FireWeapon()
 
 		m_Core.m_Ninja.m_ActivationDir = Direction;
 		m_Core.m_Ninja.m_CurrentMoveTime = g_pData->m_Weapons.m_Ninja.m_Movetime * GameWorld()->GameTickSpeed() / 1000;
-		m_Core.m_Ninja.m_OldVelAmount = length(m_Core.m_Vel);
+
+		// clamp to prevent massive MoveBox calculation lag with SG bug
+		float VelocityLength = length(m_Core.m_Vel);
+		m_Core.m_Ninja.m_OldVelAmount = std::clamp(VelocityLength, 0.0f, 6000.0f);
```
Comment (heinrich5991) [inline src/game/client/prediction/entities/character.cpp]: Same as below.

File: src/game/server/entities/character.cpp [hunk 2]
```diff
@@ -611,7 +611,10 @@ void CCharacter::FireWeapon()
 
 		m_Core.m_Ninja.m_ActivationDir = Direction;
 		m_Core.m_Ninja.m_CurrentMoveTime = g_pData->m_Weapons.m_Ninja.m_Movetime * Server()->TickSpeed() / 1000;
-		m_Core.m_Ninja.m_OldVelAmount = length(m_Core.m_Vel);
+
+		// clamp to prevent massive MoveBox calculation lag with SG bug
+		float VelocityLength = length(m_Core.m_Vel);
+		m_Core.m_Ninja.m_OldVelAmount = std::clamp(VelocityLength, 0.0f, 6000.0f);
```
Comment (heinrich5991) [inline src/game/server/entities/character.cpp]:
```suggestion
		// clamp to prevent massive MoveBox calculation lag with shotgun bug
		m_Core.m_Ninja.m_OldVelAmount = std::clamp(length(m_Core.m_Vel), 0.0f, 6000.0f);
```
(suggestion, not needed for merge)

**Comment by heinrich5991** [comment]
Oh, please include your nice PR description in the commit message. The commit message is available when `git blame`-ing, the PR description is not.

File: src/game/server/entities/character.cpp (hunk 2 above)
Comment (sjrc6) [reply src/game/server/entities/character.cpp]: sure

**Comment by sjrc6** [comment]
> Oh, please include your nice PR description in the commit message. The commit message is available when `git blame`-ing, the PR description is not.

Sure

**Review by Robyt3 — APPROVED** [review]
