### PR TITLE
Fix AFK when timing out

### LINKED ISSUE #7755: Set Players Into AFK State During Timeout Protection Period
Some players don't immediately try to reconnect to make use of the timeout protection (due to the server being full, for example). The AFK state usually kicks in quite late. So my suggestion is to set all players who are considered timed out by the server into the AFK state early. This should also aid players who managed to stay connected during a DoS attack in determining whom to help and whom to avoid on HH maps.

### PR DESCRIPTION
**Pull request by swarfeya**
This fixes #7755 and #5781

Same code is used here, for the same reasons: https://github.com/ddnet/ddnet/blob/495290e0b2c38029a7913db0945e7ea9e944551d/src/game/server/player.cpp#L722-L737
## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)
image

### CODE REVIEW

File: src/game/server/player.cpp [hunk 1]
```diff
@@ -210,6 +210,8 @@ void CPlayer::Tick()
 	if(Server()->GetNetErrorString(m_ClientID)[0])
 	{
 		SetAfk(true);
+		// Ensure that the AFK state is not reset again automatically
+		m_LastPlaytime = time_get() - time_freq() * g_Config.m_SvMaxAfkTime - 1;
```
Comment (Robyt3) [inline src/game/server/player.cpp:214]: Seems like this would be equivalent to `SetInitialAfk(true)`.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

File: src/game/server/player.cpp (hunk 1 above)
Comment (swarfeya) [reply src/game/server/player.cpp:214]: Sure, will change
The reason I didn't do that before was in case of m_SvMaxAfkTime being 0 it would work differently as in the original version :)

**Review by def- — APPROVED** [review]
