### PR TITLE
Disable gfx_asyncrender_old on macOS (fixes #4435)

### LINKED ISSUE #4435: Crash when moving/resizing window (Steam, macOS)
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               DDNet [5103]
Path:                  /Users/USER/Library/Application Support/Steam/*/DDNet
Identifier:            DDNet
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        steam_osx [3719]
Responsible:           steam_osx [3719]
User ID:               501

Date/Time:             2021-12-10 15:07:14.0097 +0100
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        3AB7E5C0-6273-0D0C-4A67-105D60AF53FE


Time Awake Since Boot: 5000 seconds

System Integrity Protection: enabled

Crashed Thread:        7

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Codes:       0x0000000000000001, 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [5103]

VM Region Info: 0x10 is not in any region.  Bytes before following region: 4375924720
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104d35000-10508a000    [ 3412K] r-x/r-x SM=COW  ...Steam/*/DDNet

Application Specific Information:
dyld4 config: DYLD_INSERT_LIBRARIES=/Users/deen/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamloader.dylib:/Users/deen/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/gameoverlayrenderer.dylib


Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage


Thread 0:: MainThrd Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b400022 __recvfrom + 10
2   DDNet                         	       0x104f801cf CNetClient::Recv(CNetChunk*) + 175
3   DDNet                         	       0x104d6860d CClient::PumpNetwork() + 717
4   DDNet                         	       0x104d6987b CClient::Update() + 3083
5   DDNet                         	       0x104d6ab35 CClient::Run() + 2853
6   DDNet                         	       0x104d6f632 TWMain + 1922
7   dyld                          	       0x20541f4fe start + 462
8   ???                           	               0xc ???

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffef28e4 0x7ff7ffeee000 + 18660
1   runtime                       	    0x7ff7ffeff928 0x7ff7ffeee000 + 71976
2   runtime                       	    0x7ff7fff010a4 0x7ff7ffeee000 + 77988

Thread 2:
0   runtime                       	    0x7ff7fff10814 0x7ff7ffeee000 + 141332

Thread 3:
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b420f66 sem_wait + 10
2   DDNet                         	       0x104f914cb thread_run(void*) + 43
3   libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 4:
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b420f66 sem_wait + 10
2   DDNet                         	       0x104f914cb thread_run(void*) + 43
3   libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 5:
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b420f66 sem_wait + 10
2   DDNet                         	       0x104f914cb thread_run(void*) + 43
3   libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
4   libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 6:
0   runtime                       	    0x7ff7fff10814 0x7ff7ffeee000 + 141332

Thread 7 Crashed:
0   AppleMetalOpenGLRenderer      	       0x11576cf9e GLRResourceList::addResource(GLRResource*) + 388
1   AppleMetalOpenGLRenderer      	       0x1157ad8ec GLDContextRec::prepareResourceForGPUAccess(GLRResource*, unsigned int, PipelineType) + 150
2   AppleMetalOpenGLRenderer      	       0x11577f4a4 GLDContextRec::addRenderPassResources() + 86
3   AppleMetalOpenGLRenderer      	       0x11577f73a GLDContextRec::beginRenderPass() + 602
4   AppleMetalOpenGLRenderer      	       0x1157997d9 gldRenderVertexArray(GLDContextRec*, unsigned int, unsigned int, int, int, unsigned int, void const*, int, void const*) + 454
5   GLEngine                      	    0x7ffa33a20b3f glDrawElements_ACC_GL3Exec + 389
6   DDNet                         	       0x104d5851b CCommandProcessorFragment_OpenGL3_3::Cmd_RenderQuadLayer(CCommandBuffer::SCommand_RenderQuadLayer const*) + 507
7   DDNet                         	       0x104d4f1cc CCommandProcessorFragment_OpenGL::RunCommand(CCommandBuffer::SCommand const*) + 316
8   DDNet                         	       0x104d5c686 CCommandProcessor_SDL_OpenGL::RunBuffer(CCommandBuffer*) + 102
9   DDNet                         	       0x104d5bec5 CGraphicsBackend_Threaded::ThreadFunc() + 197
10  DDNet                         	       0x104d5efbc void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CGraphicsBackend_Threaded::StartProcessor(CGraphicsBackend_Threaded::ICommandProcessor*)::$_0> >(void*) + 60
11  libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
12  libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 8:: AMCP Logging Spool
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b3fcaf6 semaphore_wait_trap + 10
2   caulk                         	    0x7ff8242e108a caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	    0x7ff8242e0d4e void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 9:: AudioQueue thread
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b3fcaba mach_msg_trap + 10
2   CoreFoundation                	    0x7ff81b4ffd51 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff81b4fe40f __CFRunLoopRun + 1329
4   CoreFoundation                	    0x7ff81b4fd809 CFRunLoopRunSpecific + 567
5   SDL2                          	       0x10e72721f audioqueue_thread + 287
6   SDL2                          	       0x10e5a614f SDL_RunThread + 95
7   SDL2                          	       0x10e710cc5 RunThread + 21
8   libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 10:
0   runtime                       	    0x7ff7fff10814 0x7ff7ffeee000 + 141332

Thread 11:
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b3fcaf6 semaphore_wait_trap + 10
2   caulk                         	    0x7ff8242e108a caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	    0x7ff8242e0d4e void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 12:: AQConverterThread
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b3ff506 __psynch_cvwait + 10
2   libAudioToolboxUtility.dylib  	    0x7ff8282cacd4 CADeprecated::CAGuard::Wait() + 54
3   AudioToolbox                  	    0x7ff829277159 AQConverterManager::AQConverterThread::ConverterThreadEntry(void*) + 707
4   libAudioToolboxUtility.dylib  	    0x7ff8282ad067 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 77
5   libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
6   libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 13:: com.apple.audio.IOThread.client
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b3fcaba mach_msg_trap + 10
2   CoreAudio                     	    0x7ff81cfa4f27 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 111
3   CoreAudio                     	    0x7ff81ce33d17 HALC_ProxyIOContext::IOWorkLoop() + 3937
4   CoreAudio                     	    0x7ff81ce327d9 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 63
5   CoreAudio                     	    0x7ff81cffab54 HALB_IOThread::Entry(void*) + 72
6   libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 14:
0   runtime                       	    0x7ff7fff10814 0x7ff7ffeee000 + 141332

Thread 15:: com.apple.NSEventThread
0   ???                           	    0x7ff8ab8be940 ???
1   libsystem_kernel.dylib        	    0x7ff81b3fcaba mach_msg_trap + 10
2   CoreFoundation                	    0x7ff81b4ffd51 __CFRunLoopServiceMachPort + 319
3   CoreFoundation                	    0x7ff81b4fe40f __CFRunLoopRun + 1329
4   CoreFoundation                	    0x7ff81b4fd809 CFRunLoopRunSpecific + 567
5   AppKit                        	    0x7ff81dfbdcec _NSEventThread + 132
6   libsystem_pthread.dylib       	    0x7ff81b439514 _pthread_start + 125
7   libsystem_pthread.dylib       	    0x7ff81b43502f thread_start + 15

Thread 16:
0   runtime                       	    0x7ff7fff10814 0x7ff7ffeee000 + 141332

Thread 17:
0   runtime                       	    0x7ff7fff10814 0x7ff7ffeee000 + 141332

Thread 18:
0   runtime                       	    0x7ff7fff10814 0x7ff7ffeee000 + 141332

Thread 19:
0   runtime                       	    0x7ff7fff10814 0x7ff7ffeee000 + 141332

Thread 20:
0   runtime                       	    0x7ff7fff10814 0x7ff7ffeee000 + 141332


Thread 7 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fb1f49c6cd0  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x00007fb1f49c6cd0  rsi: 0x0000000000001000  rbp: 0x000000030e59cc70  rsp: 0x000000030e59cc40
   r8: 0x000000000000ffff   r9: 0x00007fb1a51268f0  r10: 0x000000000000007f  r11: 0x0000000000000003
  r12: 0x0000000000000007  r13: 0x0000000000000001  r14: 0x0000600003e0c7e0  r15: 0x0000000000000033
  rip: 0x000000011576cf9e  rfl: 0x0000000000000283
 tmp0: 0x000000000000fffe tmp1: 0x000000011577f492 tmp2: 0x00000001157ad8ec


Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff81b3fc000 -     0x7ff81b432fff libsystem_kernel.dylib (*) <12bd6f13-c452-35ee-9069-51befef29f1a> /usr/lib/system/libsystem_kernel.dylib
       0x104d35000 -        0x105089fff DDNet (*) <1e172fad-4a57-35ce-bda8-e2b071fbfe59> /Users/USER/Library/Application Support/Steam/*/DDNet
       0x20541a000 -        0x205485fff dyld (*) <1a6ae033-9438-33c0-8077-988fd885250a> /usr/lib/dyld
    0x7ff7ffeee000 -     0x7ff7fff1dfff runtime (*) <9f5d65be-d8d0-3979-bb05-e651a67e785c> /usr/libexec/rosetta/runtime
    0x7ff81b433000 -     0x7ff81b43efff libsystem_pthread.dylib (*) <29a2750e-f31b-3630-8761-242a6bc3e99e> /usr/lib/system/libsystem_pthread.dylib
       0x115750000 -        0x1157c3fff com.apple.AppleMetalOpenGLRenderer (1.0) <b8e741dc-9dd9-3b34-9dfc-c0fa79a7e67e> /System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/MacOS/AppleMetalOpenGLRenderer
    0x7ffa3395b000 -     0x7ffa33ae9fff GLEngine (*) <b1ce5ca4-6d23-3e9c-8ace-cc817df1e21a> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
    0x7ff8242df000 -     0x7ff824301fff com.apple.audio.caulk (1.0) <c5042b28-9206-337f-bfb2-dc0b37dd8632> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7ff81b480000 -     0x7ff81b980fff com.apple.CoreFoundation (6.9) <afcc752e-074d-340f-890c-263efd2da77f> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x10e4fe000 -        0x10e784fff org.libsdl.SDL2 (2.0.16) <494bd053-376c-3916-b991-e925109786d9> /Users/USER/Library/Application Support/Steam/*/SDL2.framework/Versions/A/SDL2
    0x7ff8282a1000 -     0x7ff8282d0fff libAudioToolboxUtility.dylib (*) <18c97184-3a6b-3834-8d4a-1c5d10872c53> /usr/lib/libAudioToolboxUtility.dylib
    0x7ff829241000 -     0x7ff82937bfff com.apple.audio.toolbox.AudioToolbox (1.14) <c2f1132b-c012-38e3-a18b-99ca5d2056b1> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7ff81cc7d000 -     0x7ff81d3a2fff com.apple.audio.CoreAudio (5.0) <130e5930-dd35-379f-965e-c760c13b3462> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7ff81de11000 -     0x7ff81ec9dfff com.apple.AppKit (6.9) <dd0028a3-78e3-3a8a-a51b-ddd68123adef> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.8G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG backing stores                 4032K        4 
CG image                           220K       19 
ColorSync                          228K       26 
CoreAnimation                      148K       12 
CoreGraphics                        12K        2 
CoreUI image data                 1716K       14 
Foundation                          32K        2 
Image IO                             4K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           532.3M       87 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         768.0M        8         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3 
Rosetta Arena                     4096K        2 
Rosetta Generic                    816K      201 
Rosetta IndirectBranch            1024K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack               400K       40 
Rosetta Thread Context             400K       40 
SQLite page cache                   64K        1 
STACK GUARD                         36K        9 
Stack                             17.7M       20 
Stack Guard                       56.1M       11 
VM_ALLOCATE                       4212K      103 
VM_ALLOCATE (reserved)              72K        9         reserved VM address space (unallocated)
__DATA                            27.7M      418 
__DATA_CONST                      19.4M      233 
__DATA_DIRTY                      1004K      137 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       702.6M       33 
__OBJC_RO                         81.6M        1 
__OBJC_RW                         3120K        2 
__TEXT                           364.8M      422 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                        5.0G      612 
shared memory                     18.5M       22 
unshared pmap                     10.7M        8 
===========                     =======  ======= 
TOTAL                              8.0G     2522 
TOTAL, minus reserved VM space     6.9G     2522 



-----------
Full Report
-----------

{"app_name":"DDNet","timestamp":"2021-12-10 15:07:16.00 +0100","app_version":"","slice_uuid":"1e172fad-4a57-35ce-bda8-e2b071fbfe59","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"FE6E896A-5862-4E0F-B831-9D90CF5B63A5","name":"DDNet"}
{
  "uptime" : 5000,
  "procLaunch" : "2021-12-10 15:05:55.6546 +0100",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "procStartAbsTime" : 118819542220,
  "coalitionID" : 1882,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-10 15:07:14.0097 +0100",
  "incident" : "FE6E896A-5862-4E0F-B831-9D90CF5B63A5",
  "bug_type" : "309",
  "pid" : 5103,
  "procExitAbsTime" : 120699586171,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "DDNet",
  "procPath" : "\/Users\/USER\/Library\/Application Support\/Steam\/*\/DDNet",
  "parentProc" : "steam_osx",
  "parentPid" : 3719,
  "coalitionName" : "com.valvesoftware.steam",
  "crashReporterKey" : "3AB7E5C0-6273-0D0C-4A67-105D60AF53FE",
  "responsiblePid" : 3719,
  "responsibleProc" : "steam_osx",
  "sip" : "enabled",
  "vmRegionInfo" : "0x10 is not in any region.  Bytes before following region: 4375924720\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      104d35000-10508a000    [ 3412K] r-x\/r-x SM=COW  ...Steam\/*\/DDNet",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000010","rawCodes":[1,16],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000010"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":5103},
  "ktriageinfo" : "VM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\nVM - pmap_enter failed with resource shortage\n",
  "vmregioninfo" : "0x10 is not in any region.  Bytes before following region: 4375924720\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      104d35000-10508a000    [ 3412K] r-x\/r-x SM=COW  ...Steam\/*\/DDNet",
  "asi" : {"dyld":["dyld4 config: DYLD_INSERT_LIBRARIES=\/Users\/deen\/Library\/Application Support\/Steam\/Steam.AppBundle\/Steam\/Contents\/MacOS\/steamloader.dylib:\/Users\/deen\/Library\/Application Support\/Steam\/Steam.AppBundle\/Steam\/Contents\/MacOS\/gameoverlayrenderer.dylib"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 7,
  "threads" : [{"id":73980,"name":"MainThrd","queue":"com.apple.main-thread","frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":16418,"symbol":"__recvfrom","symbolLocation":10,"imageIndex":1},{"imageOffset":2404815,"symbol":"CNetClient::Recv(CNetChunk*)","symbolLocation":175,"imageIndex":2},{"imageOffset":210445,"symbol":"CClient::PumpNetwork()","symbolLocation":717,"imageIndex":2},{"imageOffset":215163,"symbol":"CClient::Update()","symbolLocation":3083,"imageIndex":2},{"imageOffset":219957,"symbol":"CClient::Run()","symbolLocation":2853,"imageIndex":2},{"imageOffset":239154,"symbol":"TWMain","symbolLocation":1922,"imageIndex":2},{"imageOffset":21758,"symbol":"start","symbolLocation":462,"imageIndex":3},{"imageOffset":12,"imageIndex":0}]},{"id":73996,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18660,"imageIndex":4},{"imageOffset":71976,"imageIndex":4},{"imageOffset":77988,"imageIndex":4}]},{"id":74101,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"id":74102,"frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":151398,"symbol":"sem_wait","symbolLocation":10,"imageIndex":1},{"imageOffset":2475211,"symbol":"thread_run(void*)","symbolLocation":43,"imageIndex":2},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74103,"frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":151398,"symbol":"sem_wait","symbolLocation":10,"imageIndex":1},{"imageOffset":2475211,"symbol":"thread_run(void*)","symbolLocation":43,"imageIndex":2},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74104,"frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":151398,"symbol":"sem_wait","symbolLocation":10,"imageIndex":1},{"imageOffset":2475211,"symbol":"thread_run(void*)","symbolLocation":43,"imageIndex":2},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74126,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"triggered":true,"id":74135,"threadState":{"r13":{"value":1},"rflags":{"value":643},"rax":{"value":0},"rosetta":{"tmp2":{"value":4655339756},"tmp1":{"value":4655150226},"tmp0":{"value":65534}},"r14":{"value":105553181329376},"rsi":{"value":4096},"r8":{"value":65535},"rdx":{"value":0},"r10":{"value":127},"r9":{"value":140400955386096},"r15":{"value":51},"rbx":{"value":140402289831120},"r11":{"value":3},"rip":{"value":4655075230},"rbp":{"value":13125667952},"rsp":{"value":13125667904},"r12":{"value":7},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":140402289831120}},"frames":[{"imageOffset":118686,"symbol":"GLRResourceList::addResource(GLRResource*)","symbolLocation":388,"imageIndex":6},{"imageOffset":383212,"symbol":"GLDContextRec::prepareResourceForGPUAccess(GLRResource*, unsigned int, PipelineType)","symbolLocation":150,"imageIndex":6},{"imageOffset":193700,"symbol":"GLDContextRec::addRenderPassResources()","symbolLocation":86,"imageIndex":6},{"imageOffset":194362,"symbol":"GLDContextRec::beginRenderPass()","symbolLocation":602,"imageIndex":6},{"imageOffset":301017,"symbol":"gldRenderVertexArray(GLDContextRec*, unsigned int, unsigned int, int, int, unsigned int, void const*, int, void const*)","symbolLocation":454,"imageIndex":6},{"imageOffset":809791,"symbol":"glDrawElements_ACC_GL3Exec","symbolLocation":389,"imageIndex":7},{"imageOffset":144667,"symbol":"CCommandProcessorFragment_OpenGL3_3::Cmd_RenderQuadLayer(CCommandBuffer::SCommand_RenderQuadLayer const*)","symbolLocation":507,"imageIndex":2},{"imageOffset":106956,"symbol":"CCommandProcessorFragment_OpenGL::RunCommand(CCommandBuffer::SCommand const*)","symbolLocation":316,"imageIndex":2},{"imageOffset":161414,"symbol":"CCommandProcessor_SDL_OpenGL::RunBuffer(CCommandBuffer*)","symbolLocation":102,"imageIndex":2},{"imageOffset":159429,"symbol":"CGraphicsBackend_Threaded::ThreadFunc()","symbolLocation":197,"imageIndex":2},{"imageOffset":171964,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CGraphicsBackend_Threaded::StartProcessor(CGraphicsBackend_Threaded::ICommandProcessor*)::$_0> >(void*)","symbolLocation":60,"imageIndex":2},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74136,"name":"AMCP Logging Spool","frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":2806,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":8330,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":36,"imageIndex":8},{"imageOffset":7502,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":41,"imageIndex":8},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74150,"name":"AudioQueue thread","frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":523601,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":9},{"imageOffset":517135,"symbol":"__CFRunLoopRun","symbolLocation":1329,"imageIndex":9},{"imageOffset":514057,"symbol":"CFRunLoopRunSpecific","symbolLocation":567,"imageIndex":9},{"imageOffset":2265631,"symbol":"audioqueue_thread","symbolLocation":287,"imageIndex":10},{"imageOffset":688463,"symbol":"SDL_RunThread","symbolLocation":95,"imageIndex":10},{"imageOffset":2174149,"symbol":"RunThread","symbolLocation":21,"imageIndex":10},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74151,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"id":74152,"frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":2806,"symbol":"semaphore_wait_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":8330,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":36,"imageIndex":8},{"imageOffset":7502,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":41,"imageIndex":8},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74153,"name":"AQConverterThread","frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":13574,"symbol":"__psynch_cvwait","symbolLocation":10,"imageIndex":1},{"imageOffset":171220,"symbol":"CADeprecated::CAGuard::Wait()","symbolLocation":54,"imageIndex":11},{"imageOffset":221529,"symbol":"AQConverterManager::AQConverterThread::ConverterThreadEntry(void*)","symbolLocation":707,"imageIndex":12},{"imageOffset":49255,"symbol":"CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*)","symbolLocation":77,"imageIndex":11},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74159,"name":"com.apple.audio.IOThread.client","frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":3309351,"symbol":"HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int)","symbolLocation":111,"imageIndex":13},{"imageOffset":1797399,"symbol":"HALC_ProxyIOContext::IOWorkLoop()","symbolLocation":3937,"imageIndex":13},{"imageOffset":1791961,"symbol":"invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)","symbolLocation":63,"imageIndex":13},{"imageOffset":3660628,"symbol":"HALB_IOThread::Entry(void*)","symbolLocation":72,"imageIndex":13},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74183,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"id":74230,"name":"com.apple.NSEventThread","frames":[{"imageOffset":140706006690112,"imageIndex":0},{"imageOffset":2746,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":523601,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":9},{"imageOffset":517135,"symbol":"__CFRunLoopRun","symbolLocation":1329,"imageIndex":9},{"imageOffset":514057,"symbol":"CFRunLoopRunSpecific","symbolLocation":567,"imageIndex":9},{"imageOffset":1756396,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":14},{"imageOffset":25876,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":5},{"imageOffset":8239,"symbol":"thread_start","symbolLocation":15,"imageIndex":5}]},{"id":74231,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"id":74678,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"id":74774,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"id":74775,"frames":[{"imageOffset":141332,"imageIndex":4}]},{"id":74776,"frames":[{"imageOffset":141332,"imageIndex":4}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703585779712,
    "size" : 225280,
    "uuid" : "12bd6f13-c452-35ee-9069-51befef29f1a",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4375924736,
    "size" : 3493888,
    "uuid" : "1e172fad-4a57-35ce-bda8-e2b071fbfe59",
    "path" : "\/Users\/USER\/Library\/Application Support\/Steam\/*\/DDNet",
    "name" : "DDNet"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8678121472,
    "size" : 442368,
    "uuid" : "1a6ae033-9438-33c0-8077-988fd885250a",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703127494656,
    "size" : 196608,
    "uuid" : "9f5d65be-d8d0-3979-bb05-e651a67e785c",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703586004992,
    "size" : 49152,
    "uuid" : "29a2750e-f31b-3630-8761-242a6bc3e99e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4654956544,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.AppleMetalOpenGLRenderer",
    "size" : 475136,
    "uuid" : "b8e741dc-9dd9-3b34-9dfc-c0fa79a7e67e",
    "path" : "\/System\/Library\/Extensions\/AppleMetalOpenGLRenderer.bundle\/Contents\/MacOS\/AppleMetalOpenGLRenderer",
    "name" : "AppleMetalOpenGLRenderer",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140712583999488,
    "size" : 1634304,
    "uuid" : "b1ce5ca4-6d23-3e9c-8ace-cc817df1e21a",
    "path" : "\/System\/Library\/Frameworks\/OpenGL.framework\/Versions\/A\/Resources\/GLEngine.bundle\/GLEngine",
    "name" : "GLEngine"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703735607296,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 143360,
    "uuid" : "c5042b28-9206-337f-bfb2-dc0b37dd8632",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703586320384,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5246976,
    "uuid" : "afcc752e-074d-340f-890c-263efd2da77f",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1855.105"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4535083008,
    "CFBundleShortVersionString" : "2.0.16",
    "CFBundleIdentifier" : "org.libsdl.SDL2",
    "size" : 2650112,
    "uuid" : "494bd053-376c-3916-b991-e925109786d9",
    "path" : "\/Users\/USER\/Library\/Application Support\/Steam\/*\/SDL2.framework\/Versions\/A\/SDL2",
    "name" : "SDL2",
    "CFBundleVersion" : "2.0.16"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703802462208,
    "size" : 196608,
    "uuid" : "18c97184-3a6b-3834-8d4a-1c5d10872c53",
    "path" : "\/usr\/lib\/libAudioToolboxUtility.dylib",
    "name" : "libAudioToolboxUtility.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703818846208,
    "CFBundleShortVersionString" : "1.14",
    "CFBundleIdentifier" : "com.apple.audio.toolbox.AudioToolbox",
    "size" : 1290240,
    "uuid" : "c2f1132b-c012-38e3-a18b-99ca5d2056b1",
    "path" : "\/System\/Library\/Frameworks\/AudioToolbox.framework\/Versions\/A\/AudioToolbox",
    "name" : "AudioToolbox",
    "CFBundleVersion" : "1.14"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703611473920,
    "CFBundleShortVersionString" : "5.0",
    "CFBundleIdentifier" : "com.apple.audio.CoreAudio",
    "size" : 7495680,
    "uuid" : "130e5930-dd35-379f-965e-c760c13b3462",
    "path" : "\/System\/Library\/Frameworks\/CoreAudio.framework\/Versions\/A\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "5.0"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703629905920,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15257600,
    "uuid" : "dd0028a3-78e3-3a8a-a51b-ddd68123adef",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113"
  }
],
  "sharedCache" : {
  "base" : 140703582765056,
  "size" : 15215640576,
  "uuid" : "b5084610-afe4-3485-bade-628c4468b057"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.8G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.8G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG backing stores                 4032K        4 \nCG image                           220K       19 \nColorSync                          228K       26 \nCoreAnimation                      148K       12 \nCoreGraphics                        12K        2 \nCoreUI image data                 1716K       14 \nFoundation                          32K        2 \nImage IO                             4K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           532.3M       87 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         768.0M        8         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        256K        3 \nRosetta Arena                     4096K        2 \nRosetta Generic                    816K      201 \nRosetta IndirectBranch            1024K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack               400K       40 \nRosetta Thread Context             400K       40 \nSQLite page cache                   64K        1 \nSTACK GUARD                         36K        9 \nStack                             17.7M       20 \nStack Guard                       56.1M       11 \nVM_ALLOCATE                       4212K      103 \nVM_ALLOCATE (reserved)              72K        9         reserved VM address space (unallocated)\n__DATA                            27.7M      418 \n__DATA_CONST                      19.4M      233 \n__DATA_DIRTY                      1004K      137 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       702.6M       33 \n__OBJC_RO                         81.6M        1 \n__OBJC_RW                         3120K        2 \n__TEXT                           364.8M      422 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                        5.0G      612 \nshared memory                     18.5M       22 \nunshared pmap                     10.7M        8 \n===========                     =======  ======= \nTOTAL                              8.0G     2522 \nTOTAL, minus reserved VM space     6.9G     2522 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000174
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6194416dea7ed64a7812a429"
      },
      "deploymentId" : 240000322
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000081
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61ae8d06da72d16a4beb762e"
      },
      "deploymentId" : 240000290
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,1, BootROM 7429.41.5, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Sep 24 2021 15:49:44 version 20.10.853.23.8.7.106 FWID 01-78e271b2
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: iPhone
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
```

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Ok, it crashes less with this, but after some very agressive window moving I can still get it to crash:
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               DDNet [6227]
Path:                  /Users/USER/*/DDNet
Identifier:            DDNet
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [1317]
Responsible:           iTerm2 [528]
User ID:               501

Date/Time:             2021-12-13 16:39:15.8219 +0100
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Anonymous UUID:        3AB7E5C0-6273-0D0C-4A67-105D60AF53FE


Time Awake Since Boot: 20000 seconds

System Integrity Protection: enabled

Crashed Thread:        7

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00005723a12c6290
Exception Codes:       0x0000000000000001, 0x00005723a12c6290
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [6227]

VM Region Info: 0x5723a12c6290 is not in any region.  Bytes after previous region: 95329503175313  Bytes before following region: 9742576754032
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Application Specific Information:
objc_msgSend() selector name: sampleCount


Thread 0::  Dispatch queue: com.apple.main-thread
0   CoreFoundation                	       0x1b31f7a54 CFBasicHashGetCountOfKey + 0
1   CoreFoundation                	       0x1b3216f0c CFSetContainsValue + 188
2   CoreFoundation                	       0x1b325445c __CFRunLoopDoBlocks + 284
3   CoreFoundation                	       0x1b32534f4 __CFRunLoopRun + 1728
4   CoreFoundation                	       0x1b3252694 CFRunLoopRunSpecific + 600
5   HIToolbox                     	       0x1bbdc8990 RunCurrentEventLoopInMode + 292
6   HIToolbox                     	       0x1bbdc8704 ReceiveNextEventCommon + 552
7   HIToolbox                     	       0x1bbdc84c4 _BlockUntilNextEventMatchingListInModeWithFilter + 72
8   AppKit                        	       0x1b5da7aec _DPSNextEvent + 844
9   AppKit                        	       0x1b5da6390 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1332
10  libSDL2-2.0.0.dylib           	       0x1030d89f8 Cocoa_PumpEventsUntilDate + 100
11  libSDL2-2.0.0.dylib           	       0x1030d8b34 Cocoa_PumpEvents + 52
12  libSDL2-2.0.0.dylib           	       0x103058d84 SDL_PumpEvents_REAL + 40
13  libSDL2-2.0.0.dylib           	       0x10305902c SDL_WaitEventTimeout_REAL + 628
14  DDNet                         	       0x102938e84 CInput::Update() + 172
15  DDNet                         	       0x102920d48 CClient::Run() + 2160
16  DDNet                         	       0x102925f14 TWMain + 2144
17  dyld                          	       0x102e490f4 start + 520

Thread 1:
0   libsystem_kernel.dylib        	       0x1b3179f4c sem_wait + 8
1   DDNet                         	       0x1028f2308 aio_thread(void*) + 216
2   DDNet                         	       0x1028f2f14 thread_run(void*) + 48
3   libsystem_pthread.dylib       	       0x1b31894ec _pthread_start + 148
4   libsystem_pthread.dylib       	       0x1b31842d0 thread_start + 8

Thread 2:
0   libsystem_kernel.dylib        	       0x1b3179f4c sem_wait + 8
1   DDNet                         	       0x1028da774 CJobPool::WorkerThread(void*) + 108
2   DDNet                         	       0x1028f2f14 thread_run(void*) + 48
3   libsystem_pthread.dylib       	       0x1b31894ec _pthread_start + 148
4   libsystem_pthread.dylib       	       0x1b31842d0 thread_start + 8

Thread 3:
0   libsystem_kernel.dylib        	       0x1b3179f4c sem_wait + 8
1   DDNet                         	       0x1028da774 CJobPool::WorkerThread(void*) + 108
2   DDNet                         	       0x1028f2f14 thread_run(void*) + 48
3   libsystem_pthread.dylib       	       0x1b31894ec _pthread_start + 148
4   libsystem_pthread.dylib       	       0x1b31842d0 thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x1b31842bc start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1b31842bc start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x1b31842bc start_wqthread + 0

Thread 7 Crashed:
0   libobjc.A.dylib               	       0x1b30143e0 objc_msgSend + 32
1   AppleMetalOpenGLRenderer      	       0x107471e08 GLDTextureRec::getTextureResource(unsigned int, bool) + 384
2   AppleMetalOpenGLRenderer      	       0x10747bf84 GLDContextRec::addRenderPassResources() + 64
3   AppleMetalOpenGLRenderer      	       0x107484b54 gldClearFramebufferData + 248
4   GLEngine                      	       0x214390540 glClear_Exec + 448
5   DDNet                         	       0x1029071cc CCommandProcessorFragment_OpenGL::RunCommand(CCommandBuffer::SCommand const*) + 448
6   DDNet                         	       0x102913c58 CCommandProcessor_SDL_OpenGL::RunBuffer(CCommandBuffer*) + 120
7   DDNet                         	       0x1029133e4 CGraphicsBackend_Threaded::ThreadFunc() + 216
8   DDNet                         	       0x102916498 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CGraphicsBackend_Threaded::StartProcessor(CGraphicsBackend_Threaded::ICommandProcessor*)::$_0> >(void*) + 64
9   libsystem_pthread.dylib       	       0x1b31894ec _pthread_start + 148
10  libsystem_pthread.dylib       	       0x1b31842d0 thread_start + 8

Thread 8:
0   libsystem_pthread.dylib       	       0x1b31842bc start_wqthread + 0

Thread 9:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1b314d954 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1b314dd00 mach_msg + 76
2   CoreFoundation                	       0x1b3254e38 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1b32532f0 __CFRunLoopRun + 1212
4   CoreFoundation                	       0x1b3252694 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1b5f14c24 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x1b31894ec _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1b31842d0 thread_start + 8

Thread 10:
0   libsystem_pthread.dylib       	       0x1b31842bc start_wqthread + 0


Thread 7 crashed with ARM Thread State (64-bit):
    x0: 0x0000600001946280   x1: 0x00000001fd3d3177   x2: 0x0000000000000102   x3: 0x0000000000000000
    x4: 0x0000000000000010   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000023
    x8: 0x0000000154f582f8   x9: 0x0000000000000001  x10: 0x6ae1600001946280  x11: 0x0000000000000002
   x12: 0x0000000000000001  x13: 0x00005723a12c6280  x14: 0x001ffe0000000000  x15: 0x00005723a12c6280
   x16: 0x00005723a12c6280  x17: 0x00000001074bc308  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000600001946100  x21: 0x0000000154f580d0  x22: 0x0000000000000000  x23: 0x0000000154f5810c
   x24: 0x0000000148132a68  x25: 0x0000000148132e30  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016d99ad20   lr: 0x0000000107471e08
    sp: 0x000000016d99ace0   pc: 0x00000001b30143e0 cpsr: 0x20001000
   far: 0x00005723a12c6290  esr: 0x92000005 (Data Abort) byte read Translation fault

Binary Images:
       0x1b31d0000 -        0x1b3713fff com.apple.CoreFoundation (6.9) <b2ff96d0-ae99-31ef-9014-fc9964b4f3e0> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1bbd98000 -        0x1bc0c7fff com.apple.HIToolbox (2.1.1) <98ea191e-b6f8-3036-b267-eeadb5f03c7d> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x1b5d66000 -        0x1b6c17fff com.apple.AppKit (6.9) <518f4e68-c324-320f-9d7f-85c224eae972> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x103038000 -        0x103127fff libSDL2-2.0.0.dylib (*) <f4d6a97a-3058-3e84-9e87-b6c8b24f48f1> /opt/homebrew/*/libSDL2-2.0.0.dylib
       0x102834000 -        0x102a73fff DDNet (*) <c2273d7a-3e32-3752-905d-f0287b90169a> /Users/USER/*/DDNet
       0x102e44000 -        0x102ea3fff dyld (*) <86a8ba48-8bb4-3b30-9cda-051f73c74f44> /usr/lib/dyld
       0x1b314c000 -        0x1b3181fff libsystem_kernel.dylib (*) <c8524c02-b14f-30bd-a228-c44b4a448e68> /usr/lib/system/libsystem_kernel.dylib
       0x1b3182000 -        0x1b318efff libsystem_pthread.dylib (*) <4786e19a-9312-38e6-80ef-9c1394548118> /usr/lib/system/libsystem_pthread.dylib
       0x1b300e000 -        0x1b3049fff libobjc.A.dylib (*) <2eabed7f-1e81-3a1b-bb4b-985b8dd3b77f> /usr/lib/libobjc.A.dylib
       0x107450000 -        0x1074bbfff com.apple.AppleMetalOpenGLRenderer (1.0) <561d1f36-51eb-3a8f-972e-15beeac26465> /System/Library/Extensions/AppleMetalOpenGLRenderer.bundle/Contents/MacOS/AppleMetalOpenGLRenderer
       0x214374000 -        0x2144e2fff GLEngine (*) <2ac316b4-7efc-300c-bcb4-7e7534405b82> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=884.8M resident=0K(0%) swapped_out_or_unallocated=884.8M(100%)
Writable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework              1408K       11 
Activity Tracing                   256K        1 
CG backing stores                 4800K        8 
CG image                           144K        6 
ColorSync                          512K       25 
CoreAnimation                      240K       14 
CoreGraphics                        32K        2 
CoreUI image data                 1584K       13 
Foundation                          48K        2 
Image IO                            16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           434.8M       70 
MALLOC guard page                  192K       11 
MALLOC_MEDIUM (reserved)         696.0M        7         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3 
SQLite page cache                   64K        1 
STACK GUARD                       56.2M       11 
Stack                             13.3M       11 
VM_ALLOCATE                        1.0G      150 
__AUTH                            2060K      218 
__AUTH_CONST                      13.1M      381 
__DATA                             9.9M      370 
__DATA_CONST                      13.7M      392 
__DATA_DIRTY                      1113K      141 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       572.0M       13 
__OBJC_CONST                      2305K      185 
__OBJC_RO                         81.8M        1 
__OBJC_RW                         3088K        1 
__TEXT                           312.7M      408 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                      153.2M       23 
shared memory                      960K       19 
===========                     =======  ======= 
TOTAL                              3.7G     2505 
TOTAL, minus reserved VM space     2.6G     2505 



-----------
Full Report
-----------

{"app_name":"DDNet","timestamp":"2021-12-13 16:39:15.00 +0100","app_version":"","slice_uuid":"c2273d7a-3e32-3752-905d-f0287b90169a","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.0.1 (21A559)","incident_id":"AF8CD0AD-0F03-4231-ACBC-2F4AC6685474","name":"DDNet"}
{
  "uptime" : 20000,
  "procLaunch" : "2021-12-13 16:38:26.8170 +0100",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "procStartAbsTime" : 502047828719,
  "coalitionID" : 522,
  "osVersion" : {
    "train" : "macOS 12.0.1",
    "build" : "21A559",
    "releaseType" : "User"
  },
  "captureTime" : "2021-12-13 16:39:15.8219 +0100",
  "incident" : "AF8CD0AD-0F03-4231-ACBC-2F4AC6685474",
  "bug_type" : "309",
  "pid" : 6227,
  "procExitAbsTime" : 503223363056,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "DDNet",
  "procPath" : "\/Users\/USER\/*\/DDNet",
  "parentProc" : "zsh",
  "parentPid" : 1317,
  "coalitionName" : "com.googlecode.iterm2",
  "crashReporterKey" : "3AB7E5C0-6273-0D0C-4A67-105D60AF53FE",
  "responsiblePid" : 528,
  "responsibleProc" : "iTerm2",
  "sip" : "enabled",
  "vmRegionInfo" : "0x5723a12c6290 is not in any region.  Bytes after previous region: 95329503175313  Bytes before following region: 9742576754032\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      commpage (reserved)        1000000000-7000000000   [384.0G] ---\/--- SM=NUL  ...(unallocated)\n--->  GAP OF 0x5f9000000000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00005723a12c6290","rawCodes":[1,95810539512464],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00005723a12c6290"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":6227},
  "vmregioninfo" : "0x5723a12c6290 is not in any region.  Bytes after previous region: 95329503175313  Bytes before following region: 9742576754032\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      commpage (reserved)        1000000000-7000000000   [384.0G] ---\/--- SM=NUL  ...(unallocated)\n--->  GAP OF 0x5f9000000000 BYTES\n      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-\/rwx SM=PRV  ",
  "asi" : {"objc":["objc_msgSend() selector name: sampleCount"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 7,
  "threads" : [{"id":127566,"queue":"com.apple.main-thread","frames":[{"imageOffset":162388,"symbol":"CFBasicHashGetCountOfKey","symbolLocation":0,"imageIndex":0},{"imageOffset":290572,"symbol":"CFSetContainsValue","symbolLocation":188,"imageIndex":0},{"imageOffset":541788,"symbol":"__CFRunLoopDoBlocks","symbolLocation":284,"imageIndex":0},{"imageOffset":537844,"symbol":"__CFRunLoopRun","symbolLocation":1728,"imageIndex":0},{"imageOffset":534164,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":0},{"imageOffset":199056,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":1},{"imageOffset":198404,"symbol":"ReceiveNextEventCommon","symbolLocation":552,"imageIndex":1},{"imageOffset":197828,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":1},{"imageOffset":269036,"symbol":"_DPSNextEvent","symbolLocation":844,"imageIndex":2},{"imageOffset":263056,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1332,"imageIndex":2},{"imageOffset":657912,"symbol":"Cocoa_PumpEventsUntilDate","symbolLocation":100,"imageIndex":3},{"imageOffset":658228,"symbol":"Cocoa_PumpEvents","symbolLocation":52,"imageIndex":3},{"imageOffset":134532,"symbol":"SDL_PumpEvents_REAL","symbolLocation":40,"imageIndex":3},{"imageOffset":135212,"symbol":"SDL_WaitEventTimeout_REAL","symbolLocation":628,"imageIndex":3},{"imageOffset":1068676,"symbol":"CInput::Update()","symbolLocation":172,"imageIndex":4},{"imageOffset":970056,"symbol":"CClient::Run()","symbolLocation":2160,"imageIndex":4},{"imageOffset":990996,"symbol":"TWMain","symbolLocation":2144,"imageIndex":4},{"imageOffset":20724,"symbol":"start","symbolLocation":520,"imageIndex":5}]},{"id":127582,"frames":[{"imageOffset":188236,"symbol":"sem_wait","symbolLocation":8,"imageIndex":6},{"imageOffset":779016,"symbol":"aio_thread(void*)","symbolLocation":216,"imageIndex":4},{"imageOffset":782100,"symbol":"thread_run(void*)","symbolLocation":48,"imageIndex":4},{"imageOffset":29932,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8912,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":127583,"frames":[{"imageOffset":188236,"symbol":"sem_wait","symbolLocation":8,"imageIndex":6},{"imageOffset":681844,"symbol":"CJobPool::WorkerThread(void*)","symbolLocation":108,"imageIndex":4},{"imageOffset":782100,"symbol":"thread_run(void*)","symbolLocation":48,"imageIndex":4},{"imageOffset":29932,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8912,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":127584,"frames":[{"imageOffset":188236,"symbol":"sem_wait","symbolLocation":8,"imageIndex":6},{"imageOffset":681844,"symbol":"CJobPool::WorkerThread(void*)","symbolLocation":108,"imageIndex":4},{"imageOffset":782100,"symbol":"thread_run(void*)","symbolLocation":48,"imageIndex":4},{"imageOffset":29932,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8912,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":127585,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":127586,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":127601,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"triggered":true,"id":127606,"threadState":{"x":[{"value":105553142768256},{"value":8543613303,"objc-selector":"sampleCount"},{"value":258},{"value":0},{"value":16},{"value":0},{"value":0},{"value":35},{"value":5720343288},{"value":1},{"value":7701542390923027072},{"value":2},{"value":1},{"value":95810539512448},{"value":9005000231485440},{"value":95810539512448},{"value":95810539512448},{"value":4417372936},{"value":0},{"value":0},{"value":105553142767872},{"value":5720342736},{"value":0},{"value":5720342796},{"value":5504182888},{"value":5504183856},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4417068552},"cpsr":{"value":536875008},"fp":{"value":6133755168},"sp":{"value":6133755104},"esr":{"value":2449473541,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":7298171872,"matchesCrashFrame":1},"far":{"value":95810539512464}},"frames":[{"imageOffset":25568,"symbol":"objc_msgSend","symbolLocation":32,"imageIndex":8},{"imageOffset":138760,"symbol":"GLDTextureRec::getTextureResource(unsigned int, bool)","symbolLocation":384,"imageIndex":9},{"imageOffset":180100,"symbol":"GLDContextRec::addRenderPassResources()","symbolLocation":64,"imageIndex":9},{"imageOffset":215892,"symbol":"gldClearFramebufferData","symbolLocation":248,"imageIndex":9},{"imageOffset":116032,"symbol":"glClear_Exec","symbolLocation":448,"imageIndex":10},{"imageOffset":864716,"symbol":"CCommandProcessorFragment_OpenGL::RunCommand(CCommandBuffer::SCommand const*)","symbolLocation":448,"imageIndex":4},{"imageOffset":916568,"symbol":"CCommandProcessor_SDL_OpenGL::RunBuffer(CCommandBuffer*)","symbolLocation":120,"imageIndex":4},{"imageOffset":914404,"symbol":"CGraphicsBackend_Threaded::ThreadFunc()","symbolLocation":216,"imageIndex":4},{"imageOffset":926872,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, CGraphicsBackend_Threaded::StartProcessor(CGraphicsBackend_Threaded::ICommandProcessor*)::$_0> >(void*)","symbolLocation":64,"imageIndex":4},{"imageOffset":29932,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8912,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":127607,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":127622,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":6},{"imageOffset":544312,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":0},{"imageOffset":537328,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":0},{"imageOffset":534164,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":0},{"imageOffset":1764388,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":2},{"imageOffset":29932,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":8912,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":127625,"frames":[{"imageOffset":8892,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7299989504,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5521408,
    "uuid" : "b2ff96d0-ae99-31ef-9014-fc9964b4f3e0",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1855.105"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7446560768,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3342336,
    "uuid" : "98ea191e-b6f8-3036-b267-eeadb5f03c7d",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7345692672,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15409152,
    "uuid" : "518f4e68-c324-320f-9d7f-85c224eae972",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4345528320,
    "size" : 983040,
    "uuid" : "f4d6a97a-3058-3e84-9e87-b6c8b24f48f1",
    "path" : "\/opt\/homebrew\/*\/libSDL2-2.0.0.dylib",
    "name" : "libSDL2-2.0.0.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4337123328,
    "size" : 2359296,
    "uuid" : "c2273d7a-3e32-3752-905d-f0287b90169a",
    "path" : "\/Users\/USER\/*\/DDNet",
    "name" : "DDNet"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4343480320,
    "size" : 393216,
    "uuid" : "86a8ba48-8bb4-3b30-9cda-051f73c74f44",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7299448832,
    "size" : 221184,
    "uuid" : "c8524c02-b14f-30bd-a228-c44b4a448e68",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7299670016,
    "size" : 53248,
    "uuid" : "4786e19a-9312-38e6-80ef-9c1394548118",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7298146304,
    "size" : 245760,
    "uuid" : "2eabed7f-1e81-3a1b-bb4b-985b8dd3b77f",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4416929792,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.AppleMetalOpenGLRenderer",
    "size" : 442368,
    "uuid" : "561d1f36-51eb-3a8f-972e-15beeac26465",
    "path" : "\/System\/Library\/Extensions\/AppleMetalOpenGLRenderer.bundle\/Contents\/MacOS\/AppleMetalOpenGLRenderer",
    "name" : "AppleMetalOpenGLRenderer",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8929099776,
    "size" : 1503232,
    "uuid" : "2ac316b4-7efc-300c-bcb4-7e7534405b82",
    "path" : "\/System\/Library\/Frameworks\/OpenGL.framework\/Versions\/A\/Resources\/GLEngine.bundle\/GLEngine",
    "name" : "GLEngine"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 7296499712,
  "size" : 3072180224,
  "uuid" : "a6162d66-93e3-3251-93cc-b11f7c8c830e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=884.8M resident=0K(0%) swapped_out_or_unallocated=884.8M(100%)\nWritable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework              1408K       11 \nActivity Tracing                   256K        1 \nCG backing stores                 4800K        8 \nCG image                           144K        6 \nColorSync                          512K       25 \nCoreAnimation                      240K       14 \nCoreGraphics                        32K        2 \nCoreUI image data                 1584K       13 \nFoundation                          48K        2 \nImage IO                            16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           434.8M       70 \nMALLOC guard page                  192K       11 \nMALLOC_MEDIUM (reserved)         696.0M        7         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        256K        3 \nSQLite page cache                   64K        1 \nSTACK GUARD                       56.2M       11 \nStack                             13.3M       11 \nVM_ALLOCATE                        1.0G      150 \n__AUTH                            2060K      218 \n__AUTH_CONST                      13.1M      381 \n__DATA                             9.9M      370 \n__DATA_CONST                      13.7M      392 \n__DATA_DIRTY                      1113K      141 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       572.0M       13 \n__OBJC_CONST                      2305K      185 \n__OBJC_RO                         81.8M        1 \n__OBJC_RW                         3088K        1 \n__TEXT                           312.7M      408 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                      153.2M       23 \nshared memory                      960K       19 \n===========                     =======  ======= \nTOTAL                              3.7G     2505 \nTOTAL, minus reserved VM space     2.6G     2505 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000174
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6194416dea7ed64a7812a429"
      },
      "deploymentId" : 240000322
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000081
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61ae8d06da72d16a4beb762e"
      },
      "deploymentId" : 240000290
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}

```

File: src/engine/shared/config_variables.h [hunk 1]
```diff
@@ -120,7 +120,11 @@ MACRO_CONFIG_INT(GfxRefreshRate, gfx_refresh_rate, 0, 0, 10000, CFGFLAG_SAVE | C
 MACRO_CONFIG_INT(GfxFinish, gfx_finish, 0, 0, 1, CFGFLAG_SAVE | CFGFLAG_CLIENT, "")
 MACRO_CONFIG_INT(GfxBackgroundRender, gfx_backgroundrender, 1, 0, 1, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Render graphics when window is in background")
 MACRO_CONFIG_INT(GfxTextOverlay, gfx_text_overlay, 10, 1, 100, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Stop rendering textoverlay in editor or with entities: high value = less details = more speed")
+#if !defined(CONF_PLATFORM_MACOS)
 MACRO_CONFIG_INT(GfxAsyncRenderOld, gfx_asyncrender_old, 1, 0, 1, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Do rendering async from the the update")
+#else
+MACRO_CONFIG_INT(GfxAsyncRenderOld, gfx_asyncrender_old, 0, 0, 0, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Do rendering async from the the update")
```
Comment (heinrich5991) [inline src/engine/shared/config_variables.h:126]: 0, 0, 0 is the code for allowing arbitrary values IIRC, probably doesn't do what you want, here.

**Comment by heinrich5991** [comment]
Was this just for testing or should it go in?

**Comment by heinrich5991** [comment]
Probably should go in, is also in another PR.

bors r+

Thanks.

**Comment by def-** [comment]
Well, it's better with this but not entirely fixed. Maybe @Learath2 knows more

**Comment by Learath2** [comment]
This seems to be an issue with some gl commands happening on the main thread instead of our drawing thread. I'm not completely sure where along the way it could be happening though, maybe @Jupeyy has an idea?

We could also try to block the draw thread while resizing and only let it keep drawing after resizing is done. It'll make the window look frozen while resizing but just might be enough.

**Comment by Jupeyy** [comment]
I doubt that any GL command happens on the main thread, but i agree, that the draw thread could be emptied/wait for empty before resizing happens
