### PR TITLE
Use `dbg_assert_failed` on Rust panic

### LINKED ISSUE #12074: Crashes due to Rust panic do not produce crash dump on Windows
Because Rust panics are currently fail-fast, which cannot be caught by using `SetUnhandledExceptionFilter` on Windows, which is what [ExcHndl](https://github.com/jrfonseca/drmingw) does.

Can we override the behavior of panics to throw an unhandled exception or abort in such a way that the unhandled exception filter can catch them panic?

### PR DESCRIPTION
**Pull request by heinrich5991**
Fixes #12074.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or Valgrind's memcheck](https://github.com/ddnet/ddnet/blob/master/docs/DEBUGGING.md#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)
- [x] I didn't use generative AI to generate more than single-line completions

### CODE REVIEW

**Comment by heinrich5991** [comment]
I tested it using the following diff in the console command:
```patch
diff --git a/src/engine/shared/rust_version.rs b/src/engine/shared/rust_version.rs
index dc65764dcb..31fe3a9e38 100644
--- a/src/engine/shared/rust_version.rs
+++ b/src/engine/shared/rust_version.rs
@@ -34,6 +34,7 @@ pub fn RustVersionPrint(console: &IConsole) {
         s!(include_str!(concat!(env!("OUT_DIR"), "/rustc-version"))),
         gs_ConsoleDefaultColor,
     );
+    panic!();
 }
 
 #[allow(non_snake_case)]
```

It looked like this on my Linux:
image

Could you test this on Windows, @Robyt3?

File: src/base/rust.rs [hunk 1]
```diff
@@ -266,3 +270,39 @@ macro_rules! s {
         )
     };
 }
+
+// This function tries pretty hard not to panic, even for suspicious parameters.
+fn dbg_assert_panic_handler(panic_info: &PanicHookInfo) -> ! {
+    // TODO (MSRV 1.92): Use `file_as_c_str`.
+    let filename = panic_info.location().map(|l| l.file()).unwrap_or("unknown");
```
Comment (Robyt3) [inline src/base/rust.rs:301]: Should we normalize this path, i.e. replace `\` with `/`? The path for C++ assertions currently contains only `/` also on Windows.

**Review by Robyt3 — COMMENTED** [review]
Seems good. Works on Windows in Debug and RelWithDebInfo. Though after stripping the debug symbols with `strip -s`, which is done by the cmake package targets, some lines in the backtrace cannot be symbolized anymore with `scripts/parse_crashlog_drmingw.py` (using the original, unstripped executable).

Example symbolized stack trace:

```
0x00000001405131d5: dbg_break() at <...>\ddnet\build-release/<...>/ddnet/src/base/dbg.cpp:46
 (inlined by) dbg_assert_imp at <...>\ddnet\build-release/<...>/ddnet/src/base/dbg.cpp:40
0x000000014038f80f: ?? at ??:?
0x000000014038fb8c: ?? at ??:?
0x000000014040b489: ?? at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\std\src/panicking.rs:835
0x000000014040b14d: ?? at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\std\src/panicking.rs:?
0x0000000140402fdf: ?? at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\std\src\sys/backtrace.rs:182
0x00000001403e2fde: ?? at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\std\src/panicking.rs:689
0x00000001403d6a3d: ?? at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\core\src/panicking.rs:80
0x00000001403d5757: ?? at /rustc/4a4ef493e3a1488c6e321570238084b38948f6db/library\core\src/result.rs:1867
0x000000014038d273: ?? at ??:?
0x000000014038f3a8: ?? at ??:?
0x00000001400b5fda: CSnapshotDelta::UnpackDelta(CSnapshot const&, CSnapshotBuffer&, rust::cxxbridge1::Slice<int const>) at <...>\ddnet\build-release/<...>/ddnet/src/rust-bridge/engine/shared/snapshot/delta.cpp:677
0x000000014006820b: CDemoPlayer::DoTick() at <...>\ddnet\build-release/<...>/ddnet/src/engine/shared/demo.cpp:736
0x0000000140068f3f: CDemoPlayer::Update(bool) at <...>\ddnet\build-release/<...>/ddnet/src/engine/shared/demo.cpp:1240
0x0000000140113cc5: CClient::Update() at <...>\ddnet\build-release/<...>/ddnet/src/engine/client/client.cpp:2770
0x0000000140114b49: CClient::Run() at <...>\ddnet\build-release/<...>/ddnet/src/engine/client/client.cpp:3342
0x0000000140511017: IClient::State() const at <...>\ddnet\build-release/<...>/ddnet/src/engine/client.h:143
 (inlined by) main at <...>\ddnet\build-release/<...>/ddnet/src/engine/client/client.cpp:5126
0x00000001400010c9: __tmainCRTStartup at D:\W\B\src\build-MINGW64/D:/W/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:237
0x00000001400013f6: WinMainCRTStartup at D:\W\B\src\build-MINGW64/D:/W/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:93
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

(The duplicated paths seem to be an issue when I build the client locally, but it looks correct for official nightly releases.)

**Comment by heinrich5991** [comment]
I fixed the CI, should be ready for review now.

I don't have a too strong opinion on `/` vs `\`, I'd keep it as-is, as it's less string manipulation. If you'd prefer, I can change it to replace `\` with `/`.

I've opened a new issue for the missing line numbers in Rust code: #12112.

**Review by Robyt3 — APPROVED** [review]
