### PR TITLE
Fix multiple editor undo/redo issues

### LINKED ISSUE #7738: Segfault with undo/redo when using the "Remove unused envelopes" tool
Steps to reproduce
1. Create a few envelopes
2. Tools -> Remove unused envelopes
3. History -> Envelope -> Add new envelope

https://github.com/ddnet/ddnet/assets/141338449/f84c9a17-c46c-48f8-864b-820240f90dab

### PR DESCRIPTION
**Pull request by archimede67**
Fixed crash when runing tool 'Remove unused envelopes' and trying to undo the addition of an envelope (fixes #7738).
Fixed issues where undo/redo would not work properly when changing a layer's order or group property.
Added missing action for changing the position of a sound source.

I don't know if there are any more problems, so feel free to open an issue when you encounter a crash/unexpected behavior while using the feature.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/editor/editor_actions.cpp [hunk 1]
```diff
@@ -794,12 +794,20 @@ void CEditorActionEditLayerProp::Apply(int Value)
...
-		auto Position = std::find(pCurrentGroup->m_vpLayers.begin(), pCurrentGroup->m_vpLayers.end(), m_pLayer);
-		if(Position != pCurrentGroup->m_vpLayers.end())
-			pCurrentGroup->m_vpLayers.erase(Position);
-		m_pEditor->m_Map.m_vpGroups[Value]->m_vpLayers.push_back(m_pLayer);
+		auto pPreviousGroup = m_pEditor->m_Map.m_vpGroups[Value];
+		pCurrentGroup->m_vpLayers.erase(pCurrentGroup->m_vpLayers.begin() + pCurrentGroup->m_vpLayers.size() - 1);
+		if(Value == m_Previous)
+		{
+			pPreviousGroup->m_vpLayers.insert(pPreviousGroup->m_vpLayers.begin() + m_LayerIndex, m_pLayer);
+			printf("Inserted at %d of %d\n", m_LayerIndex, m_Previous);
```
Comment (Robyt3) [inline src/game/editor/editor_actions.cpp:802]: Remove debug output

File: src/game/editor/editor_actions.cpp [hunk 2]
```diff
@@ -794,12 +794,20 @@ void CEditorActionEditLayerProp::Apply(int Value)
...
+		}
+		else
+		{
+			pPreviousGroup->m_vpLayers.push_back(m_pLayer);
+			printf("Inserted at end of %d\n", Value);
```
Comment (Robyt3) [inline src/game/editor/editor_actions.cpp:807]: Remove debug output

**Review by Robyt3 — CHANGES_REQUESTED** [review]

**Review by Robyt3 — APPROVED** [review]

**Review by def- — APPROVED** [review]
