### PR TITLE
Make binds prints the original bind command

### LINKED ISSUE #10461: Copy pasting from `bind <key>` does not work in all cases
Image
If you look at the syntax, you will see that it is different. So maybe I don't understand something, but why? If I want to share my bind, why do I need to add " " for no reason?

This is needed for a better binding sharing experience.
Maybe it would be better to go further and add a command for that with a **_variable_** where you can't rebind your bind if used shared bind
Like:
We have: `bind mouse4 "+toggle cl_mouse_max_distance 2 210; +toggle inp_mouse_sensitivity 80 85"`
I want to share it with a new player, but the new player will definitely have a different `max distance`.
So, instead of this, it would be better to add a new variable like` [your max distance]`.
So when you trigger the cmd for sharing the bind, it will look like this:
` /share_bind mouse4`
`bind mouse4 "+toggle cl_mouse_max_distance 2 "[your max distance]; +toggle inp_mousesens 80 "[your mousesens]"`
Then new players can just copy that and won't have any issues.

### PR DESCRIPTION
**Pull request by Pioooooo**
Closes #10461.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/components/binds.cpp [hunk 1]
```diff
@@ -334,7 +334,18 @@ void CBinds::ConBind(IConsole::IResult *pResult, void *pUserData)
...
+			char *pBuffer = (char *)malloc(Size);
+			char *pEnd = pBuffer + Size;
+			str_format(pBuffer, Size, "bind %s \"", pKeyName);
+			char *pDst = pBuffer + str_length(pBuffer);
+			str_escape(&pDst, pBinds->m_aapKeyBindings[BindSlot.m_ModifierMask][BindSlot.m_Key], pEnd);
+			str_append(pBuffer, "\"", Size);
+
+			log_info_color(BIND_PRINT_COLOR, "binds", pBuffer);
+			free(pBuffer);
+		}
```
Comment (heinrich5991) [inline src/game/client/components/binds.cpp]: You use this twice. Factor it out into a function.

File: src/game/client/components/binds.cpp [hunk 2]
```diff
@@ -334,7 +334,18 @@ void CBinds::ConBind(IConsole::IResult *pResult, void *pUserData)
 		if(!pBinds->m_aapKeyBindings[BindSlot.m_ModifierMask][BindSlot.m_Key])
 			log_info_color(BIND_PRINT_COLOR, "binds", "%s (%d) is not bound", pKeyName, BindSlot.m_Key);
 		else
-			log_info_color(BIND_PRINT_COLOR, "binds", "%s (%d) = %s", pKeyName, BindSlot.m_Key, pBinds->m_aapKeyBindings[BindSlot.m_ModifierMask][BindSlot.m_Key]);
+		{
+			int Size = str_length(pBinds->m_aapKeyBindings[BindSlot.m_ModifierMask][BindSlot.m_Key]) * 2 + 30;
+			char *pBuffer = (char *)malloc(Size);
+			char *pEnd = pBuffer + Size;
+			str_format(pBuffer, Size, "bind %s \"", pKeyName);
```
Comment (heinrich5991) [inline src/game/client/components/binds.cpp]: Thought: Would it be better to only quote the command if necessary? Might make the output cleaner.

**Review by heinrich5991 — COMMENTED** [review]
Thanks for implementing this.

File: src/game/client/components/binds.cpp (hunk 1 above)
Comment (Pioooooo) [reply src/game/client/components/binds.cpp]: There's actually a third in the following lines where I stole it from that print it into settings cfg. I don't know how to do it properly because I have to handle the pointer lifetime, or should I use std::string (which I don't find used much in the codebase)

Comment (Robyt3) [reply src/game/client/components/binds.cpp]: I would extract a function like so:

```cpp
char *CBinds::FormatBindCommand(int Modifier, int Key) const
{
	// worst case the str_escape can double the string length
	int Size = str_length(m_aapKeyBindings[Modifier][Key]) * 2 + 30;
	char *pBuffer = (char *)malloc(Size);
	char *pEnd = pBuffer + Size;

	char aModifiers[128];
	GetKeyBindModifiersName(Modifier, aModifiers, sizeof(aModifiers));
	str_format(pBuffer, Size, "bind %s%s \"", aModifiers, Input()->KeyName(Key));
	// process the string. we need to escape some characters
	char *pDst = pBuffer + str_length(pBuffer);
	str_escape(&pDst, m_aapKeyBindings[Modifier][Key], pEnd);
	str_append(pBuffer, "\"", Size);
	return pBuffer;
}
```

Callers have to call `free` after they are done using the string. I think that's sufficient for a private helper function.

**Comment by heinrich5991** [comment]
Maybe as `unbind <key>`?

**Comment by Pioooooo** [comment]
I don't think there's any use for that

File: src/game/client/components/binds.cpp [hunk 3]
```diff
@@ -355,9 +350,15 @@ void CBinds::ConBinds(IConsole::IResult *pResult, void *pUserData)
 		else
 		{
 			if(!pBinds->m_aapKeyBindings[BindSlot.m_ModifierMask][BindSlot.m_Key])
-				log_info_color(BIND_PRINT_COLOR, "binds", "%s (%d) is not bound", pKeyName, BindSlot.m_Key);
+				log_info_color(BIND_PRINT_COLOR, "binds", "%s is not bound", pKeyName);
 			else
-				log_info_color(BIND_PRINT_COLOR, "binds", "%s (%d) = %s", pKeyName, BindSlot.m_Key, pBinds->m_aapKeyBindings[BindSlot.m_ModifierMask][BindSlot.m_Key]);
+			{
+				int Size = str_length(pBinds->m_aapKeyBindings[BindSlot.m_ModifierMask][BindSlot.m_Key]) * 2 + 30;
+				auto *pBuf = static_cast<char *>(malloc(Size));
```
Comment (Robyt3) [inline src/game/client/components/binds.cpp]: Also move the duplicate size calculation and allocation inside the `GetKeyBindCommand` function, no need to pass in the buffer and size.

File: src/game/client/components/binds.cpp [hunk 4]
```diff
@@ -371,7 +372,11 @@ void CBinds::ConBinds(IConsole::IResult *pResult, void *pUserData)
 				if(!pBinds->m_aapKeyBindings[Modifier][Key])
 					continue;
 
-				log_info_color(BIND_PRINT_COLOR, "binds", "%s%s (%d) = %s", aModifiers, pBinds->Input()->KeyName(Key), Key, pBinds->m_aapKeyBindings[Modifier][Key]);
+				int Size = str_length(pBinds->m_aapKeyBindings[Modifier][Key]) * 2 + 30;
+				auto *pBuf = static_cast<char *>(malloc(Size));
+				pBinds->GetKeyBindCommand(Modifier, Key, pBuf, Size);
```
Comment (Robyt3) [inline src/game/client/components/binds.cpp]: Remove unused `aModifiers` above.

File: src/game/client/components/binds.cpp [hunk 5]
```diff
@@ -472,17 +488,10 @@ void CBinds::ConfigSaveCallback(IConfigManager *pConfigManager, void *pUserData)
...
-			str_format(pBuffer, Size, "bind %s%s \"", aModifiers, pSelf->Input()->KeyName(Key));
-			// process the string. we need to escape some characters
-			char *pDst = pBuffer + str_length(pBuffer);
-			str_escape(&pDst, pSelf->m_aapKeyBindings[Modifier][Key], pEnd);
-			str_append(pBuffer, "\"", Size);
-
-			pConfigManager->WriteLine(pBuffer);
-			free(pBuffer);
+			auto *pBuf = static_cast<char *>(malloc(Size));
+			pSelf->GetKeyBindCommand(Modifier, Key, pBuf, Size);
```
Comment (Robyt3) [inline src/game/client/components/binds.cpp]: Remove unused `aModifiers` above.

**Review by Robyt3 — CHANGES_REQUESTED** [review]

**Review by Robyt3 — APPROVED** [review]
