### PR TITLE
Fix segfault when swapchain images change (e.g. toggling Vsync)

### LINKED ISSUE #8328: segfault on vulkan_backend.cpp : ClearFrameData
from discord:

i managed to crash the client by setting `cl_refresh_rate` and `gfx_refresh_rate` to 240 aswell as turning `Vsync` on

and then turning cl_refresh_rate and gfx_refresh_rate to 1000 and turning `Vsync` off

`12:58:16: /home/melonarch/Projects/ddnet/build/Desktop-Debug/DDNet ist abgestürzt.`

gdb outputted the following:

```
0x00005555556a04c0 in CCommandProcessorFragment_Vulkan::ClearFrameData (this=0x555555fb6660, FrameImageIndex=4) at /home/melonarch/Projects/ddnet/src/engine/client/backend/vulkan/backend_vulkan.cpp:2048
2048                if(BufferPair.m_pMappedData != nullptr)
```

OS: Arch Linux x86_64
WM: Hyprland (Wayland)

### PR DESCRIPTION
**Pull request by Jupeyy**
fixes #8328

I was able to reproduce #8328 by simply faking the swapchain image count

```cpp
uint32_t ImgNumber = VKCapabilities.minImageCount + 1 + rand() % 5;
```

in `GetNumberOfSwapImages`.

For sync objects I decided that they should not be dependent on the frame count directly anyway.
For vulkan cleanup simply take the swapchain count as parameter instead of relying on the cached one (since that is overwritten when recreating the swapchain).

Also minor refactoring.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
It seems there is also a memory leak involved in the same issue, i have to find that

File: src/engine/client/backend/vulkan/backend_vulkan.cpp [hunk 1]
```diff
@@ -5333,12 +5331,12 @@ class CCommandProcessorFragment_Vulkan : public CCommandProcessorFragment_GLBase
...
-
-		m_vMemorySemaphores.resize(m_SwapChainImageCount);
+		// Create one more sync object than there are frames in flight
+		auto SyncObjectCount = m_SwapChainImageCount + 1;
+		m_vWaitSemaphores.resize(SyncObjectCount);
+		m_vSigSemaphores.resize(SyncObjectCount);
 
-		m_vFrameFences.resize(m_SwapChainImageCount);
+		m_vFrameFences.resize(SyncObjectCount);
 		m_vImagesFences.resize(m_SwapChainImageCount, VK_NULL_HANDLE);
```
Comment (Jupeyy) [inline src/engine/client/backend/vulkan/backend_vulkan.cpp:5340]: For this type `m_SwapChainImageCount` is ok, since they are just a reference per frame to the FrameFences and don't actually create an object

**Review by Robyt3 — APPROVED** [review]
