### PR TITLE
Fix /load from backup database

### LINKED ISSUE #6924: Save deleted without a team getting its state
```
2023-07-26 14:31:45 I save: Save successful: ff358a88-0138-4c05-be28-27131b26dd56
[…]
2023-07-26 14:32:46 I chat: *** […] joined team 22
2023-07-26 14:32:49 I sql: [91] load team done on write backup database, Success=1
2023-07-26 14:32:49 I mysql: connection established
2023-07-26 14:32:49 I sql: [91] load team done on write database
2023-07-26 14:32:49 I sql: [91] load team done move write on backup database to non-backup table
2023-07-26 14:32:50 I sql: [92] load team done on write backup database, Success=1
2023-07-26 14:32:50 I sql: [92] load team done on write database
2023-07-26 14:32:50 I sql: [92] load team done move write on backup database to non-backup table
2023-07-26 14:32:52 I sql: [93] get saves done on read database 0
2023-07-26 14:32:53 I chat: *** '[…]' has left the game
2023-07-26 14:32:53 I game: leave player='0:[…]'
2023-07-26 14:33:16 I sql: [94] get saves done on read database 0
2023-07-26 14:33:17 I sql: SQLite statement: DELETE FROM record_saves WHERE Code = 'stony cadet wiry' AND Map = 'Level' AND SaveID = 'ff358a88-0138-4c05-be28-27131b26dd56'
2023-07-26 14:33:17 I sql: [95] load team done on write backup database, Success=1
2023-07-26 14:33:17 I sql: [95] load team done on write database
2023-07-26 14:33:17 I sql: [95] load team done move write on backup database to non-backup table
2023-07-26 14:33:23 I host_lookup: […]
2023-07-26 14:33:24 I server: player has entered the game. ClientID=0 addr=<[…]> sixup=0
2023-07-26 14:33:24 I chat: *** '[…]' entered and joined the game
2023-07-26 14:33:24 I ddnet: cid=0 version=[…]
2023-07-26 14:33:24 I sql: [96] load player data done on read database 0
2023-07-26 14:33:25 I sql: [97] load team done on write backup database, Success=1
2023-07-26 14:33:25 I sql: [97] load team done on write database
2023-07-26 14:33:25 I sql: [97] load team done move write on backup database to non-backup table
2023-07-26 14:33:27 I sql: [98] load team done on write backup database, Success=1
2023-07-26 14:33:28 I sql: [98] load team done on write database
2023-07-26 14:33:28 I sql: [98] load team done move write on backup database to non-backup table
2023-07-26 14:33:32 I sql: [99] load team done on write backup database, Success=1
2023-07-26 14:33:32 I sql: [99] load team done on write database
2023-07-26 14:33:32 I sql: [99] load team done move write on backup database to non-backup table
2023-07-26 14:33:40 I chat: 3:-2:[…]
[…]
```

A corresponding `Load successful: ff358a88-0138-4c05-be28-27131b26dd56` is not to be found in the logs.

The full log is available on ger10.ddnet.org in /home/teeworlds/bug-6924.log, can be requested from a DDNet admin. Not posted here because it contains sensitive information.

### PR DESCRIPTION
**Pull request by Zwelf**
Saves were deleted without the team getting its state when /load and /save both happened during mysql server not reachable.

Before this fix, the saves were only in the DDNet log output for recovery, not in any database anymore.

`Write::BACKUP_FIRST` is 0 so always false, so the previous code didn't harm other code paths (especially `Write::NORMAL`). The saves were tried to retrieve two times from the database, therefore at the second time it didn't exist anymore. One time erroneously in `Write::BACKUP_FIRST` and the second time in `Write::NORMAL_FAILED`.

Fixes #6924

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/server/scoreworker.cpp [hunk 1]
```diff
@@ -1641,7 +1641,7 @@ bool CScoreWorker::SaveTeam(IDbConnection *pSqlServer, const ISqlData *pGameData
 
 bool CScoreWorker::LoadTeam(IDbConnection *pSqlServer, const ISqlData *pGameData, Write w, char *pError, int ErrorSize)
 {
-	if(w == Write::NORMAL_SUCCEEDED || Write::BACKUP_FIRST)
+	if(w == Write::NORMAL_SUCCEEDED || w == Write::BACKUP_FIRST)
```
Comment (heinrich5991) [inline src/game/server/scoreworker.cpp:1644]: This seems like the only relevant change.

File: src/game/server/scoreworker.cpp [hunk 2]
```diff
@@ -1710,6 +1710,7 @@ bool CScoreWorker::LoadTeam(IDbConnection *pSqlServer, const ISqlData *pGameData
 	}
 	if(!Found)
 	{
+		printf("!Found\n");
```
Comment (heinrich5991) [inline src/game/server/scoreworker.cpp]: Lots of debug printfs left in code.

**Review by heinrich5991 — COMMENTED** [review]
> The saves are only in the DDNet log output for recovery, not in any database anymore.

This describes the "before the PR" state, correct?

Can you make that more obvious in the commit message?

**Comment by Zwelf** [comment]
Thanks for fast review, done.
