### PR TITLE
fix happy ddnet birthday broadcast (#7758)

### LINKED ISSUE #7758: "Happy DDNet birthday" broadcast is only shown for a split second.
https://github.com/ddnet/ddnet/assets/141338449/8505f576-fb73-4308-aef0-a745dd67e31c

This happens because the broadcast is sent before the client knows the current tick. Which means `m_BroadcastTick` will be set to `500` (which is the current tick (0) + 10 seconds). But then the client will receive its first snapshot which will set the correct tick (causing the broadcast to disappear).

### PR DESCRIPTION
**Pull request by swarfeya**
The broadcast gets fixed by only running the method, which triggers the broadcast, only when the client has received (at least) 3 snapshots. 
image
## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]

File: src/game/server/gamecontext.cpp [hunk 1]
```diff
@@ -4078,8 +4078,10 @@ void CGameContext::OnSnap(int ClientID)
 			pPlayer->Snap(ClientID);
 	}
 
-	if(ClientID > -1)
+	if(ClientID > -1) {
 		m_apPlayers[ClientID]->FakeSnap();
+		m_apPlayers[ClientID]->m_SentSnaps++;
```
Comment (Chairn) [inline src/game/server/gamecontext.cpp:4083]: it makes more sense to increment m_SentSnaps directly in FakeSnap after it is effectively sent

**Comment by ChillerDragon** [comment]
Nudelsuff

**Comment by fokkonaut** [comment]
I'd simply send it a second after connecting or something.

File: src/game/server/gamecontext.cpp (hunk 1 above)
Comment (swarfeya) [reply src/game/server/gamecontext.cpp:4083]: I also thought about doing that, but i guessed it might make more sense if m_SentSnaps was being incremented in a method named "OnSnap" instead of "FakeSnap".
If you still think that it would fit better into FakeSnap, sure I can change it

**Review by Robyt3 — APPROVED** [review]
