### PR TITLE
Fix memory leak in SQLite3 print statement

### LINKED ISSUE #3381: Memory leak in sqlite3
```
=================================================================
==18192==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 992 byte(s) in 1 object(s) allocated from:
    #0 0x4f3d02 in __sanitizer::InternalMmapVectorNoCtor<__asan::AllocationSite>::Realloc(unsigned long) (/home/teeworlds/servers/DDNet-Server-asan+0x4f3d02)
    #1 0x7f59e7c7dc08  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x49c08)

SUMMARY: AddressSanitizer: 992 byte(s) leaked in 1 allocation(s).
```

### PR DESCRIPTION
**Pull request by Zwelf**
https://www.sqlite.org/c3ref/expanded_sql.html

Fixes #3381

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
LGTM, CI still failing in an unrelated way.

File: src/engine/server/databases/sqlite.cpp [hunk 1]
```diff
@@ -162,7 +162,11 @@ extern char *sqlite3_expanded_sql(sqlite3_stmt *pStmt) __attribute__((weak));
 void CSqliteConnection::Print()
 {
 	if(m_pStmt != nullptr && sqlite3_expanded_sql != nullptr)
-		dbg_msg("sql", "SQLite statement: %s", sqlite3_expanded_sql(m_pStmt));
+	{
+		char *pExpandedStmt = sqlite3_expanded_sql(m_pStmt);
```
Comment (def-) [inline src/engine/server/databases/sqlite.cpp:166]: Should probably handle the case of returning NULL when no more memory is available.

Comment (heinrich5991) [reply src/engine/server/databases/sqlite.cpp:166]: I don't think we handle allocation failure much in DDNet tbh.
