### PR TITLE
Fix invalid server-assigned utf8 names with (1) prefix (fixes #3269)

### LINKED ISSUE #3269: Failure in move_sqlite.py
Does this mean we lost the ranks? Edit: Seems like not, good.

```
8 new entries in backup database found (8 ranks, 0 teamranks, 0 saves
Moving entries from /home/teeworlds/servers/ddnet-server.sqlite to /home/teeworlds/servers/ddnet-server-2020-11-08.sqlite
You can use the following commands to import the entries to MySQL (use sed 's/record_/prefix_/' for other database prefixes):

    echo '.dump --preserve-rowids' | sqlite3 /home/teeworlds/servers/ddnet-server-2020-11-08.sqlite | grep -E '^INSERT INTO record_(race|teamrace|saves)' | sed -e 's/INSERT INTO/INSERT IGNORE INTO/' | sed -e
's/rowid,//' -e 's/VALUES([0-9]*,/VALUES(/' > ddnet-server-2020-11-08.sql
    mysql -u teeworlds -p'PW2' teeworlds < ddnet-server-2020-11-08.sql

When the ranks are transfered successfully to mysql, /home/teeworlds/servers/ddnet-server-2020-11-08.sqlite can be removed

Log of the transfer:

BEGIN TRANSACTION;
CREATE TABLE record_maps (Map VARCHAR(128) COLLATE BINARY NOT NULL, Server VARCHAR(32) COLLATE BINARY NOT NULL, Mapper VARCHAR(128) COLLATE BINARY NOT NULL, Points INT DEFAULT 0, Stars INT DEFAULT 0, Timestamp
TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (Map));
CREATE TABLE record_points (Name VARCHAR(16) COLLATE BINARY NOT NULL, Points INT DEFAULT 0, PRIMARY KEY (Name));
CREATE TABLE record_race (Map VARCHAR(128) COLLATE BINARY NOT NULL, Name VARCHAR(16) COLLATE BINARY NOT NULL, Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, Time FLOAT DEFAULT 0, Server CHAR(4), cp1
FLOAT DEFAULT 0, cp2 FLOAT DEFAULT 0, cp3 FLOAT DEFAULT 0, cp4 FLOAT DEFAULT 0, cp5 FLOAT DEFAULT 0, cp6 FLOAT DEFAULT 0, cp7 FLOAT DEFAULT 0, cp8 FLOAT DEFAULT 0, cp9 FLOAT DEFAULT 0, cp10 FLOAT DEFAULT 0, cp11
FLOAT DEFAULT 0, cp12 FLOAT DEFAULT 0, cp13 FLOAT DEFAULT 0, cp14 FLOAT DEFAULT 0, cp15 FLOAT DEFAULT 0, cp16 FLOAT DEFAULT 0, cp17 FLOAT DEFAULT 0, cp18 FLOAT DEFAULT 0, cp19 FLOAT DEFAULT 0, cp20 FLOAT DEFAULT
0, cp21 FLOAT DEFAULT 0, cp22 FLOAT DEFAULT 0, cp23 FLOAT DEFAULT 0, cp24 FLOAT DEFAULT 0, cp25 FLOAT DEFAULT 0, GameID VARCHAR(64), DDNet7 BOOL DEFAULT FALSE, PRIMARY KEY (Map, Name, Time, Timestamp, Server));
Traceback (most recent call last):
  File "/home/teeworlds/servers/scripts/move_sqlite.py", line 104, in <module>
    main()
  File "/home/teeworlds/servers/scripts/move_sqlite.py", line 101, in main
    transfer(args.f, args.to)
  File "/home/teeworlds/servers/scripts/move_sqlite.py", line 37, in transfer
    for line in conn_from.iterdump():
  File "/usr/lib/python3.7/sqlite3/dump.py", line 55, in _iterdump
    query_res = cu.execute(q)
sqlite3.OperationalError: Could not decode to UTF-8 column ''INSERT INTO "record_race"
VALUES('||quote("Map")||','||quote("Name")||','||quote("Timestamp")||','||quote("Time")||','||quote("Server")||','||quote("cp1")||','||qu
```
@Zwelf can you please take a look?

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/engine/server/server.cpp [hunk 1]
```diff
@@ -395,6 +395,7 @@ bool CServer::SetClientNameImpl(int ClientID, const char *pNameRequest, bool Set
 		for(int i = 1;; i++)
 		{
 			str_format(aNameTry, sizeof(aNameTry), "(%d)%s", i, aTrimmedName);
+			str_utf8_trim_right(aNameTry);
```
Comment (heinrich5991) [inline src/engine/server/server.cpp:398]: https://youtu.be/DGuRI_SPZYg

Comment (heinrich5991) [inline src/engine/server/server.cpp:398]: This seems to work but isn't the documented functionality of the function, the function says it trims whitespace on the right, but it actually trims whitespace and invalid UTF-8. The more correct function to use would be str_utf8_copy, but it would require yet another buffer. What do you think?

Comment (def-) [reply src/engine/server/server.cpp:398]: Done.

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)
