### PR TITLE
Use reliable APIs to retrieve executable path

### LINKED ISSUE #11418: Wrong executable path in client when running from ddnet:// urls
Normal:

Image

When running from a url:

Image

Possibly because the client falls back to GetCurrentDirectoryW (fs_getcwd) because argv does not contain the path when running from a URL

### PR DESCRIPTION
**Pull request by CherryEx**
Adds OS api calls to reliably get executable path. (and use argv[0] as backup)
The MacOS/Linux code needs more testing though, especially with the updater.
Also fixes #11418 

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [x] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)
- [ ] I didn't use generative AI to generate more than single-line completions

### CODE REVIEW

File: src/base/system.cpp [hunk 1]
```diff
@@ -2456,6 +2456,87 @@ int fs_storage_path(const char *appname, char *path, int max)
 #endif
 }
 
+char *fs_executable_path(char *buffer, int buffer_size, bool remove_name)
```
Comment (heinrich5991) [inline src/base/system.cpp]: Why is there an essentially unused, optional parameter here?

File: src/base/system.cpp [hunk 2]
```diff
@@ -2456,6 +2456,87 @@ int fs_storage_path(const char *appname, char *path, int max)
...
+
+	char *path = (char *)malloc(path_size);
+	if(_NSGetExecutablePath(path, &path_size) != 0)
+	{
+		free(path);
+		buffer[0] = '\0';
+		return nullptr;
+	}
+	char real_path[IO_MAX_PATH_LENGTH];
+	if(realpath(path, real_path) != nullptr) // _NSGetExecutablePath may return relative paths
```
Comment (heinrich5991) [inline src/base/system.cpp]: > `_NSGetExecutablePath` may return relative paths

Is that true? Couldn't find documentation for that online. Can you give an example when it is a relative path?

File: src/engine/shared/storage.cpp [hunk 3]
```diff
@@ -373,19 +378,16 @@ class CStorage : public IStorage
 			{
 				char aBuf[IO_MAX_PATH_LENGTH];
 				str_copy(m_aBinarydir, pArgv0, Pos + 1);
-				str_format(aBuf, sizeof(aBuf), "%s/" PLAT_SERVER_EXEC, m_aBinarydir);
+				str_format(aBuf, sizeof(aBuf), "%s/" PLAT_CLIENT_EXEC, m_aBinarydir);
```
Comment (heinrich5991) [inline src/engine/shared/storage.cpp]: Why was this changed? And not below?

File: src/base/system.cpp [hunk 4]
```diff
@@ -2456,6 +2456,87 @@ int fs_storage_path(const char *appname, char *path, int max)
...
+	static const char *NAMES[] = {
+		"/proc/self/exe", // Linux, Android
+		"/proc/curproc/exe", // NetBSD
+		"/proc/curproc/file", // DragonFly
+	};
+	for(auto &name : NAMES)
+	{
+		if(ssize_t bytes_written = readlink(name, path, sizeof(path)); bytes_written != -1)
+		{
+			path[bytes_written] = '\0'; // readlink does NOT null-terminate
```
Comment (heinrich5991) [inline src/base/system.cpp:2476]: Potential out of bounds write?

File: src/base/system.h [hunk 5]
```diff
@@ -1394,6 +1394,23 @@ int fs_makedir_rec_for(const char *path);
...
+/**
+ * Gets the absolute path to the executable
+ *
+ * @ingroup Filesystem
+ *
+ * @param buffer Buffer that will receive the path of the executable.
+ * @param buffer_size Size of the buffer.
+ * @param remove_name Whether to remove the filename from the path.
+ *
+ * @return Pointer to the buffer on success, `nullptr` on failure.
```
Comment (heinrich5991) [inline src/base/system.h]: Why return a pointer and not a result value?

File: src/engine/shared/storage.cpp [hunk 6]
```diff
@@ -373,19 +378,16 @@ class CStorage : public IStorage
...
 				if(fs_is_file(aBuf))
 				{
 					return;
 				}
-#if defined(CONF_PLATFORM_MACOS)
-				str_append(m_aBinarydir, "/../../../DDNet-Server.app/Contents/MacOS");
```
Comment (heinrich5991) [inline src/engine/shared/storage.cpp:382]: Why was this remove?

**Comment by CherryEx** [comment]
> > * [ ]  I didn't use generative AI to generate more than single-line completions
> 
> Was this PR generated? To what extent?

I had some conversations with AI to choose correct apis for each OS but that was not my only source.

File: src/base/system.cpp (hunk 1 above)
Comment (CherryEx) [reply src/base/system.cpp]: It's used in the unit test.
And I think it's best we keep this for now until the code is tested more; especially on Mac

File: src/base/system.cpp (hunk 2 above)
Comment (CherryEx) [reply src/base/system.cpp]: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dyld.3.html

This documentation mentions that the returned path may be a symlink and may not be a real path.
~~And, before using realpath I believe the unit test for checking whether the path was absolute was failing, if I remember correctly.~~
The code was probably wrong so it's not related to the path at all.

File: src/engine/shared/storage.cpp (hunk 3 above)
Comment (CherryEx) [reply src/engine/shared/storage.cpp]: Does the priority matter? I believe the nature of this is to check whether the path is valid and these two conditions will check both names; unless I'm missing some detail about this all.

File: src/base/system.cpp (hunk 4 above)
Comment (CherryEx) [reply src/base/system.cpp:2476]: I missed that, thanks.

File: src/base/system.cpp (hunk 1 above)
Comment (heinrich5991) [reply src/base/system.cpp]: I don't like optional parameters. This is unused outside of tests, so it should be removed, in my opinion.

The test should be written to use the same functionality as the code.

File: src/base/system.cpp (hunk 2 above)
Comment (heinrich5991) [reply src/base/system.cpp]: > This documentation mentions that the returned path may be a symlink and may not be a real path.

Is it important that symlinks are resolved for this function? I wouldn't think so.

I'd be interested in an example where this is necessary. What was the path before the call to `realpath`?

File: src/engine/shared/storage.cpp (hunk 3 above)
Comment (heinrich5991) [reply src/engine/shared/storage.cpp]: The change isn't documented in the commit message or anywhere. If it's not documented, it shouldn't be changed.

File: src/base/system.cpp (hunk 4 above)
Comment (CherryEx) [reply src/base/system.cpp:2476]: This should be fixed now.

File: src/base/system.cpp (hunk 1 above)
Comment (CherryEx) [reply src/base/system.cpp]: I don't see any other way to check the validity of the result in the tests.
If you insist, I can remove the parameter and keep the name by default, and remove it inside FindBinaryDirectory after the result is retrieved. (Which would lead to the same outcome, without the optional parameter)

**Comment by heinrich5991** [comment]
Hmm. Maybe this would be a good use case for the Rust bridge — Rust has a function you can call for getting the current executable's path: [`std::env::current_exe`](https://doc.rust-lang.org/stable/std/env/fn.current_exe.html). I guess if you're not already really familiar with Rust, it'd be hard to use that here, though…

**Comment by CherryEx** [comment]
Indeed I'm not really familiar with Rust, but still that feels like too much complexity and this code is not entirely untested.
Most of it is already included in io_currrent_exe. I just changed them a little bit and added the readlink & realpath parts.

File: src/base/system.cpp (hunk 2 above)
Comment (CherryEx) [reply src/base/system.cpp]: Well this function is meant to retrieve the absolute path to the executable, not the symlink.
And the results are directly used in `Storage()` and Http downloader I believe.

**Comment by heinrich5991** [comment]
Hmmm. It's indeed already in `io_current_exe`. Why not use that code by splitting it up instead of writing the thing again?

**Comment by CherryEx** [comment]
I don't see a clean way to split it, unless we prefer to have too many micro functions. one to do the OS calls and then have functions on top to use them for different things?
I doubt the readability of that.
And like for io_current_exe we need a path that we can open a handle to, while in this case we want an absolute path.

File: src/engine/shared/storage.cpp (hunk 6 above)
Comment (CherryEx) [reply src/engine/shared/storage.cpp:382]: I did not find the reason it was there, and it seemed unnecessary.
If the goal is to validate `argv[0]` then why append a path to it? (not to mention that it could even be incorrect because DDNet-Server is not a static name and that it would have stopped working if that name would change one day)

File: src/engine/shared/storage.cpp (hunk 3 above)
Comment (CherryEx) [reply src/engine/shared/storage.cpp]: Well this was not (in my opinion) a big enough change to document, and ~~the results are the same whether the server executable name gets checked first, or the client's~~.

File: src/base/system.cpp (hunk 1 above)
Comment (CherryEx) [reply src/base/system.cpp]: I removed the optional parameter.

File: src/base/system.h (hunk 5 above)
Comment (Robyt3) [reply src/base/system.h]: I suggested it because `fs_getcwd` is also implemented like that. But in either case the return value is only cast to `bool`, so I guess we can also change it to ````@return `0` on success. `1` on failure.````

File: src/engine/shared/storage.cpp (hunk 6 above)
Comment (heinrich5991) [reply src/engine/shared/storage.cpp:382]: Please only remove things you understand. https://en.wikipedia.org/wiki/Wikipedia:Chesterton's_fence.

File: src/base/system.cpp (hunk 2 above)
Comment (CherryEx) [reply src/base/system.cpp]: Good examples would be these implementations:
https://github.com/ddnet/ddnet/blob/3f623af0071f2c266e644e107133bfdf4ba43191/src/engine/shared/storage.cpp#L838-L852
https://github.com/ddnet/ddnet/blob/3f623af0071f2c266e644e107133bfdf4ba43191/src/engine/shared/storage.cpp#L818-L824

Both work with `GetBinaryPath` (`m_Binarydir`  so could be a symlink on mac) and then use it to call system apis such as `rename` and `unlink`, which both don't follow symlinks.
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/rename.2.html
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/unlink.2.html

And I'm quite sure there are more examples because the updater and storage class itself look like they're built with an "absolute path" in mind, and none of them resolve the path, they just use it.

File: src/base/system.h (hunk 5 above)
Comment (CherryEx) [reply src/base/system.h]: Now returns a result value.

File: src/base/system.cpp [hunk 7]
```diff
@@ -2456,6 +2456,71 @@ int fs_storage_path(const char *appname, char *path, int max)
...
+#else
+	char path[IO_MAX_PATH_LENGTH];
+	static const char *NAMES[] = {
+		"/proc/self/exe", // Linux, Android
+		"/proc/curproc/exe", // NetBSD
+		"/proc/curproc/file", // DragonFly
+	};
+	for(auto &name : NAMES)
+	{
+		if(ssize_t bytes_written = readlink(name, path, sizeof(path) - 1); bytes_written != -1)
```
Comment (Robyt3) [inline src/base/system.cpp:2474]: This probably breaks when the executable is a relative symlink, or a symlink to another symlink.

File: src/base/system.cpp [hunk 8]
```diff
@@ -2456,6 +2456,71 @@ int fs_storage_path(const char *appname, char *path, int max)
...
+		{
+			path[bytes_written] = '\0'; // readlink does NOT null-terminate
+			// if the file gets deleted or replaced (not renamed) linux appends (deleted) to the symlink
+			if(char *deleted = strstr(path, " (deleted)"); deleted != nullptr)
+			{
+				*deleted = '\0';
+			}
```
Comment (Robyt3) [inline src/base/system.cpp]: This seems brittle. Does any other library do something like this?

File: src/base/system.h [hunk 9]
```diff
@@ -1394,6 +1394,22 @@ int fs_makedir_rec_for(const char *path);
  */
 int fs_storage_path(const char *appname, char *path, int max);
 
+/**
+ * Gets the absolute path to the executable
```
Comment (Robyt3) [inline src/base/system.h]: `.` at the end.

File: src/base/system.h [hunk 10]
```diff
@@ -1394,6 +1394,22 @@ int fs_makedir_rec_for(const char *path);
...
+ *
+ * @ingroup Filesystem
+ *
+ * @param buffer Buffer that will receive the path of the executable.
+ * @param buffer_size Size of the buffer.
+ *
+ * @return `0` on success. Negative value on failure.
+ *
+ * @remark The executable name is included in the result
```
Comment (Robyt3) [inline src/base/system.h]: `.` at the end.

File: src/base/system.cpp (hunk 8 above)
Comment (Robyt3) [reply src/base/system.cpp]: (To remove the last `" (deleted)"`, this should use `strrstr` not `strstr`.)

File: src/base/system.cpp (hunk 7 above)
Comment (CherryEx) [reply src/base/system.cpp:2474]: But the documentation says that the link contains "the actual pathname of the executed command"
https://www.man7.org/linux/man-pages/man5/proc_pid_exe.5.html

At least on linux, I mean.

File: src/base/system.cpp (hunk 8 above)
Comment (CherryEx) [reply src/base/system.cpp]: Well we need a usable path and " (deleted)" will not be that.
strrstr is fine, but it is not portable because it's not an ISO C function at all. (afaik)
So maybe I should use str_endswith and manually terminate the string or maybe you have a better idea.

File: src/base/system.h (hunk 10 above)
Comment (CherryEx) [reply src/base/system.h]: Fixed

File: src/base/system.h (hunk 9 above)
Comment (CherryEx) [reply src/base/system.h]: Fixed

File: src/base/system.cpp (hunk 2 above)
Comment (CherryEx) [reply src/base/system.cpp]: Actually I just found out that the updater is broken for macOS and it's disabled in release builds.
That said, we still need the absolute path so that we can append the magical `"/../../../DDNet-Server.app/Contents/MacOS"` to it. (Because that's how the "Run Server" button finds the server on macOS)

File: src/base/system.cpp (hunk 8 above)
Comment (Robyt3) [reply src/base/system.cpp]: Hmm, seems to be documented liked that so I guess that's the best we get. But it would be a good idea add the link to the comment because it's otherwise not clear where to find the information.

Using `str_endswith` would work, though you need to convert the returned pointer to an index because it returns a const pointer (and `const_cast` should generally be avoided).

File: src/base/system.cpp (hunk 7 above)
Comment (Robyt3) [reply src/base/system.cpp:2474]: Seems fine then.

But this documentation is for `/proc/pid/exe` which is not in the `NAMES` array. I suppose it should also be added.

Comment (CherryEx) [reply src/base/system.cpp:2474]: `/proc/self` gets translated to `/proc/pid` with 'pid' being the process calling it internally.

Comment (CherryEx) [reply src/base/system.cpp:2474]: `"When a process accesses this magic symbolic link, it resolves to the process's own /proc/pid directory."`
https://www.man7.org/linux/man-pages/man5/proc.5.html

**Comment by CherryEx** [comment]
> Hmmm. It's indeed already in `io_current_exe`. Why not use that code by splitting it up instead of writing the thing again?

@heinrich5991 I made `io_current_exe` use `fs_executable_path` instead of having duplicated code for same thing.

File: src/base/system.cpp (hunk 2 above)
Comment (heinrich5991) [reply src/base/system.cpp]: > Both work with `GetBinaryPath` (`m_Binarydir` so could be a symlink on mac) and then use it to call system apis such as `rename` and `unlink`, which both don't follow symlinks.

Both `rename` and `unlink` support symlinks in the path.

Comment (CherryEx) [reply src/base/system.cpp]: > Both `rename` and `unlink` support symlinks in the path.

I think there's a misunderstanding here. I was more talking about the last component of the path.
The documentation for `_NSGetExecutablePath` was a bit unclear so I might've misunderstood parts of it.
I thought that the last component of the path could be a symlink but it turns out that there's no source to verify that so I'm removing the `realpath` call for now.

File: src/engine/shared/storage.cpp [hunk 11]
```diff
@@ -362,6 +362,23 @@ class CStorage : public IStorage
...
+#if defined(CONF_PLATFORM_MACOS)
+			// No updater for macOS, use server's location so that the client can find the server ("Run Server" button).
+			char aBuf[IO_MAX_PATH_LENGTH];
+			str_append(m_aBinarydir, "/../../../DDNet-Server.app/Contents/MacOS");
+			str_format(aBuf, sizeof(aBuf), "%s/" PLAT_SERVER_EXEC, m_aBinarydir);
+			if(fs_is_file(aBuf))
+			{
+				return;
+			}
+#else
```
Comment (Robyt3) [inline src/engine/shared/storage.cpp]: If this is only for starting the local server on macOS, then maybe we could move this platform-specific code to `local_server.cpp` or we could separately store the client and server binary directories in `CStorage` (and use the same value on non-macOS). Seems weird that this binary path might otherwise be of the client or server depending on how the app was installed. I assume if you build it from source on macOS, you get client and server executable in one folder. But if you install the app package you get two separate apps for client and server, leading to the path segment `/../../../DDNet-Server.app/Contents/MacOS` to navigate from the client folder `/DDNet.app/Contents/MacOS` to the server folder `/DDNet-Server.app/Contents/MacOS`.

File: src/base/system.cpp [hunk 12]
```diff
@@ -426,39 +426,15 @@ IOHANDLE io_stderr()
...
 	}
-	return io_open(path, IOFLAG_READ);
-#else
-	static const char *NAMES[] = {
-		"/proc/self/exe", // Linux, Android
-		"/proc/curproc/exe", // NetBSD
-		"/proc/curproc/file", // DragonFly
-	};
-	for(auto &name : NAMES)
+	else
```
Comment (Robyt3) [inline src/base/system.cpp]: We usually avoid else-branches after if-branches that return.

File: src/engine/shared/storage.cpp (hunk 11 above)
Comment (CherryEx) [reply src/engine/shared/storage.cpp]: I don't think storing two paths is necessary.
Moving macOS specific code to `local_server.cpp` seems like a better idea.

File: src/base/system.cpp (hunk 12 above)
Comment (CherryEx) [reply src/base/system.cpp]: Yeah I think I was sleepy at that point; fixed now.

**Comment by Robyt3** [comment]
Please squash the commits into one and update its description.

**Comment by Robyt3** [comment]
@Pioooooo Could you test this again now that the macOS build and CI artifacts should work again? Specifically, launch the client from inside the dmg, then check whether launching the local server from within the client works.

**Comment by Pioooooo** [comment]
It needs to be rebased onto master

**Comment by Pioooooo** [comment]
i rebased on my local branch and tested packaged dmg, and it's working

**Comment by Robyt3** [comment]
Thanks for testing, @Pioooooo.

Thanks for implementing, @CherryEx.
