### PR TITLE
Use text and quad containers for MOTD rendering, fix MOTD height calculation

### LINKED ISSUE #6346: Discrepancy of text line height depending on mapped screen size and font size
With the current font size 16 used for the ingame server info MOTD, the line height is calculated inaccurately:

textrender-lineheight-16

There is an empty space at the bottom due to the text not being rendered at exact positions aligned with the text lines. The line height is always identical to the font size.

If you change the font size to 10, then this space disappears, as the font size is now perfectly aligned with the height of the mapped screen (which is 600 for the UI):

textrender-lineheight-10

Seems like there is some rounding error introduced somewhere in the text render.

For testing I used `sv_motd "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30"`. The extra space decreases if less lines are present.

### PR DESCRIPTION
**Pull request by Robyt3**
Optimize MOTD rendering by caching the round rect and the text.

Use the correct text height based on the aligned font size instead of the original font size, to fix the discrepancy between the scrollable height and the text height. Closes #6346.

Screenshots:

- Tutorial, ingame:
   - Before: 
Tutorial ingame old
   - After:
Tutorial ingame new
- Multeasymap, ingame:
   - Before: 
Multeasymap ingame old
   - After:
Multeasymap ingame new
- Test server, ingame:
   - Before: 
Testing ingame new
   - After: 
Testing ingame old
- Long, ingame:
   - Before: 
Long ingame old
   - After:
Long ingame new
- Long, menu:
   - Before: 
Long menu old
   - After:
Long menu new

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

File: src/game/client/components/motd.h [hunk 1]
```diff
@@ -6,18 +6,24 @@
 
 class CMotd : public CComponent
 {
-	// motd
+	char m_aServerMotd[900];
```
Comment (def-) [inline src/game/client/components/motd.h:9]: magic 900?

Comment (Robyt3) [reply src/game/client/components/motd.h]: I replaced it with `std::size(g_Config.m_SvMotd)`, as the size of the `sv_motd` config variable is also `900`. No idea why it's specifically 900 though.

Comment (def-) [reply src/game/client/components/motd.h]: So that it fits inside of a single network packet.

**Comment by def-** [comment]
bors r+
Thanks
